SET sql_mode = 'NO_ENGINE_SUBSTITUTION';
SET GLOBAL innodb_default_row_format=compact;
CREATE TABLE t1 ( id int(11) NOT NULL AUTO_INCREMENT, year year DEFAULT NULL, modified timestamp NOT NULL DEFAULT '0000-00-00 00:00:00', PRIMARY KEY (id) ) ENGINE=InnoDB ROW_FORMAT=COMPACT PARTITION BY HASH (id) PARTITIONS 2;
ALTER TABLE t2 REMOVE PARTITIONING;
SHOW CREATE TABLE t1;
INSERT INTO t1 VALUES (1),(2),(3);
