# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = mysql-server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = mysql-server/bld

# Include any dependencies generated for this target.
include depend.make

# Include the compile flags for this target's objects.
include flags.make

join_syntax-t.cc.o: flags.make
join_syntax-t.cc.o: join_syntax-t.cc
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object join_syntax-t.cc.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o join_syntax-t.cc.o -c join_syntax-t.cc

join_syntax-t.cc.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to join_syntax-t.cc.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E join_syntax-t.cc > join_syntax-t.cc.i

join_syntax-t.cc.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly join_syntax-t.cc.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S join_syntax-t.cc -o join_syntax-t.cc.s

join_syntax-t: join_syntax-t.cc.o
join_syntax-t: Makefile
# join_syntax-t: mysql-server/bld/unittest/gunit/libgunit_large.a
join_syntax-t: mysql-server/bld/library_output_directory/libserver_unittest_library.so
join_syntax-t: mysql-server/bld/libgmock.a
join_syntax-t: mysql-server/bld/libgtest.a
join_syntax-t: mysql-server/bld/sql/libsql_main.a
join_syntax-t: mysql-server/bld/storage/innobase/libinnobase.a
join_syntax-t: mysql-server/bld/sql/libsql_dd.a
join_syntax-t: mysql-server/bld/sql/libsql_gis.a
join_syntax-t: mysql-server/bld/sql/librpl.a
join_syntax-t: mysql-server/bld/sql/libmaster.a
join_syntax-t: mysql-server/bld/sql/libslave.a
join_syntax-t: mysql-server/bld/sql/libbinlog.a
join_syntax-t: mysql-server/bld/storage/archive/libarchive.a
join_syntax-t: mysql-server/bld/storage/blackhole/libblackhole.a
join_syntax-t: mysql-server/bld/storage/csv/libcsv.a
join_syntax-t: mysql-server/bld/storage/federated/libfederated.a
join_syntax-t: mysql-server/bld/storage/heap/libheap.a
join_syntax-t: mysql-server/bld/storage/heap/libheap_library.a
join_syntax-t: mysql-server/bld/sql/server_component/libmysql_server_component_services.a
join_syntax-t: mysql-server/bld/archive_output_directory/libvio.a
join_syntax-t: mysql-server/bld/sql/protobuf/librpl_protobuf_lite.a
join_syntax-t: mysql-server/bld/libbinlogevents/lib/libbinlogevents.a
join_syntax-t: mysql-server/bld/storage/myisam/libmyisam.a
join_syntax-t: mysql-server/bld/storage/myisam/libmyisam_library.a
join_syntax-t: mysql-server/bld/archive_output_directory/libmysys.a
join_syntax-t: mysql-server/bld/archive_output_directory/libstrings.a
join_syntax-t: mysql-server/bld/archive_output_directory/libmysys.a
join_syntax-t: mysql-server/bld/archive_output_directory/libstrings.a
join_syntax-t: mysql-server/bld/archive_output_directory/libz.a
join_syntax-t: mysql-server/bld/archive_output_directory/libmytime.a
join_syntax-t: mysql-server/bld/archive_output_directory/libzstd.a
join_syntax-t: /usr/lib/x86_64-linux-gnu/libssl.so
join_syntax-t: /usr/lib/x86_64-linux-gnu/libcrypto.so
join_syntax-t: mysql-server/bld/storage/myisammrg/libmyisammrg.a
join_syntax-t: mysql-server/bld/storage/perfschema/libperfschema.a
join_syntax-t: mysql-server/bld/storage/temptable/libtemptable.a
join_syntax-t: mysql-server/bld/plugin/fulltext/libngram_parser.a
join_syntax-t: mysql-server/bld/plugin/x/libmysqlx.a
join_syntax-t: mysql-server/bld/liblz4_lib.a
join_syntax-t: mysql-server/bld/extra/libevent/libevent-2.1.11-stable/lib/libevent_extra.a
join_syntax-t: mysql-server/bld/extra/libevent/libevent-2.1.11-stable/lib/libevent_openssl.a
join_syntax-t: mysql-server/bld/extra/libevent/libevent-2.1.11-stable/lib/libevent_core.a
join_syntax-t: mysql-server/bld/extra/libevent/libevent-2.1.11-stable/lib/libevent_pthreads.a
join_syntax-t: mysql-server/bld/extra/icu/source/i18n/libicui18n.a
join_syntax-t: mysql-server/bld/extra/icu/source/common/libicuuc.a
join_syntax-t: mysql-server/bld/extra/icu/source/stubdata/libicustubdata.a
join_syntax-t: mysql-server/bld/plugin/x/protocol/protobuf/libmysqlxmessages_lite.a
join_syntax-t: mysql-server/bld/library_output_directory/libprotobuf-lite.so.3.11.4
join_syntax-t: mysql-server/bld/components/libminchassis/libminchassis.a
join_syntax-t: link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold "Linking CXX executable join_syntax-t"
	$(CMAKE_COMMAND) -E cmake_link_script link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
build: join_syntax-t

.PHONY : build

clean:
	$(CMAKE_COMMAND) -P cmake_clean.cmake
.PHONY : clean

depend:
	$(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" \
		mysql-server \
		mysql-server/unittest/gunit \
		mysql-server/bld \
		mysql-server/bld/unittest/gunit \
		/home/server1/Documents/Projects/parser/join_syntax-t.dir/DependInfo.cmake \
		--color=$(COLOR)
.PHONY : depend

