CREATE UNDO TABLESPACE undo_003 ADD DATAFILE 'undo_003.ibu' ENGINE MyISAM;
ALTER UNDO TABLESPACE undo_003 SET ACTIVE ENGINE MyISAM;
ALTER UNDO TABLESPACE undo_003 SET INACTIVE ENGINE MyISAM;
DROP UNDO TABLESPACE undo_003 ENGINE MyISAM;
