CREATE TABLE t1 ( i1 INTEGER, i2 INTEGER, i3 INTEGER, KEY(i1,i2) ) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1, 1, 1), (1, 1, 1),(1, 1, 1),(1, 1, 1), (2, 2, 1), (2, 2, 1),(2, 2, 1),(2, 2, 1), (3, 3, 1), (3, 3, 1),(3, 3, 1),(3, 3, 1);
ANALYZE TABLE t1;
EXPLAIN FORMAT=JSON SELECT i3 FROM t1 WHERE i1 = 1 AND i2 = 1;
EXPLAIN FORMAT=JSON SELECT i3 FROM t1 WHERE i1 = 1 AND i3 = 1;
UPDATE mysql.server_cost SET cost_value=0.1 WHERE cost_name="row_evaluate_cost";
UPDATE mysql.server_cost SET cost_value=0.05 WHERE cost_name="key_compare_cost";
UPDATE mysql.server_cost SET cost_value=1.0 WHERE cost_name="memory_temptable_create_cost";
UPDATE mysql.server_cost SET cost_value=0.1 WHERE cost_name="memory_temptable_row_cost";
UPDATE mysql.server_cost SET cost_value=20 WHERE cost_name="disk_temptable_create_cost";
UPDATE mysql.server_cost SET cost_value=0.5 WHERE cost_name="disk_temptable_row_cost";
UPDATE mysql.engine_cost SET cost_value=0.25 WHERE cost_name="memory_block_read_cost";
UPDATE mysql.engine_cost SET cost_value=1.0 WHERE cost_name="io_block_read_cost";
UPDATE mysql.server_cost SET cost_value = 2 * cost_value;
UPDATE mysql.engine_cost SET cost_value = 2 * cost_value;
SELECT cost_name, cost_value FROM mysql.server_cost;
SELECT cost_name, cost_value FROM mysql.engine_cost;
FLUSH OPTIMIZER_COSTS;
EXPLAIN FORMAT=JSON SELECT i3 FROM t1 WHERE i1 = 1 AND i2 = 1;
EXPLAIN FORMAT=JSON SELECT i3 FROM t1 WHERE i1 = 1 AND i3 = 1;
UPDATE mysql.server_cost SET cost_value=DEFAULT;
UPDATE mysql.engine_cost SET cost_value=DEFAULT;
FLUSH OPTIMIZER_COSTS;
DROP TABLE t1;
CREATE TABLE t1 ( pk INTEGER PRIMARY KEY, a INTEGER, b INTEGER, c CHAR(255), UNIQUE KEY k1 (a) );
INSERT INTO t1 VALUES (1, 1, NULL, "Abc"), (2, 2, NULL, "Abc"), (3, 3, NULL, "Abc"), (4, 4, NULL, "Abc");
INSERT INTO t1 SELECT a + 4, a + 4, b, c FROM t1;
INSERT INTO t1 SELECT a + 8, a + 8, b, c FROM t1;
INSERT INTO t1 SELECT a + 16, a + 16, b, c FROM t1;
INSERT INTO t1 SELECT a + 32, a + 32, b, c FROM t1;
INSERT INTO t1 SELECT a + 64, a + 64, b, c FROM t1;
INSERT INTO t1 SELECT a + 128, a + 128, b, c FROM t1;
CREATE TABLE t2 ( d INTEGER PRIMARY KEY, e INTEGER );
INSERT INTO t2 SELECT a, b FROM t1;
ANALYZE TABLE t1, t2;
EXPLAIN FORMAT=JSON SELECT * FROM t1 JOIN t2 ON b=d ORDER BY a LIMIT 4;
UPDATE mysql.server_cost SET cost_value=0.1 WHERE cost_name="row_evaluate_cost";
UPDATE mysql.server_cost SET cost_value=0.05 WHERE cost_name="key_compare_cost";
UPDATE mysql.server_cost SET cost_value=1.0 WHERE cost_name="memory_temptable_create_cost";
UPDATE mysql.server_cost SET cost_value=0.1 WHERE cost_name="memory_temptable_row_cost";
UPDATE mysql.server_cost SET cost_value=20 WHERE cost_name="disk_temptable_create_cost";
UPDATE mysql.server_cost SET cost_value=0.5 WHERE cost_name="disk_temptable_row_cost";
UPDATE mysql.engine_cost SET cost_value=0.25 WHERE cost_name="memory_block_read_cost";
UPDATE mysql.engine_cost SET cost_value=1.0 WHERE cost_name="io_block_read_cost";
UPDATE mysql.server_cost SET cost_value = 0.5 * cost_value;
UPDATE mysql.engine_cost SET cost_value = 0.5 * cost_value;
SELECT cost_name, cost_value FROM mysql.server_cost;
SELECT cost_name, cost_value FROM mysql.engine_cost;
FLUSH OPTIMIZER_COSTS;
EXPLAIN FORMAT=JSON SELECT * FROM t1 JOIN t2 ON b=d ORDER BY a LIMIT 4;
UPDATE mysql.server_cost SET cost_value=DEFAULT;
UPDATE mysql.engine_cost SET cost_value=DEFAULT;
FLUSH OPTIMIZER_COSTS;
DROP TABLE t1, t2;
