CREATE TABLE t0 ( i1 INTEGER );
INSERT INTO t0 VALUE (0),(1),(2),(3),(4),(5),(6),(7),(8),(9);
CREATE TABLE t1 ( pk INTEGER PRIMARY KEY, i1 INTEGER NOT NULL, c1 CHAR(250), c2 CHAR(250), c3 CHAR(250), c4 CHAR(250), INDEX i1_key (i1) ) ENGINE=InnoDB;
INSERT INTO t1 SELECT a0.i1 + 10 * a1.i1, a0.i1, 'abc', 'def', 'ghi', 'jkl' FROM t0 AS a0, t0 AS a1 ORDER BY a0.i1, a1.i1;
ANALYZE TABLE t1;
EXPLAIN FORMAT=JSON SELECT * FROM t1;
UPDATE mysql.server_cost SET cost_value=0.4 WHERE cost_name="row_evaluate_cost";
FLUSH OPTIMIZER_COSTS;
EXPLAIN FORMAT=JSON SELECT * FROM t1;
UPDATE mysql.server_cost SET cost_value=DEFAULT;
UPDATE mysql.server_cost SET cost_value=0.2 WHERE cost_name="row_evaluate_cost";
FLUSH OPTIMIZER_COSTS;
EXPLAIN FORMAT=JSON SELECT * FROM t1;
UPDATE mysql.server_cost SET cost_value=DEFAULT;
EXPLAIN FORMAT=JSON SELECT DISTINCT(i1) FROM t1;
UPDATE mysql.server_cost SET cost_value=0.1 WHERE cost_name="key_compare_cost";
FLUSH OPTIMIZER_COSTS;
EXPLAIN FORMAT=JSON SELECT DISTINCT(i1) FROM t1;
UPDATE mysql.server_cost SET cost_value=DEFAULT;
EXPLAIN FORMAT=JSON SELECT * FROM t1 WHERE i1 IN (SELECT i1 FROM t1);
UPDATE mysql.server_cost SET cost_value=10.0 WHERE cost_name="memory_temptable_create_cost";
FLUSH OPTIMIZER_COSTS;
EXPLAIN FORMAT=JSON SELECT * FROM t1 WHERE i1 IN (SELECT i1 FROM t1);
UPDATE mysql.server_cost SET cost_value=DEFAULT;
EXPLAIN FORMAT=JSON SELECT * FROM t1 WHERE i1 IN (SELECT i1 FROM t1);
UPDATE mysql.server_cost SET cost_value=0.2 WHERE cost_name="memory_temptable_row_cost";
FLUSH OPTIMIZER_COSTS;
EXPLAIN FORMAT=JSON SELECT * FROM t1 WHERE i1 IN (SELECT i1 FROM t1);
UPDATE mysql.server_cost SET cost_value=DEFAULT;
set global internal_tmp_mem_storage_engine='memory';
set session internal_tmp_mem_storage_engine='memory';
set @max_heap_table_size_save= @@max_heap_table_size;
set max_heap_table_size= 16384;
EXPLAIN FORMAT=JSON SELECT * FROM t1 WHERE c1 IN (SELECT c1 FROM t1);
UPDATE mysql.server_cost SET cost_value=40.0 WHERE cost_name="disk_temptable_create_cost";
FLUSH OPTIMIZER_COSTS;
set max_heap_table_size= 16384;
EXPLAIN FORMAT=JSON SELECT * FROM t1 WHERE c1 IN (SELECT c1 FROM t1);
UPDATE mysql.server_cost SET cost_value=DEFAULT;
EXPLAIN FORMAT=JSON SELECT * FROM t1 WHERE c1 IN (SELECT c1 FROM t1);
UPDATE mysql.server_cost SET cost_value=1.0 WHERE cost_name="disk_temptable_row_cost";
FLUSH OPTIMIZER_COSTS;
set max_heap_table_size= 16384;
EXPLAIN FORMAT=JSON SELECT * FROM t1 WHERE c1 IN (SELECT c1 FROM t1);
UPDATE mysql.server_cost SET cost_value=DEFAULT;
set max_heap_table_size= @max_heap_table_size_save;
set session internal_tmp_mem_storage_engine=default;
set global internal_tmp_mem_storage_engine=default;
EXPLAIN FORMAT=JSON SELECT * FROM t1;
UPDATE mysql.engine_cost SET cost_value=0.5 WHERE cost_name="memory_block_read_cost";
FLUSH OPTIMIZER_COSTS;
EXPLAIN FORMAT=JSON SELECT * FROM t1;
UPDATE mysql.engine_cost SET cost_value=DEFAULT;
FLUSH OPTIMIZER_COSTS;
DROP TABLE t0,t1;
