SELECT cost_name,cost_value FROM mysql.server_cost;
SELECT engine_name,cost_name,cost_value FROM mysql.engine_cost;
CREATE TABLE t0 ( i1 INTEGER );
INSERT INTO t0 VALUE (0),(1),(2),(3),(4),(5),(6),(7),(8),(9);
CREATE TABLE t1_innodb ( pk INTEGER PRIMARY KEY, i1 INTEGER NOT NULL, c1 CHAR(250), c2 CHAR(250), c3 CHAR(250), c4 CHAR(250), INDEX i1_key (i1) ) ENGINE=InnoDB;
INSERT INTO t1_innodb SELECT a0.i1 + 10 * a1.i1, a0.i1, 'abc', 'def', 'ghi', 'jkl' FROM t0 AS a0, t0 AS a1 ORDER BY a0.i1, a1.i1;
ANALYZE TABLE t1_innodb;
EXPLAIN FORMAT=JSON SELECT * FROM t1_innodb;
UPDATE mysql.server_cost  SET cost_value=0.4 WHERE cost_name="row_evaluate_cost";
UPDATE mysql.engine_cost SET cost_value=2.0 WHERE cost_name="memory_block_read_cost";
UPDATE mysql.engine_cost SET cost_value=2.0 WHERE cost_name="io_block_read_cost";
SELECT cost_name, cost_value FROM mysql.server_cost;
SELECT engine_name, cost_name, cost_value FROM mysql.engine_cost;
EXPLAIN FORMAT=JSON SELECT * FROM t1_innodb;
UPDATE mysql.server_cost SET cost_value=DEFAULT;
UPDATE mysql.engine_cost SET cost_value=DEFAULT;
INSERT INTO mysql.engine_cost VALUES ("InnoDB", 0, "memory_block_read_cost", 4.0, CURRENT_TIMESTAMP, DEFAULT, DEFAULT);
INSERT INTO mysql.engine_cost VALUES ("InnoDB", 0, "io_block_read_cost", 4.0, CURRENT_TIMESTAMP, DEFAULT, DEFAULT);
SELECT cost_name, cost_value FROM mysql.server_cost;
SELECT engine_name, cost_name, cost_value FROM mysql.engine_cost;
EXPLAIN FORMAT=JSON SELECT * FROM t1_innodb;
DELETE FROM mysql.engine_cost WHERE engine_name NOT LIKE "default";
DROP TABLE t0, t1_innodb;
