SET @old_innodb_stats_persistent= @@global.innodb_stats_persistent;
SET @@global.innodb_stats_persistent= 0;
create table thread_to_monitor(thread_id int);
insert into thread_to_monitor(thread_id) SELECT THREAD_ID FROM performance_schema.threads WHERE PROCESSLIST_ID=CONNECTION_ID();
CREATE TABLE t1 (a int PRIMARY KEY, b varchar(128), KEY (b)) ENGINE = InnoDB PARTITION BY HASH (a) PARTITIONS 13;
CREATE TABLE t2 (a int PRIMARY KEY AUTO_INCREMENT, b varchar(128)) ENGINE = InnoDB PARTITION BY HASH (a) PARTITIONS 13;
SHOW CREATE TABLE t1;
SHOW CREATE TABLE t2;
FLUSH STATUS;
INSERT INTO t1 VALUES (1, 'First row, p1');
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t1 VALUES (1, 'First row, duplicate');
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t1 VALUES (0, 'First row, p0'), (2, 'First row, p2'), (3, 'First row, p3'), (4, 'First row, p4');
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t1 VALUES (1 * 13, 'Second row, p0'), (2 * 13, 'Third row, p0'), (3 * 13, 'Fourth row, p0'), (4 * 13, 'Fifth row, p0');
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t2 VALUES (NULL, 'First auto-inc row');
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t2 (b) VALUES ('Second auto-inc row');
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t2 VALUES (10, "First row, p10");
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
UPDATE t2 SET b = CONCAT(b, ", UPDATED") WHERE a = 10;
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
CREATE TABLE t3 (a INT, b CHAR(10)) PARTITION BY HASH (a) PARTITIONS 2;
SHOW CREATE TABLE t3;
FLUSH STATUS;
INSERT INTO t3 VALUES (1, "Test 1");
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 VALUES (2, "Test 2"), (3, "Test 3"), (4, "Test 4");
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 VALUES (6, "Test 6"), (8, "Test 8"), (10, "Test 10");
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 VALUES (5, "Test 5"), (7, "Test 7"), (9, "Test 9");
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 VALUES (0, "Test 0");
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (a, b) VALUES (1, "Test 1");
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (a, b) VALUES (2, "Test 2"), (3, "Test 3"), (4, "Test 4");
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (a, b) VALUES (6, "Test 6"), (8, "Test 8"), (10, "Test 10");
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (a, b) VALUES (5, "Test 5"), (7, "Test 7"), (9, "Test 9");
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (a, b) VALUES (0, "Test 0");
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (a) VALUES (1);
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (a) VALUES (2), (3), (4);
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (a) VALUES (6), (8), (10);
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (a) VALUES (5), (7), (9);
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (b) VALUES ("Only b 1");
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (b) VALUES ("Only b 2"), ("Only b 3");
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
SELECT * FROM t3 ORDER BY a, b;
DROP TABLE t3;
CREATE TABLE t3 (a int DEFAULT 10, b varchar(64) DEFAULT "Default", c varchar(64) DEFAULT "Default", d int unsigned DEFAULT 9, e varchar(255) DEFAULT "Default-filler.filler.filler.", PRIMARY KEY (a,b,c,d)) charset latin1 PARTITION BY RANGE COLUMNS (a, b) SUBPARTITION BY LINEAR KEY (d, c) SUBPARTITIONS 4 (PARTITION pNeg VALUES LESS THAN (0, ""), PARTITION `p0-9` VALUES LESS THAN (9, MAXVALUE), PARTITION p10 VALUES LESS THAN (10, MAXVALUE), PARTITION `p11-100` VALUES LESS THAN (99, MAXVALUE));
SHOW CREATE TABLE t3;
FLUSH STATUS;
INSERT INTO t3 () VALUES ();
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT IGNORE INTO t3 VALUES (-1, "ZZZzzzz", "yyyYYY", -1, DEFAULT);
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 () VALUES (0, "", "", 0, NULL);
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (a) VALUES (1);
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (a, b) VALUES (1, "Part expr fulfilled"), (10, "Part expr fulfilled");
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (d) VALUES (1), (2);
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (c, d) VALUES ("Subpart expr fulfilled", 1);
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (a, b, d) VALUES (10, "Full part, half subpart", 1), (12, "Full part, half subpart", 1), (12, "Full part, half subpart", 2), (12, "Full part, half subpart", 3), (12, "Full part, half subpart", 4), (12, "Full part, half subpart", 0);
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (a, b, c) VALUES (1, "Full part", "Half subpart");
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (a, c, d) VALUES (12, "Half part, full subpart", 1), (12, "Half part, full subpartDefault", 1), (12, "Half part, full subpart Default", 1);
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (b, c, d) VALUES ("Half part", "Full subpart", 1);
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
FLUSH STATUS;
INSERT INTO t3 (a, b, c, d) VALUES (1, "Full part", "Full subpart", 1);
SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.status_by_thread WHERE VARIABLE_NAME LIKE 'HANDLER_%' AND VARIABLE_VALUE > 0 AND THREAD_ID IN (SELECT thread_id from test.thread_to_monitor);
