SET @@GLOBAL.table_definition_cache=DEFAULT;
SELECT IF (@@open_files_limit < 5000, 2000, @@GLOBAL.table_definition_cache);
SELECT @@GLOBAL.table_definition_cache;
SET @@GLOBAL.table_definition_cache=DEFAULT;
SELECT IF (@@open_files_limit < 5000, 2000, @@GLOBAL.table_definition_cache);
SET @@local.table_definition_cache=1;
SET @@session.table_definition_cache=1;
SET @@GLOBAL.table_definition_cache=1;
SET @@GLOBAL.table_definition_cache=DEFAULT;
SELECT IF (@@open_files_limit < 5000, 2000, @@GLOBAL.table_definition_cache);
SELECT @@GLOBAL.table_definition_cache = VARIABLE_VALUE FROM performance_schema.global_variables WHERE VARIABLE_NAME='table_definition_cache';
SELECT COUNT(@@GLOBAL.table_definition_cache);
SELECT COUNT(VARIABLE_VALUE) FROM performance_schema.global_variables  WHERE VARIABLE_NAME='table_definition_cache';
SELECT @@table_definition_cache = @@GLOBAL.table_definition_cache;
SELECT COUNT(@@local.table_definition_cache);
SELECT COUNT(@@SESSION.table_definition_cache);
SELECT COUNT(@@GLOBAL.table_definition_cache);
SELECT table_definition_cache = @@SESSION.table_definition_cache;
flush tables;
flush status;
set @dd_definitions = 14;
set @Open_table_definitions = (select variable_value from performance_schema.session_status where variable_name ='Open_table_definitions') + @dd_definitions;
set @Opened_table_definitions = (select variable_value from performance_schema.session_status where variable_name ='Opened_table_definitions') + @dd_definitions;
DROP TABLE IF EXISTS tab1;
DROP TABLE IF EXISTS tab2;
CREATE TABLE tab1 (col_1 text(10)) ENGINE=INNODB ;
CREATE TABLE tab2 (col_1 text(10)) ENGINE=INNODB ;
select (select variable_value from performance_schema.session_status where variable_name ='Open_table_definitions') = @Open_table_definitions;
select (select variable_value from performance_schema.session_status where variable_name ='Opened_table_definitions') = @Opened_table_definitions + 2;
select 1 from tab1;
select (select variable_value from performance_schema.session_status where variable_name ='Open_table_definitions') = @Open_table_definitions + 1;
select (select variable_value from performance_schema.session_status where variable_name ='Opened_table_definitions') = @Opened_table_definitions + 3;
select 1 from tab2;
select (select variable_value from performance_schema.session_status where variable_name ='Open_table_definitions') = @Open_table_definitions + 2;
select (select variable_value from performance_schema.session_status where variable_name ='Opened_table_definitions') = @Opened_table_definitions + 4;
DROP TABLE IF EXISTS tab1;
select (select variable_value from performance_schema.session_status where variable_name ='Open_table_definitions') = @Open_table_definitions + 1 + 2;
select (select variable_value from performance_schema.session_status where variable_name ='Opened_table_definitions') = @Opened_table_definitions + 4 + 2;
DROP TABLE IF EXISTS tab2;
select (select variable_value from performance_schema.session_status where variable_name ='Open_table_definitions') = @Open_table_definitions + 2;
select (select variable_value from performance_schema.session_status where variable_name ='Opened_table_definitions') = @Opened_table_definitions + 4 + 2;
set @@GLOBAL.table_definition_cache=DEFAULT;
