SET default_storage_engine=InnoDB;
SET SESSION innodb_strict_mode = ON;
SET GLOBAL innodb_file_per_table = OFF;
CREATE TABLE t1 (a int KEY, b text) ENGINE = InnoDB PARTITION BY HASH (a) (PARTITION p0 engine=InnoDB DATA DIRECTORY='/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/alternate_dir/data' INDEX DIRECTORY='/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/alternate_dir/data', PARTITION p1 engine=InnoDB DATA DIRECTORY='/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/alternate_dir/data' INDEX DIRECTORY='/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/alternate_dir/data');
SHOW WARNINGS;
SET GLOBAL innodb_file_per_table = ON;
CREATE TABLE t1 (a int KEY, b text) ENGINE = InnoDB PARTITION BY HASH (a) (PARTITION p0 engine=InnoDB DATA DIRECTORY='/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/alternate_dir/data', PARTITION p1 engine=InnoDB DATA DIRECTORY='/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/alternate_dir/data2');
SHOW WARNINGS;
SHOW CREATE TABLE t1;
SELECT t.name 'Table Name', IFNULL(s.name, 'innodb_system') 'Tablespace', t.flag 'Table Flags', t.n_cols 'Columns', t.row_format 'Row Format', t.zip_page_size 'Zip Size', t.space_type 'Space Type' 	FROM information_schema.innodb_tables t LEFT JOIN information_schema.innodb_tablespaces s ON t.space = s.space WHERE t.name not like 'mysql/%' 	AND t.name NOT LIKE 'sys/%' 	ORDER BY t.name;
SELECT s.name 'Space_Name', s.space_type 'Space_Type', s.page_size 'Page_Size', s.zip_page_size 'Zip_Size', s.fs_block_size!=0 'BlockSize!=0', s.file_size!=0 'FileSize!=0', s.row_format 'Formats_Permitted', d.path 'Path' 	FROM information_schema.innodb_tablespaces s, information_schema.innodb_datafiles d WHERE s.space = d.space AND d.path NOT LIKE '%/sys/%' 	AND d.path NOT LIKE '%\\\sys\\\%' 	AND s.name NOT LIKE 'mysql/%' 	AND s.name NOT LIKE 'sys/%' 	AND s.name NOT LIKE '%undo%' 	ORDER BY s.name, d.path;
SELECT	s.name 'Space_Name', f.file_type 'File_Type', f.engine 'Engine', f.status 'Status', f.tablespace_name 'Tablespace_Name', f.file_name 'Path' 	FROM information_schema.files f, information_schema.innodb_tablespaces s WHERE f.file_id = s.space AND f.file_name NOT LIKE '%/sys/%' 	AND f.file_name NOT LIKE '%\\\sys\\\%' 	AND s.name NOT LIKE 'mysql' 	AND s.name NOT LIKE 'sys/%' 	AND s.name NOT LIKE 'innodb_temporary' 	AND s.name NOT LIKE '%undo%' 	ORDER BY s.name, f.file_name;
INSERT INTO t1 VALUES (1, "red");
INSERT INTO t1 VALUES (2, "green");
INSERT INTO t1 VALUES (3, "blue");
SELECT * FROM t1;
TRUNCATE TABLE t1;
SELECT * FROM t1;
SHOW CREATE TABLE t1;
SELECT t.name 'Table Name', IFNULL(s.name, 'innodb_system') 'Tablespace', t.flag 'Table Flags', t.n_cols 'Columns', t.row_format 'Row Format', t.zip_page_size 'Zip Size', t.space_type 'Space Type' 	FROM information_schema.innodb_tables t LEFT JOIN information_schema.innodb_tablespaces s ON t.space = s.space WHERE t.name not like 'mysql/%' 	AND t.name NOT LIKE 'sys/%' 	ORDER BY t.name;
SELECT s.name 'Space_Name', s.space_type 'Space_Type', s.page_size 'Page_Size', s.zip_page_size 'Zip_Size', s.fs_block_size!=0 'BlockSize!=0', s.file_size!=0 'FileSize!=0', s.row_format 'Formats_Permitted', d.path 'Path' 	FROM information_schema.innodb_tablespaces s, information_schema.innodb_datafiles d WHERE s.space = d.space AND d.path NOT LIKE '%/sys/%' 	AND d.path NOT LIKE '%\\\sys\\\%' 	AND s.name NOT LIKE 'mysql/%' 	AND s.name NOT LIKE 'sys/%' 	AND s.name NOT LIKE '%undo%' 	ORDER BY s.name, d.path;
SELECT	s.name 'Space_Name', f.file_type 'File_Type', f.engine 'Engine', f.status 'Status', f.tablespace_name 'Tablespace_Name', f.file_name 'Path' 	FROM information_schema.files f, information_schema.innodb_tablespaces s WHERE f.file_id = s.space AND f.file_name NOT LIKE '%/sys/%' 	AND f.file_name NOT LIKE '%\\\sys\\\%' 	AND s.name NOT LIKE 'mysql' 	AND s.name NOT LIKE 'sys/%' 	AND s.name NOT LIKE 'innodb_temporary' 	AND s.name NOT LIKE '%undo%' 	ORDER BY s.name, f.file_name;
RENAME TABLE t1 TO t11;
SHOW CREATE TABLE t11;
SELECT t.name 'Table Name', IFNULL(s.name, 'innodb_system') 'Tablespace', t.flag 'Table Flags', t.n_cols 'Columns', t.row_format 'Row Format', t.zip_page_size 'Zip Size', t.space_type 'Space Type' 	FROM information_schema.innodb_tables t LEFT JOIN information_schema.innodb_tablespaces s ON t.space = s.space WHERE t.name not like 'mysql/%' 	AND t.name NOT LIKE 'sys/%' 	ORDER BY t.name;
SELECT s.name 'Space_Name', s.space_type 'Space_Type', s.page_size 'Page_Size', s.zip_page_size 'Zip_Size', s.fs_block_size!=0 'BlockSize!=0', s.file_size!=0 'FileSize!=0', s.row_format 'Formats_Permitted', d.path 'Path' 	FROM information_schema.innodb_tablespaces s, information_schema.innodb_datafiles d WHERE s.space = d.space AND d.path NOT LIKE '%/sys/%' 	AND d.path NOT LIKE '%\\\sys\\\%' 	AND s.name NOT LIKE 'mysql/%' 	AND s.name NOT LIKE 'sys/%' 	AND s.name NOT LIKE '%undo%' 	ORDER BY s.name, d.path;
SELECT	s.name 'Space_Name', f.file_type 'File_Type', f.engine 'Engine', f.status 'Status', f.tablespace_name 'Tablespace_Name', f.file_name 'Path' 	FROM information_schema.files f, information_schema.innodb_tablespaces s WHERE f.file_id = s.space AND f.file_name NOT LIKE '%/sys/%' 	AND f.file_name NOT LIKE '%\\\sys\\\%' 	AND s.name NOT LIKE 'mysql' 	AND s.name NOT LIKE 'sys/%' 	AND s.name NOT LIKE 'innodb_temporary' 	AND s.name NOT LIKE '%undo%' 	ORDER BY s.name, f.file_name;
DROP TABLE t11;
SET GLOBAL innodb_file_per_table = ON;
PREPARE stmt1 FROM "CREATE TABLE t1 (a int KEY, b text)      ENGINE = InnoDB PARTITION BY HASH (a)      (PARTITION p0 engine=InnoDB DATA DIRECTORY='/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/alternate_dir/data',       PARTITION p1 engine=InnoDB DATA DIRECTORY='/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/alternate_dir/data2')";
EXECUTE stmt1;
SHOW WARNINGS;
DEALLOCATE PREPARE stmt1;
SHOW CREATE TABLE t1;
SELECT t.name 'Table Name', IFNULL(s.name, 'innodb_system') 'Tablespace', t.flag 'Table Flags', t.n_cols 'Columns', t.row_format 'Row Format', t.zip_page_size 'Zip Size', t.space_type 'Space Type' 	FROM information_schema.innodb_tables t LEFT JOIN information_schema.innodb_tablespaces s ON t.space = s.space WHERE t.name not like 'mysql/%' 	AND t.name NOT LIKE 'sys/%' 	ORDER BY t.name;
SELECT s.name 'Space_Name', s.space_type 'Space_Type', s.page_size 'Page_Size', s.zip_page_size 'Zip_Size', s.fs_block_size!=0 'BlockSize!=0', s.file_size!=0 'FileSize!=0', s.row_format 'Formats_Permitted', d.path 'Path' 	FROM information_schema.innodb_tablespaces s, information_schema.innodb_datafiles d WHERE s.space = d.space AND d.path NOT LIKE '%/sys/%' 	AND d.path NOT LIKE '%\\\sys\\\%' 	AND s.name NOT LIKE 'mysql/%' 	AND s.name NOT LIKE 'sys/%' 	AND s.name NOT LIKE '%undo%' 	ORDER BY s.name, d.path;
SELECT	s.name 'Space_Name', f.file_type 'File_Type', f.engine 'Engine', f.status 'Status', f.tablespace_name 'Tablespace_Name', f.file_name 'Path' 	FROM information_schema.files f, information_schema.innodb_tablespaces s WHERE f.file_id = s.space AND f.file_name NOT LIKE '%/sys/%' 	AND f.file_name NOT LIKE '%\\\sys\\\%' 	AND s.name NOT LIKE 'mysql' 	AND s.name NOT LIKE 'sys/%' 	AND s.name NOT LIKE 'innodb_temporary' 	AND s.name NOT LIKE '%undo%' 	ORDER BY s.name, f.file_name;
DROP TABLE t1;
SET GLOBAL innodb_file_per_table = ON;
SHOW WARNINGS;
INSERT INTO t1 VALUES(1,'1980-05-31');
INSERT INTO t1 VALUES(2,'2090-05-31');
INSERT INTO t1 VALUES(3,'2012-05-31');
INSERT INTO t1 VALUES(4,'1970-05-31');
INSERT INTO t1 VALUES(5,'1985-05-31');
INSERT INTO t1 VALUES(6,'2006-05-31');
SELECT * FROM t1;
SHOW CREATE TABLE t1;
SELECT t.name 'Table Name', IFNULL(s.name, 'innodb_system') 'Tablespace', t.flag 'Table Flags', t.n_cols 'Columns', t.row_format 'Row Format', t.zip_page_size 'Zip Size', t.space_type 'Space Type' 	FROM information_schema.innodb_tables t LEFT JOIN information_schema.innodb_tablespaces s ON t.space = s.space WHERE t.name not like 'mysql/%' 	AND t.name NOT LIKE 'sys/%' 	ORDER BY t.name;
SELECT s.name 'Space_Name', s.space_type 'Space_Type', s.page_size 'Page_Size', s.zip_page_size 'Zip_Size', s.fs_block_size!=0 'BlockSize!=0', s.file_size!=0 'FileSize!=0', s.row_format 'Formats_Permitted', d.path 'Path' 	FROM information_schema.innodb_tablespaces s, information_schema.innodb_datafiles d WHERE s.space = d.space AND d.path NOT LIKE '%/sys/%' 	AND d.path NOT LIKE '%\\\sys\\\%' 	AND s.name NOT LIKE 'mysql/%' 	AND s.name NOT LIKE 'sys/%' 	AND s.name NOT LIKE '%undo%' 	ORDER BY s.name, d.path;
SELECT	s.name 'Space_Name', f.file_type 'File_Type', f.engine 'Engine', f.status 'Status', f.tablespace_name 'Tablespace_Name', f.file_name 'Path' 	FROM information_schema.files f, information_schema.innodb_tablespaces s WHERE f.file_id = s.space AND f.file_name NOT LIKE '%/sys/%' 	AND f.file_name NOT LIKE '%\\\sys\\\%' 	AND s.name NOT LIKE 'mysql' 	AND s.name NOT LIKE 'sys/%' 	AND s.name NOT LIKE 'innodb_temporary' 	AND s.name NOT LIKE '%undo%' 	ORDER BY s.name, f.file_name;
DROP TABLE t1;
SET GLOBAL innodb_file_per_table = ON;
SHOW WARNINGS;
INSERT INTO t1 VALUES(1,'1980-05-31');
INSERT INTO t1 VALUES(2,'2090-05-31');
INSERT INTO t1 VALUES(3,'2012-05-31');
INSERT INTO t1 VALUES(4,'1970-05-31');
INSERT INTO t1 VALUES(5,'1985-05-31');
INSERT INTO t1 VALUES(6,'2006-05-31');
SELECT * FROM t1;
SHOW CREATE TABLE t1;
SELECT t.name 'Table Name', IFNULL(s.name, 'innodb_system') 'Tablespace', t.flag 'Table Flags', t.n_cols 'Columns', t.row_format 'Row Format', t.zip_page_size 'Zip Size', t.space_type 'Space Type' 	FROM information_schema.innodb_tables t LEFT JOIN information_schema.innodb_tablespaces s ON t.space = s.space WHERE t.name not like 'mysql/%' 	AND t.name NOT LIKE 'sys/%' 	ORDER BY t.name;
SELECT s.name 'Space_Name', s.space_type 'Space_Type', s.page_size 'Page_Size', s.zip_page_size 'Zip_Size', s.fs_block_size!=0 'BlockSize!=0', s.file_size!=0 'FileSize!=0', s.row_format 'Formats_Permitted', d.path 'Path' 	FROM information_schema.innodb_tablespaces s, information_schema.innodb_datafiles d WHERE s.space = d.space AND d.path NOT LIKE '%/sys/%' 	AND d.path NOT LIKE '%\\\sys\\\%' 	AND s.name NOT LIKE 'mysql/%' 	AND s.name NOT LIKE 'sys/%' 	AND s.name NOT LIKE '%undo%' 	ORDER BY s.name, d.path;
SELECT	s.name 'Space_Name', f.file_type 'File_Type', f.engine 'Engine', f.status 'Status', f.tablespace_name 'Tablespace_Name', f.file_name 'Path' 	FROM information_schema.files f, information_schema.innodb_tablespaces s WHERE f.file_id = s.space AND f.file_name NOT LIKE '%/sys/%' 	AND f.file_name NOT LIKE '%\\\sys\\\%' 	AND s.name NOT LIKE 'mysql' 	AND s.name NOT LIKE 'sys/%' 	AND s.name NOT LIKE 'innodb_temporary' 	AND s.name NOT LIKE '%undo%' 	ORDER BY s.name, f.file_name;
DROP TABLE t1;
SHOW CREATE TABLE t1;
DROP TABLE t1;
CREATE TABLE t1 (a int not null, primary key (a)) ENGINE=InnoDB PARTITION BY KEY (a) (PARTITION p0 DATA DIRECTORY '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/alternate_dir/data_part', PARTITION p1);
SHOW CREATE TABLE t1;
SET @@global.innodb_file_per_table = ON;
CREATE TABLE t_file_per_table_on (a int not null auto_increment primary key, b varchar(128)) ENGINE = InnoDB;
SET @@global.innodb_file_per_table = OFF;
CREATE TABLE t_file_per_table_off (a int not null auto_increment primary key, b varchar(128)) ENGINE = InnoDB;
SHOW CREATE TABLE t_file_per_table_on;
SHOW CREATE TABLE t_file_per_table_off;
SET @@global.innodb_file_per_table = ON;
SHOW CREATE TABLE t_file_per_table_on;
SHOW CREATE TABLE t_file_per_table_off;
ALTER TABLE t1 COALESCE PARTITION 1;
SHOW CREATE TABLE t1;
SET @old_sql_quote_show_create=@@sql_quote_show_create;
SET @@sql_quote_show_create=0;
SHOW CREATE TABLE t1;
SET @@sql_quote_show_create=@old_sql_quote_show_create;
SELECT t.name 'Table Name', IFNULL(s.name, 'innodb_system') 'Tablespace', t.flag 'Table Flags', t.n_cols 'Columns', t.row_format 'Row Format', t.zip_page_size 'Zip Size', t.space_type 'Space Type' 	FROM information_schema.innodb_tables t LEFT JOIN information_schema.innodb_tablespaces s ON t.space = s.space WHERE t.name not like 'mysql/%' 	AND t.name NOT LIKE 'sys/%' 	ORDER BY t.name;
SELECT s.name 'Space_Name', s.space_type 'Space_Type', s.page_size 'Page_Size', s.zip_page_size 'Zip_Size', s.fs_block_size!=0 'BlockSize!=0', s.file_size!=0 'FileSize!=0', s.row_format 'Formats_Permitted', d.path 'Path' 	FROM information_schema.innodb_tablespaces s, information_schema.innodb_datafiles d WHERE s.space = d.space AND d.path NOT LIKE '%/sys/%' 	AND d.path NOT LIKE '%\\\sys\\\%' 	AND s.name NOT LIKE 'mysql/%' 	AND s.name NOT LIKE 'sys/%' 	AND s.name NOT LIKE '%undo%' 	ORDER BY s.name, d.path;
SELECT	s.name 'Space_Name', f.file_type 'File_Type', f.engine 'Engine', f.status 'Status', f.tablespace_name 'Tablespace_Name', f.file_name 'Path' 	FROM information_schema.files f, information_schema.innodb_tablespaces s WHERE f.file_id = s.space AND f.file_name NOT LIKE '%/sys/%' 	AND f.file_name NOT LIKE '%\\\sys\\\%' 	AND s.name NOT LIKE 'mysql' 	AND s.name NOT LIKE 'sys/%' 	AND s.name NOT LIKE 'innodb_temporary' 	AND s.name NOT LIKE '%undo%' 	ORDER BY s.name, f.file_name;
DROP TABLE t1;
SET @@global.innodb_file_per_table = ON;
SHOW CREATE TABLE t_file_per_table_on;
SHOW CREATE TABLE t_file_per_table_off;
SET @@global.innodb_file_per_table = OFF;
SHOW CREATE TABLE t_file_per_table_on;
SHOW CREATE TABLE t_file_per_table_off;
DROP TABLE t_file_per_table_on;
DROP TABLE t_file_per_table_off;
SET GLOBAL innodb_file_per_table=1;
SET SESSION innodb_strict_mode=1;
SET @@default_storage_engine=@@default_storage_engine;;
