DROP TABLE IF EXISTS t1;
set @@autocommit=0;
CREATE TABLE t1(s1 INT UNIQUE) ENGINE=innodb;
INSERT INTO t1 VALUES (1);
set @@autocommit=0;
INSERT INTO t1 VALUES (2);
INSERT INTO t1 VALUES (1);
set @@autocommit=0;
DROP TABLE t1;
INSERT INTO t1 VALUES (2);
commit;
set @@autocommit=1;
commit;
set @@autocommit=1;
set @@autocommit=1;
drop table if exists t1;
create table t1 (c1 int primary key, c2 int, c3 int) engine=InnoDB;
insert into t1 values (1,1,0),(2,2,0),(3,3,0),(4,4,0),(5,5,0);
begin;
update t1 set c3=c3+1 where c2=3;
alter table t1 add column c4 int;;
update t1 set c3=c3+1 where c2=4;
commit;
drop table t1;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (a INT) engine=innodb;
INSERT INTO t1 VALUES (1), (2), (3);
START TRANSACTION WITH CONSISTENT SNAPSHOT;
SELECT * FROM t1;
OPTIMIZE TABLE t1;
SELECT * FROM t1;
COMMIT;
DROP TABLE t1;
DROP TABLE IF EXISTS t1, t2;
DROP VIEW IF EXISTS v2;
CREATE TABLE t1 ( f1 INTEGER ) ENGINE = innodb;
CREATE TABLE t2 ( f1 INTEGER );
CREATE VIEW v1 AS SELECT 1 FROM t1;
LOCK TABLE t1 WRITE;
START TRANSACTION;
SELECT * FROM v1;
ALTER VIEW v1 AS SELECT 2 FROM t2;
UNLOCK TABLES;
SELECT * FROM v1;
COMMIT;
DROP TABLE t1, t2;
DROP VIEW v1;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (id INT PRIMARY KEY, value INT) ENGINE = InnoDB;
INSERT INTO t1 VALUES (1, 12345);
START TRANSACTION;
SELECT * FROM t1;
SET lock_wait_timeout=1;
ALTER TABLE t1 ADD INDEX idx(value);
ALTER TABLE t1 ADD INDEX idx(value);
SELECT * FROM t1;
COMMIT;
DROP TABLE t1;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1(a INT, b VARCHAR(250), PRIMARY KEY(a,b)) engine=innodb default charset=utf8;
INSERT INTO t1 VALUES (1, 'a'), (2, 'b');
CREATE INDEX t1ba ON t1(b,a);
DROP TABLE t1;
