TRUNCATE TABLE mysql.slow_log;
SET @old_master_info_repository = @@GLOBAL.master_info_repository;
SET @old_relay_log_info_repository = @@GLOBAL.relay_log_info_repository;
SET @old_log_output=          @@global.log_output;
SET @old_slow_query_log=      @@global.slow_query_log;
SET @old_slow_query_log_file= @@global.slow_query_log_file;
SET @old_long_query_time=     @@global.long_query_time;
SET GLOBAL slow_query_log_file= '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/log/rewrite_slow.log';
SET GLOBAL log_output =       'FILE,TABLE';
SET GLOBAL slow_query_log=    'ON';
SET SESSION long_query_time=  0;
CREATE USER test_user2 IDENTIFIED BY 'azundris2';
SET SESSION long_query_time = 0;
ALTER USER test_user2 IDENTIFIED BY 'azundris2' REPLACE 'azundris2';
SET GLOBAL master_info_repository = 'TABLE';
SET GLOBAL relay_log_info_repository = 'TABLE';
CHANGE REPLICATION SOURCE TO SOURCE_PASSWORD='azundris3', SOURCE_BIND = 'eth4n', SOURCE_TLS_CIPHERSUITES = ''   FOR CHANNEL 'chan_jackie';
CHANGE REPLICATION SOURCE TO SOURCE_PASSWORD='azundris3', SOURCE_CONNECT_RETRY = 1, SOURCE_HEARTBEAT_PERIOD = 1.01, SOURCE_LOG_FILE = 'master_log_name', SOURCE_LOG_POS = 0, SOURCE_SSL = 0, SOURCE_SSL_CA = 'ca_file_name', SOURCE_SSL_CAPATH = 'ca_directory_name', SOURCE_SSL_CERT = 'cert_file_name', SOURCE_SSL_KEY = 'key_file_name', SOURCE_SSL_CIPHER = 'cipher_list', SOURCE_SSL_VERIFY_SERVER_CERT = 1, SOURCE_SSL_CRL = 'crl_file_name', SOURCE_SSL_CRLPATH = 'crl_directory_name', IGNORE_SERVER_IDS = (99,100), SOURCE_TLS_VERSION = 'TLSv1.2', SOURCE_TLS_CIPHERSUITES = NULL, SOURCE_BIND = 'eth4n', SOURCE_RETRY_COUNT = 7, SOURCE_DELAY = 4711, SOURCE_AUTO_POSITION = 0 FOR CHANNEL 'chan_jackie';
RESET SLAVE ALL;
SET GLOBAL master_info_repository = DEFAULT;
SET GLOBAL relay_log_info_repository = DEFAULT;
CREATE USER 'test_user4'@'localhost';
SET SESSION long_query_time=  @old_long_query_time;
SET GLOBAL slow_query_log='OFF';
DROP USER 'test_user4'@'localhost';
DROP USER test_user2;
CREATE TABLE test_log (sql_text TEXT);
LOAD DATA LOCAL INFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/log/rewrite_slow.log'      INTO TABLE test_log FIELDS TERMINATED BY '\n' LINES TERMINATED BY '\n';
SELECT sql_text FROM test_log WHERE sql_text LIKE CONCAT('%azun','dris%');
SELECT sql_text FROM mysql.slow_log WHERE sql_text LIKE CONCAT('%azun','dris%');
SELECT count(*)=1 OR count(*)=2 FROM mysql.slow_log WHERE sql_text LIKE '%REPLACE%';
SELECT count(*)=1 OR count(*)=2 FROM test_log WHERE sql_text LIKE 'CREATE USER %' AND sql_text LIKE '%<secret>%';
SELECT sql_text FROM test_log WHERE sql_text LIKE 'CHANGE REPLICATION SOURCE TO SOURCE_BIND %';
SELECT count(*)=1 OR count(*)=2 FROM mysql.slow_log WHERE sql_text LIKE 'CREATE USER %' AND sql_text LIKE '%<secret>%';
SELECT sql_text FROM test_log WHERE sql_text LIKE 'CHANGE REPLICATION SOURCE TO SOURCE_BIND %';
DROP TABLE test_log;
SET SESSION long_query_time= 0;
SET GLOBAL slow_query_log  = 1;
SET GLOBAL log_output      = 'TABLE';
TRUNCATE mysql.slow_log;
DROP USER u16467055;
SET SESSION long_query_time=    @old_long_query_time;
SET GLOBAL  slow_query_log_file=@old_slow_query_log_file;
SET GLOBAL  slow_query_log=     @old_slow_query_log;
SET GLOBAL  log_output=         @old_log_output;
TRUNCATE TABLE mysql.slow_log;
TRUNCATE TABLE mysql.general_log;
SET GLOBAL  master_info_repository= @old_master_info_repository;
SET GLOBAL  relay_log_info_repository= @old_relay_log_info_repository;
