SET @save_sqlf=@@global.slow_query_log_file;
SET GLOBAL slow_query_log_file= '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/my_extra_slow1.log';
SET timestamp=10;
SET @@global.slow_query_log_file=@save_sqlf;
SET @save_sqlf=@@global.slow_query_log_file;
SET GLOBAL slow_query_log_file= '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/my_extra_slow2.log';
SET GLOBAL long_query_time=0;
DROP TABLE IF EXISTS islow;
CREATE TABLE islow(i INT) ENGINE=innodb;
INSERT INTO islow VALUES (1), (2), (3), (4), (5), (6), (7), (8);
SELECT * FROM islow;
SELECT * FROM islow;
SET GLOBAL slow_query_log=0;
SET GLOBAL long_query_time=1;
DROP TABLE islow;
SET @@global.slow_query_log_file=@save_sqlf;
SET GLOBAL slow_query_log=1;
SET @save_sqlf=@@global.slow_query_log_file;
SET GLOBAL slow_query_log_file= '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/my_extra_slow3.log';
SET long_query_time=0;
CREATE TABLE b(id INT NOT NULL AUTO_INCREMENT);
SET @@global.slow_query_log_file=@save_sqlf;
SET GLOBAL slow_query_log=1;
