SET @save_sqlf=@@global.slow_query_log_file;
SET GLOBAL slow_query_log_file= '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/my_extra_slow2.log';
SET GLOBAL long_query_time=0;
DROP TABLE IF EXISTS islow;
DROP TABLE IF EXISTS mslow;
CREATE TABLE islow(i INT) ENGINE=innodb;
INSERT INTO islow VALUES (1), (2), (3), (4), (5), (6), (7), (8);
CREATE TABLE mslow(i INT) ENGINE=myisam;
INSERT INTO mslow VALUES (1), (2), (3), (4), (5), (6), (7), (8);
SELECT * FROM islow;
SELECT * FROM islow;
SELECT * FROM mslow;
SELECT * FROM mslow;
SET GLOBAL slow_query_log=0;
SET GLOBAL long_query_time=1;
DROP TABLE islow;
DROP TABLE mslow;
SET @@global.slow_query_log_file=@save_sqlf;
SET GLOBAL slow_query_log=1;
