select load_file("/proc/uptime");
SET @old_net_buffer_length = @@global.net_buffer_length;
SET @old_max_allowed_packet= @@global.max_allowed_packet;
SET GLOBAL net_buffer_length = 1024;
SET GLOBAL max_allowed_packet = 1024;
select load_file("/proc/modules");
SET GLOBAL max_allowed_packet = @old_max_allowed_packet;
SET GLOBAL net_buffer_length = @old_net_buffer_length;
select load_file("/proc/self/fd/0");
select load_file("/proc/uptime");
