set @@session.sql_mode='';
drop table if exists t1, t2;
SET SQL_WARNINGS=1;
create table t1 (a int);
create table t1 (a int);
show count(*) errors;
show errors;
show warnings;
create table t2(a int) default charset qwerty;
show count(*) errors;
show errors;
create table t (i);
show count(*) errors;
show errors;
insert into t1 values (1);
insert ignore into t1 values ("hej");
insert ignore into t1 values ("hej"),("då");
set SQL_WARNINGS=1;
insert ignore into t1 values ("hej");
insert ignore into t1 values ("hej"),("då");
drop table t1;
set SQL_WARNINGS=0;
drop temporary table if exists not_exists;
drop table if exists not_exists_table;
show warnings limit 1;
drop database if exists not_exists_db;
show count(*) warnings;
create table t1(id int);
create table if not exists t1(id int);
select @@warning_count;
drop table t1;
create table t1(a tinyint, b int not null, c date, d char(5));
load data infile '../../std_data/warnings_loaddata.dat' into table t1 fields terminated by ',';
select @@warning_count;
drop table t1;
create table t1(a tinyint NOT NULL, b tinyint unsigned, c char(5));
insert ignore into t1 values(NULL,100,'mysql'),(10,-1,'mysql ab'),(500,256,'open source'),(20,NULL,'test');
SET sql_mode = 'NO_ENGINE_SUBSTITUTION';
alter table t1 modify c char(4);
SET sql_mode = default;
alter table t1 add d char(2);
update ignore t1 set a=NULL where a=10;
update ignore t1 set c='mysql ab' where c='test';
update ignore t1 set d=c;
create table t2(a tinyint NOT NULL, b char(3));
insert ignore into t2 select b,c from t1;
insert ignore into t2(b) values('mysqlab');
set sql_warnings=1;
insert ignore into t2(b) values('mysqlab');
set sql_warnings=0;
drop table t1, t2;
create table t1(a char(10));
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
insert into t1 values('mysql ab');
alter table t1 add b char;
set max_error_count=10;
update ignore t1 set b=a;
select @@warning_count;
set max_error_count=0;
show variables like 'max_error_count';
update ignore t1 set b='hi';
select @@warning_count;
show warnings;
set max_error_count=65535;
show variables like 'max_error_count';
set max_error_count=10;
show variables like 'max_error_count';
drop table t1;
create table t1 (a int);
insert into t1 (a) values (1), (2), (3), (4), (5), (6), (7), (8), (9), (10);
update ignore t1 set a='abc';
show warnings limit 2, 1;
show warnings limit 0, 10;
show warnings limit 9, 1;
