SET @old_general_log_state = @@global.general_log;
SET @old_log_output=       @@global.log_output;
SET @old_slow_query_log=   @@global.slow_query_log;
SET @old_general_log=      @@global.general_log;
SET @old_long_query_time=  @@session.long_query_time;
SET GLOBAL log_output="FILE,TABLE";
use mysql;
SET @saved_long_query_time = @@long_query_time;
SET @saved_log_output = @@log_output;
SET @saved_general_log = @@GLOBAL.general_log;
SET @saved_slow_query_log = @@GLOBAL.slow_query_log;
SELECT @saved_long_query_time, @saved_log_output, @saved_general_log, @saved_slow_query_log;
truncate table general_log;
select * from general_log;
truncate table slow_log;
select * from slow_log;
truncate table general_log;
select * from general_log where argument like '%general_log%';
create table join_test (verbose_comment varchar (80), command_type varchar(64));
insert into join_test values ("User performed a usual SQL query", "Query");
insert into join_test values ("New DB connection was registered", "Connect");
insert into join_test values ("Get the table info", "Field List");
select verbose_comment, user_host, argument from  mysql.general_log join join_test on (mysql.general_log.command_type = join_test.command_type);
drop table join_test;
flush logs;
lock tables mysql.general_log WRITE;
lock tables mysql.slow_log WRITE;
lock tables mysql.general_log READ;
lock tables mysql.slow_log READ;
lock tables mysql.slow_log READ LOCAL, mysql.general_log READ LOCAL;
show create table mysql.general_log;
show fields from mysql.general_log;
show create table mysql.slow_log;
show fields from mysql.slow_log;
flush logs;
flush tables;
SET GLOBAL GENERAL_LOG=ON;
SET GLOBAL SLOW_QUERY_LOG=ON;
show open tables;
flush logs;
show open tables like 'general%';
flush tables;
show open tables;
SET GLOBAL GENERAL_LOG=OFF;
SET GLOBAL SLOW_QUERY_LOG=OFF;
flush tables;
show open tables;
SET GLOBAL GENERAL_LOG=ON;
SET GLOBAL SLOW_QUERY_LOG=ON;
truncate table mysql.general_log;
set names binary;
select _koi8r'����' as test;
select * from mysql.general_log;
set names utf8;
truncate table mysql.general_log;
set names utf8;
create table bug16905 (s char(15) character set utf8 default 'пусто');
insert into bug16905 values ('новое');
select * from mysql.general_log;
drop table bug16905;
truncate table mysql.slow_log;
set session long_query_time=1;
select * from mysql.slow_log;
set @@session.long_query_time = @saved_long_query_time;
flush tables with read lock;
unlock tables;
use mysql;
lock tables general_log read local, help_category read local;
unlock tables;
SET SESSION long_query_time = 1000;
drop table if exists mysql.renamed_general_log;
drop table if exists mysql.renamed_slow_log;
drop table if exists mysql.general_log_new;
drop table if exists mysql.slow_log_new;
use mysql;
RENAME TABLE general_log TO renamed_general_log;
RENAME TABLE slow_log TO renamed_slow_log;
truncate table general_log;
select * from general_log;
truncate table slow_log;
select * from slow_log;
create table general_log_new like general_log;
rename table general_log TO renamed_general_log, general_log_new TO general_log;
create table slow_log_new like slow_log;
rename table slow_log TO renamed_slow_log, slow_log_new TO slow_log;
rename table general_log TO general_log_new, renamed_general_log TO general_log, slow_log to renamed_slow_log;
select * from general_log;
select * from renamed_general_log;
select * from slow_log;
select * from renamed_slow_log;
set global general_log='OFF';
RENAME TABLE general_log TO general_log2;
set global slow_query_log='OFF';
RENAME TABLE slow_log TO slow_log2;
set global general_log='ON';
set global slow_query_log='ON';
RENAME TABLE general_log2 TO general_log;
RENAME TABLE slow_log2 TO slow_log;
SET SESSION long_query_time = @saved_long_query_time;
set global general_log='ON';
set global slow_query_log='ON';
flush logs;
flush logs;
drop table renamed_general_log, renamed_slow_log;
use test;
use mysql;
repair table general_log;
repair table slow_log;
create table general_log_new like general_log;
create table slow_log_new like slow_log;
show tables where Tables_in_mysql like '%log%' and Tables_in_mysql != 'ndb_binlog_index';
drop table slow_log_new, general_log_new;
use test;
drop procedure if exists proc25422_truncate_slow;
drop procedure if exists proc25422_truncate_general;
drop procedure if exists proc25422_alter_slow;
drop procedure if exists proc25422_alter_general;
use test;
create procedure proc25422_truncate_slow (loops int) begin declare v1 int default 0; declare continue handler for sqlexception /* errors from truncate */ begin end; while v1 < loops do truncate mysql.slow_log; set v1 = v1 + 1; end while; end;
create procedure proc25422_truncate_general (loops int) begin declare v1 int default 0; declare continue handler for sqlexception /* errors from truncate */ begin end; while v1 < loops do truncate mysql.general_log; set v1 = v1 + 1; end while; end;
create procedure proc25422_alter_slow (loops int) begin declare v1 int default 0; declare ER_BAD_LOG_STATEMENT condition for 1575; declare continue handler for ER_BAD_LOG_STATEMENT begin end; while v1 < loops do set @old_log_state = @@global.slow_query_log; set global slow_query_log = 'OFF'; alter table mysql.slow_log engine = CSV; set global slow_query_log = @old_log_state; set v1 = v1 + 1; end while; end;
