CREATE TABLE system_tables (ID INT PRIMARY KEY AUTO_INCREMENT, table_name VARCHAR(100));
INSERT INTO system_tables(table_name) SELECT concat(table_schema, ".", table_name) FROM INFORMATION_SCHEMA.tables WHERE table_schema = 'mysql' AND table_name NOT IN('general_log', 'slow_log', 'ndb_binlog_index') ORDER BY table_name;
CALL test_system_table_alter_engine();
DROP PROCEDURE test_system_table_alter_engine;
CREATE PROCEDURE execute_stmt(stmt VARCHAR(255)) BEGIN SET @error_no = 0; SET @sql_stmt = stmt; PREPARE stmt FROM @sql_stmt; EXECUTE stmt; GET DIAGNOSTICS CONDITION 1 @error_no = MYSQL_ERRNO, @error_message = MESSAGE_TEXT; IF @error_no > 0 THEN SELECT "Warning" AS SEVERITY, @error_no as ERRNO, @error_message as MESSAGE; END IF; DEALLOCATE PREPARE stmt; END;
CALL test_create_system_table();
DROP PROCEDURE test_create_system_table;
DROP PROCEDURE execute_stmt;
DROP TABLE system_tables;
CREATE USER 'user1'@'%';
CREATE TABLE t1 (f1 INT);
CREATE FUNCTION sequence RETURNS INTEGER SONAME "udf_example.so";
RENAME TABLE mysql.func TO mysql.func_bkp;
CREATE TABLE mysql.func ENGINE='MyISAM' AS SELECT * FROM mysql.func_bkp;
CREATE FUNCTION udf_func RETURNS STRING SONAME 'udf_func.so';
DROP FUNCTION sequence;
ALTER TABLE mysql.func ENGINE='InnoDB', DROP COLUMN ret;
CREATE FUNCTION udf_func RETURNS STRING SONAME 'udf_func.so';
DROP FUNCTION sequence;
DROP TABLE mysql.func;
RENAME TABLE mysql.func_bkp TO mysql.func;
DROP FUNCTION sequence;
RENAME TABLE mysql.plugin TO mysql.plugin_bkp;
CREATE TABLE mysql.plugin ENGINE='MyISAM' AS SELECT * FROM mysql.plugin_bkp;
INSTALL PLUGIN my_plug soname 'some_plugin.so';
UNINSTALL PLUGIN my_plug;
ALTER TABLE mysql.plugin ENGINE=InnoDB, MODIFY dl CHAR(64);
INSTALL PLUGIN my_plug soname 'some_plugin.so';
UNINSTALL PLUGIN my_plug;
DROP TABLE mysql.plugin;
RENAME TABLE mysql.plugin_bkp TO mysql.plugin;
RENAME TABLE mysql.servers TO mysql.servers_bkp;
CREATE TABLE mysql.servers ENGINE='MyISAM' AS SELECT * FROM mysql.servers_bkp;
CREATE SERVER fedlnk FOREIGN DATA WRAPPER mysql OPTIONS (USER 'fed_user', HOST 'remote_host', PORT 9306, DATABASE 'federated');
DROP SERVER fedlnk;
ALTER SERVER fedlnk OPTIONS (USER 'sally');
ALTER TABLE mysql.servers ENGINE='InnoDB', MODIFY WRAPPER varchar(128);
CREATE SERVER fedlnk FOREIGN DATA WRAPPER mysql OPTIONS (USER 'fed_user', HOST 'remote_host', PORT 9306, DATABASE 'federated');
DROP SERVER fedlnk;
ALTER SERVER fedlnk OPTIONS (USER 'sally');
DROP TABLE mysql.servers;
RENAME TABLE mysql.servers_bkp TO mysql.servers;
CREATE USER 'user2'@'%';
DROP USER 'user1'@'%';
ALTER USER 'user1'@'%' PASSWORD EXPIRE;
GRANT SELECT ON t1 TO 'user1'@'%';
REVOKE SELECT ON t1 FROM 'user1'@'%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'user1'@'%';
RENAME USER 'user1'@'%' TO 'user1'@'%';
CREATE USER 'user2'@'%';
DROP USER 'user1'@'%';
ALTER USER 'user1'@'%' PASSWORD EXPIRE;
GRANT SELECT ON t1 TO 'user1'@'%';
REVOKE SELECT ON t1 FROM 'user1'@'%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'user1'@'%';
RENAME USER 'user1'@'%' TO 'user1'@'%';
GRANT SELECT(f1) ON t1 TO 'user1'@'%';
REVOKE SELECT ON t1.f1 FROM 'user1'@'%';
GRANT SELECT(f1) ON t1 TO 'user1'@'%';
REVOKE SELECT ON t1.f1 FROM 'user1'@'%';
GRANT SELECT ON t1 TO 'user1'@'%';
REVOKE SELECT ON t1 FROM 'user1'@'%';
GRANT SELECT ON t1 TO 'user1'@'%';
REVOKE SELECT ON t1 FROM 'user1'@'%';
CREATE FUNCTION f1() RETURNS INT return 1;
GRANT EXECUTE ON FUNCTION f1 TO 'user1'@'%';
REVOKE EXECUTE ON FUNCTION f1 FROM 'user1'@'%';
GRANT EXECUTE ON FUNCTION f1 TO 'user1'@'%';
REVOKE EXECUTE ON FUNCTION f1 FROM 'user1'@'%';
GRANT PROXY ON 'user1'@'%' TO 'user2'@'%';
REVOKE PROXY ON 'user1'@'%' FROM 'user2'@'%';
GRANT PROXY ON 'user1'@'%' TO 'user2'@'%';
REVOKE PROXY ON 'user1'@'%' FROM 'user2'@'%';
RENAME TABLE mysql.component TO mysql.component_bkp;
CREATE TABLE mysql.component ENGINE='MyISAM' AS SELECT * FROM mysql.component_bkp;
INSTALL COMPONENT "file://component_log_sink_json";
UNINSTALL COMPONENT "file://component_log_sink_json";
ALTER TABLE mysql.component ENGINE='InnoDB', DROP COLUMN component_urn;
INSTALL COMPONENT "file://component_log_sink_json";
UNINSTALL COMPONENT "file://component_log_sink_json";
DROP TABLE mysql.component;
RENAME TABLE mysql.component_bkp TO mysql.component;
GRANT ALL ON db.* TO 'user1'@'%';
GRANT ALL ON db.* TO 'user1'@'%';
