create user test_nopw;
grant select on test.* to test_nopw;
create user test_newpw identified by "newpw";
grant select on test.* to test_newpw;
select user(), current_user(), database();
select concat('<', user(), '>'), concat('<', current_user(), '>'), database();
select concat('<', user(), '>'), concat('<', current_user(), '>'), database();
select concat('<', user(), '>'), concat('<', current_user(), '>'), database();
select concat('<', user(), '>'), concat('<', current_user(), '>'), database();
select concat('<', user(), '>'), concat('<', current_user(), '>'), database();
select concat('<', user(), '>'), concat('<', current_user(), '>'), database();
select concat('<', user(), '>'), concat('<', current_user(), '>'), database();
drop user test_nopw;
drop user test_newpw;
SELECT @@session.sql_big_selects;
SELECT @@global.max_join_size;
SELECT @@session.sql_big_selects;
SELECT @@global.max_join_size;
SET @@global.max_join_size = 10000;
SET @@session.max_join_size = default;
SELECT @@session.sql_big_selects;
SET @@global.max_join_size = 18446744073709551615;
SET @@session.max_join_size = default;
SELECT @@session.sql_big_selects;
SET INSERT_ID=12;
SELECT @@INSERT_ID;
SET TIMESTAMP=200;
SELECT @@TIMESTAMP;
SELECT @@INSERT_ID;
SELECT @@TIMESTAMP=200;
SELECT IS_FREE_LOCK('bug31418');
SELECT IS_USED_LOCK('bug31418');
SELECT GET_LOCK('bug31418', 1);
SELECT IS_USED_LOCK('bug31418') = CONNECTION_ID();
SELECT IS_FREE_LOCK('bug31418');
SELECT IS_USED_LOCK('bug31418');
FLUSH STATUS;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
