SET PERSIST server_id=47, @@persist.general_log=0;
SET PERSIST concurrent_insert=NEVER;
INSTALL COMPONENT "file://component_validate_password";
SELECT @@global.validate_password.policy, @@global.validate_password.length;
SET PERSIST validate_password.policy= 2;
SET PERSIST validate_password.length= 13;
SELECT @@global.server_id;
SELECT @@global.general_log;
SELECT @@global.concurrent_insert;
SELECT @@global.validate_password.policy;
SELECT @@global.validate_password.length;
UNINSTALL COMPONENT "file://component_validate_password";
INSTALL COMPONENT "file://component_validate_password";
SELECT * FROM performance_schema.persisted_variables;
SET PERSIST validate_password.policy= 2;
SELECT * FROM performance_schema.persisted_variables;
SET PERSIST validate_password.length= 13;
SELECT * FROM performance_schema.persisted_variables;
RESET PERSIST `validate_password.length`;
SELECT * FROM performance_schema.persisted_variables;
UNINSTALL COMPONENT "file://component_validate_password";
SELECT * FROM performance_schema.persisted_variables;
RESET PERSIST;
SELECT * FROM performance_schema.persisted_variables;
INSTALL COMPONENT 'file://component_validate_password';
SET @@persist.validate_password.length=10;
SET @@persist.validate_password.check_user_name=OFF;
SELECT COUNT(*) FROM performance_schema.persisted_variables;
UNINSTALL COMPONENT 'file://component_validate_password';
INSTALL COMPONENT 'file://component_validate_password';
SELECT COUNT(*) FROM performance_schema.error_log WHERE ERROR_CODE = "MY-013185";
UNINSTALL COMPONENT 'file://component_validate_password';
RESET PERSIST;
SELECT * FROM performance_schema.persisted_variables;
