SET sql_mode = 'NO_ENGINE_SUBSTITUTION';
DROP TABLE IF EXISTS t1;
SELECT table_comment,char_length(table_comment) FROM information_schema.tables WHERE table_name='t1';
SELECT column_comment,char_length(column_comment) FROM information_schema.columns WHERE table_name='t1' ORDER BY column_comment;
SELECT comment,index_comment,char_length(index_comment) FROM information_schema.statistics WHERE table_name='t1' ORDER BY index_comment;
SHOW CREATE TABLE t1;
SELECT table_comment,char_length(table_comment) FROM information_schema.tables WHERE table_name='t1';
SELECT column_comment,char_length(column_comment) FROM information_schema.columns WHERE table_name='t1' ORDER BY column_comment;
SELECT comment,index_comment,char_length(index_comment) FROM information_schema.statistics WHERE table_name='t1' ORDER BY index_comment;
SHOW CREATE TABLE t1;
SELECT table_comment,char_length(table_comment) FROM information_schema.tables WHERE table_name='t1';
SELECT column_comment,char_length(column_comment) FROM information_schema.columns WHERE table_name='t1' ORDER BY column_comment;
SELECT comment,index_comment,char_length(index_comment) FROM information_schema.statistics WHERE table_name='t1' ORDER BY index_comment;
SHOW CREATE TABLE t1;
DROP INDEX i1 ON t1;
ALTER TABLE t1 DROP INDEX i2, DROP INDEX i4;
SELECT table_comment,char_length(table_comment) FROM information_schema.tables WHERE table_name='t1';
SELECT column_comment,char_length(column_comment) FROM information_schema.columns WHERE table_name='t1' ORDER BY column_comment;
SELECT comment,index_comment,char_length(index_comment) FROM information_schema.statistics WHERE table_name='t1' ORDER BY index_comment;
SHOW CREATE TABLE t1;
SELECT table_comment,char_length(table_comment) FROM information_schema.tables WHERE table_name='t1';
SELECT column_comment,char_length(column_comment) FROM information_schema.columns WHERE table_name='t1' ORDER BY column_comment;
SELECT comment,index_comment,char_length(index_comment) FROM information_schema.statistics WHERE table_name='t1' ORDER BY index_comment;
SHOW CREATE TABLE t1;
SELECT table_comment,char_length(table_comment) FROM information_schema.tables WHERE table_name='t1';
SELECT column_comment,char_length(column_comment) FROM information_schema.columns WHERE table_name='t1' ORDER BY column_comment;
SELECT comment,index_comment,char_length(index_comment) FROM information_schema.statistics WHERE table_name='t1' ORDER BY index_comment;
SHOW CREATE TABLE t1;
SELECT table_comment,char_length(table_comment) FROM information_schema.tables WHERE table_name='t1';
SELECT column_comment,char_length(column_comment) FROM information_schema.columns WHERE table_name='t1' ORDER BY column_comment;
SELECT comment,index_comment,char_length(index_comment) FROM information_schema.statistics WHERE table_name='t1' ORDER BY index_comment;
SHOW CREATE TABLE t1;
SELECT table_comment,char_length(table_comment) FROM information_schema.tables WHERE table_name='t1';
SELECT column_comment,char_length(column_comment) FROM information_schema.columns WHERE table_name='t1' ORDER BY column_comment;
SELECT comment,index_comment,char_length(index_comment) FROM information_schema.statistics WHERE table_name='t1' ORDER BY index_comment;
SHOW CREATE TABLE t1;
set sql_mode='TRADITIONAL';
SELECT table_comment,char_length(table_comment) FROM information_schema.tables WHERE table_name='t1';
SELECT column_comment,char_length(column_comment) FROM information_schema.columns WHERE table_name='t1' ORDER BY column_comment;
SELECT comment,index_comment,char_length(index_comment) FROM information_schema.statistics WHERE table_name='t1' ORDER BY index_comment;
SHOW CREATE TABLE t1;
set sql_mode='TRADITIONAL';
SELECT table_comment,char_length(table_comment) FROM information_schema.tables WHERE table_name='t1';
SELECT column_comment,char_length(column_comment) FROM information_schema.columns WHERE table_name='t1' ORDER BY column_comment;
SELECT comment,index_comment,char_length(index_comment) FROM information_schema.statistics WHERE table_name='t1' ORDER BY index_comment;
SHOW CREATE TABLE t1;
drop table t1;
SET sql_mode = default;
