SET PERSIST server_id=47, @@persist.general_log=0;
SET PERSIST concurrent_insert=NEVER;
INSTALL PLUGIN validate_password SONAME 'validate_password.so';
SELECT @@global.validate_password_policy, @@global.validate_password_length;
SET PERSIST validate_password_policy= 2;
SET PERSIST validate_password_length= 13;
SELECT @@global.server_id;
SELECT @@global.general_log;
SELECT @@global.concurrent_insert;
SELECT @@global.validate_password_policy;
SELECT @@global.validate_password_length;
UNINSTALL PLUGIN validate_password;
INSTALL PLUGIN validate_password SONAME 'validate_password.so';
SELECT * FROM performance_schema.persisted_variables ORDER BY 1;
SET PERSIST validate_password_policy= 2;
SELECT * FROM performance_schema.persisted_variables ORDER BY 1;
SET PERSIST validate_password_length= 13;
SELECT * FROM performance_schema.persisted_variables ORDER BY 1;
RESET PERSIST validate_password_length;
SELECT * FROM performance_schema.persisted_variables ORDER BY 1;
UNINSTALL PLUGIN validate_password;
SELECT * FROM performance_schema.persisted_variables ORDER BY 1;
RESET PERSIST;
SELECT * FROM performance_schema.persisted_variables ORDER BY 1;
INSTALL PLUGIN validate_password SONAME 'validate_password.so';
SET @@persist.validate_password_length= 15;
UNINSTALL PLUGIN validate_password;
INSTALL PLUGIN validate_password SONAME 'validate_password.so';
SELECT @@GLOBAL.validate_password_length;
SET PERSIST validate_password_length= 9;
SELECT @@GLOBAL.validate_password_length;
RESET PERSIST validate_password_length;
UNINSTALL PLUGIN validate_password;
SELECT @@GLOBAL.validate_password_length;
INSTALL PLUGIN validate_password SONAME 'validate_password.so';
SELECT @@GLOBAL.validate_password_length;
SET @@persist.validate_password_length= 11;
UNINSTALL PLUGIN validate_password;
INSTALL PLUGIN validate_password SONAME 'validate_password.so';
SELECT @@GLOBAL.validate_password_length;
SET PERSIST validate_password_length= 19;
SELECT @@GLOBAL.validate_password_length;
RESET PERSIST;
UNINSTALL PLUGIN validate_password;
SELECT @@GLOBAL.validate_password_length;
INSTALL PLUGIN validate_password SONAME 'validate_password.so';
SELECT @@GLOBAL.validate_password_length;
RESET PERSIST;
UNINSTALL plugin validate_password;
