CREATE USER 'base_user'@'localhost' IDENTIFIED BY 'pass', 'user1'@'localhost' IDENTIFIED BY 'pass';
GRANT ALL ON mysql.* TO 'user1'@'localhost';
INSTALL PLUGIN validate_password SONAME 'validate_password.so';
SET @@global.validate_password_policy=LOW;
CREATE USER 'user'@'localhost' IDENTIFIED BY '';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'aweg';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password3';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'passwor';
SET @@global.validate_password_length= 12;
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'afrgtyhlp98';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'iuyt567nbvfA';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1234';
SET @@global.validate_password_mixed_case_count= 0;
SET @@global.validate_password_number_count= 0;
SET @@global.validate_password_special_char_count= 0;
SET @@global.validate_password_length= 0;
ALTER USER 'base_user'@'localhost' IDENTIFIED BY '';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'p';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password';
SET @@global.validate_password_length= -2;
SET @@global.validate_password_length= 3.5;
SET @@global.validate_password_length= 2147483647;
SET @@global.validate_password_length= 2147483648;
SET @a = REPEAT('a',2147483647);
EXECUTE stmt1 USING @a,@b;
DEALLOCATE PREPARE stmt1;
SET @@global.validate_password_length= 4294967295;
SET @@global.validate_password_length= 8;
SET @a = REPEAT('a',1048576);
EXECUTE stmt1 USING @a,@b;
DEALLOCATE PREPARE stmt1;
SET @@global.validate_password_mixed_case_count= 1;
SET @@global.validate_password_number_count= 1;
SET @@global.validate_password_special_char_count= 1;
SET @@global.validate_password_policy=MEDIUM;
SET @@global.validate_password_number_count= 0;
CREATE USER 'user'@'localhost' IDENTIFIED BY 'aedfoiASE$%';
ALTER USER 'user'@'localhost' IDENTIFIED BY 'foiuiuytd78';
ALTER USER 'user'@'localhost' IDENTIFIED BY 'pasretryFRGH&^98';
SET @@global.validate_password_mixed_case_count= 0;
CREATE USER 'user'@'localhost' IDENTIFIED BY 'aedSWEhjui';
ALTER USER 'user'@'localhost' IDENTIFIED BY 'gruyuHOIU&*(';
ALTER USER 'user'@'localhost' IDENTIFIED BY 'passwor0987**&';
SET @@global.validate_password_special_char_count= 0;
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'piufgklol';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1A#';
SET @@global.validate_password_special_char_count= 1;
SET @@global.validate_password_number_count= 1;
SET @@global.validate_password_mixed_case_count= 1;
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'erftuiik';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1A#';
SET @@global.validate_password_number_count= 2;
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1A#';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password12A#';
SET @@global.validate_password_number_count= 1;
SET @@global.validate_password_mixed_case_count= 2;
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1A#';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1AB#';
SET @@global.validate_password_mixed_case_count= 1;
SET @@global.validate_password_special_char_count= 2;
SET @@global.validate_password_special_char_count= 1;
SET @@global.validate_password_policy=STRONG;
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1A#';
SET @@global.validate_password_dictionary_file="/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/share//dictionary.txt";
SET @@global.validate_password_policy=STRONG;
CREATE USER 'user'@'localhost' IDENTIFIED BY 'password';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1A#';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'pass12345A#';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'pass0000A#';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'PA00wrd!#';
SELECT VALIDATE_PASSWORD_STRENGTH('password', 0);
SELECT VALIDATE_PASSWORD_STRENGTH();
SELECT VALIDATE_PASSWORD_STRENGTH('');
SELECT VALIDATE_PASSWORD_STRENGTH('pass');
SELECT VALIDATE_PASSWORD_STRENGTH('password');
SELECT VALIDATE_PASSWORD_STRENGTH('password0000');
SELECT VALIDATE_PASSWORD_STRENGTH('password1A#');
SELECT VALIDATE_PASSWORD_STRENGTH('PA12wrd!#');
SELECT VALIDATE_PASSWORD_STRENGTH('PA00wrd!#');
SET NAMES 'ujis';
SELECT VALIDATE_PASSWORD_STRENGTH('PA12wrd!#');
SET @@global.validate_password_policy=MEDIUM;
SET @@global.validate_password_policy=LOW;
SET @@global.validate_password_length= 4;
SET @@global.validate_password_special_char_count= 0;
SET @@global.validate_password_mixed_case_count= 0;
CREATE USER 'user2'@'localhost' IDENTIFIED BY 'password';
CREATE USER 'user2'@'localhost' IDENTIFIED BY 'PA00wrd!#';
ALTER USER 'user2'@'localhost' IDENTIFIED BY 'password';
ALTER USER 'user2'@'localhost' IDENTIFIED BY 'PA00wrd!#';
DROP USER 'user2'@'localhost';
DROP USER 'base_user'@'localhost';
DROP USER 'user1'@'localhost';
DROP USER 'user'@'localhost';
SET @@global.validate_password_length=default;
SET @@global.validate_password_number_count=default;
SET @@global.validate_password_mixed_case_count=default;
SET @@global.validate_password_special_char_count=default;
SET @@global.validate_password_policy=default;
SET @@global.validate_password_dictionary_file=default;
SELECT @@validate_password_length, @@validate_password_number_count, @@validate_password_mixed_case_count, @@validate_password_special_char_count, @@validate_password_policy, @@validate_password_dictionary_file;
SET @@global.validate_password_policy=STRONG;
CREATE USER 'user1'@'localhost' IDENTIFIED BY 'passWORD123#';
SET @@global.validate_password_dictionary_file="/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/dictionary2.txt";
SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'validate_password_dictionary_file_words_count';
SELECT VARIABLE_VALUE into @ts1 FROM performance_schema.global_status WHERE VARIABLE_NAME = "validate_password_dictionary_file_last_parsed";
SELECT @ts1;
SELECT LENGTH(@ts1);
SET @@global.validate_password_dictionary_file="/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/dictionary.txt";
SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'validate_password_dictionary_file_words_count';
SELECT VARIABLE_VALUE into @ts2 FROM performance_schema.global_status WHERE VARIABLE_NAME = "validate_password_dictionary_file_last_parsed";
SELECT @ts1 <> @ts2;
CREATE USER 'user2'@'localhost' IDENTIFIED BY 'passWORD123#';
SET @@global.validate_password_dictionary_file=NULL;
CREATE USER 'user2'@'localhost' IDENTIFIED BY 'passWORD123#';
