DROP TABLE IF EXISTS t1, t2;
CREATE TABLE t1 (a int) ENGINE = CSV;
CREATE TABLE t1 (a int NOT NULL) ENGINE = CSV;
CREATE TABLE t2 (a int NOT NULL, b char(20)) ENGINE = CSV;
DROP TABLE t1;
DROP TABLE IF EXISTS t1;
SET sql_mode = 'NO_ENGINE_SUBSTITUTION';
CREATE TABLE t1 (a int NOT NULL, b blob NOT NULL, c CHAR(20) NOT NULL,  d VARCHAR(20) NOT NULL, e enum('foo','bar') NOT NULL,f DATE NOT NULL)  ENGINE = CSV;
INSERT INTO t1 VALUES();
SELECT * FROM t1;
INSERT INTO t1 VALUES(default,default,default,default,default,default);
SELECT * FROM t1;
INSERT INTO t1 VALUES(0,'abc','def','ghi','bar','1999-12-31');
SELECT * FROM t1;
INSERT INTO t1 VALUES(NULL,'ab','a','b','foo','2007-01-01');
INSERT INTO t1 VALUES(default(a),default(b), default(c), default(d), default(e), default(f));
DROP TABLE t1;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (a int NOT NULL, b char(10) NOT NULL) ENGINE = CSV;
INSERT INTO t1 VALUES();
SELECT * FROM t1;
UPDATE t1 set b = 'new_value' where a = 0;
SELECT * FROM t1;
UPDATE t1 set b = NULL where b = 'new_value';
SELECT * FROM t1;
DROP TABLE t1;
SET sql_mode = default;
