create function version_tokens_show returns string soname 'version_token.so';
SELECT version_tokens_show();
INSTALL PLUGIN version_tokens SONAME 'version_token.so';
UNINSTALL PLUGIN version_tokens;
INSTALL PLUGIN version_tokens SONAME 'version_token.so';
UNINSTALL PLUGIN version_tokens;
drop function version_tokens_show;
INSTALL PLUGIN version_tokens SONAME 'version_token.so';
create function version_tokens_set returns string soname 'version_token.so';
create function version_tokens_show returns string soname 'version_token.so';
create function version_tokens_edit returns string soname 'version_token.so';
create function version_tokens_delete returns string soname 'version_token.so';
create function version_tokens_lock_shared returns int soname 'version_token.so';
create function version_tokens_lock_exclusive returns int soname 'version_token.so';
create function version_tokens_unlock returns int soname 'version_token.so';
select version_tokens_set("token1    =     abc;token2=       def",123);
select version_tokens_edit("token1= 123;         token3     =         asdf",123);
select version_tokens_show("123");
select version_tokens_set(123);
select version_tokens_edit(123);
select version_tokens_delete(123);
select version_tokens_lock_shared("Less arguments");
select version_tokens_lock_shared(1,"Wrong argument type");
select version_tokens_lock_exclusive("Less arguments");
select version_tokens_lock_exclusive(1,"Wrong argument type");
select version_tokens_unlock("Takes no arguments");
select version_tokens_lock_shared("gizmo", -1);
select version_tokens_lock_exclusive("gizmo", -1);
select version_tokens_set("token1    =     abc;token2=       def");
select version_tokens_show();
select version_tokens_set("");
select version_tokens_show();
select version_tokens_set("token1    =     abc;token2=       def");
select version_tokens_show();
select version_tokens_show();
do version_tokens_set("token1    =     def;;;;      ;invalid_token; token2= abc;;");
select version_tokens_show();
select version_tokens_show();
select version_tokens_show();
select version_tokens_show();
select version_tokens_delete("invalid=token");
select version_tokens_show();
select version_tokens_show();
select version_tokens_delete("*");
select version_tokens_show();
select version_tokens_show();
select version_tokens_set("token1    =     abc;token2=       def");
select version_tokens_show();
set @@version_tokens_session= "token1=def";
select 1;
select 1;
set @@version_tokens_session= "token3=abc";
select 1;
select @@version_tokens_session;
set @@version_tokens_session= "token111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111=abc;;";
select @@version_tokens_session;
set @@version_tokens_session= NULL;
set @@version_tokens_session= "token1=def;;;;;;;;";
use test;
create table t1 (c1 int);
drop table t1;
create table t1 (c1 int);
set @@version_tokens_session= "token100=def;;;      token2  =   abc    ;;;;;";
create table t1 (c1 int);
select 1;
set @@version_tokens_session= "a=aa";
SELECT version_tokens_lock_exclusive("b",20);
SELECT version_tokens_lock_exclusive("a",20);
SELECT version_tokens_unlock();
UNINSTALL PLUGIN version_tokens;
select version_tokens_set("token1    =     abc;token2=       def");
select version_tokens_show();
SHOW PRIVILEGES;
drop function version_tokens_set;
drop function version_tokens_show;
drop function version_tokens_edit;
drop function version_tokens_delete;
drop function version_tokens_lock_shared;
drop function version_tokens_lock_exclusive;
drop function version_tokens_unlock;
