TRUNCATE TABLE performance_schema.memory_summary_global_by_event_name;
CREATE SCHEMA dd_pfs;
CREATE TABLE dd_pfs.mem_events (Seq int auto_increment PRIMARY KEY, Query varchar(1000)) AS SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
DELETE FROM dd_pfs.mem_events WHERE Query = 'savepoint';
INSERT INTO dd_pfs.mem_events (Name, N_alloc, N_free, N_curr, Sz_alloc, Sz_free, Sz_curr, Query) SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
create schema s;
create table s.t1(i int);
create table s.t2(i int) tablespace innodb_system;
drop schema s;
DELETE FROM dd_pfs.mem_events WHERE Query = 'savepoint';
INSERT INTO dd_pfs.mem_events (Name, N_alloc, N_free, N_curr, Sz_alloc, Sz_free, Sz_curr, Query) SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
CREATE SCHEMA s;
SET @diff = (SELECT COUNT_ALLOC - N_alloc FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT COUNT_FREE - N_free FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT CURRENT_COUNT_USED - N_curr FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
DELETE FROM dd_pfs.mem_events WHERE Query = 'savepoint';
INSERT INTO dd_pfs.mem_events (Name, N_alloc, N_free, N_curr, Sz_alloc, Sz_free, Sz_curr, Query) SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
CREATE TABLE s.t_myisam(i int) engine myisam;
SET @diff = (SELECT COUNT_ALLOC - N_alloc FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT COUNT_FREE - N_free FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT CURRENT_COUNT_USED - N_curr FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
DELETE FROM dd_pfs.mem_events WHERE Query = 'savepoint';
INSERT INTO dd_pfs.mem_events (Name, N_alloc, N_free, N_curr, Sz_alloc, Sz_free, Sz_curr, Query) SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
CREATE TABLE s.t_innodb_1(i int) TABLESPACE innodb_system;
SET @diff = (SELECT COUNT_ALLOC - N_alloc FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT COUNT_FREE - N_free FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT CURRENT_COUNT_USED - N_curr FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
DELETE FROM dd_pfs.mem_events WHERE Query = 'savepoint';
INSERT INTO dd_pfs.mem_events (Name, N_alloc, N_free, N_curr, Sz_alloc, Sz_free, Sz_curr, Query) SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
CREATE TABLE s.t_innodb_2(i int) TABLESPACE innodb_system;
SET @diff = (SELECT COUNT_ALLOC - N_alloc FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT COUNT_FREE - N_free FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT CURRENT_COUNT_USED - N_curr FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
DELETE FROM dd_pfs.mem_events WHERE Query = 'savepoint';
INSERT INTO dd_pfs.mem_events (Name, N_alloc, N_free, N_curr, Sz_alloc, Sz_free, Sz_curr, Query) SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
SELECT * FROM s.t_myisam;
SET @diff = (SELECT COUNT_ALLOC - N_alloc FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT COUNT_FREE - N_free FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT CURRENT_COUNT_USED - N_curr FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
DELETE FROM dd_pfs.mem_events WHERE Query = 'savepoint';
INSERT INTO dd_pfs.mem_events (Name, N_alloc, N_free, N_curr, Sz_alloc, Sz_free, Sz_curr, Query) SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
SELECT * FROM s.t_innodb_1;
SET @diff = (SELECT COUNT_ALLOC - N_alloc FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT COUNT_FREE - N_free FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT CURRENT_COUNT_USED - N_curr FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
DELETE FROM dd_pfs.mem_events WHERE Query = 'savepoint';
INSERT INTO dd_pfs.mem_events (Name, N_alloc, N_free, N_curr, Sz_alloc, Sz_free, Sz_curr, Query) SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
SELECT * FROM s.t_innodb_2;
SET @diff = (SELECT COUNT_ALLOC - N_alloc FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT COUNT_FREE - N_free FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT CURRENT_COUNT_USED - N_curr FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
DELETE FROM dd_pfs.mem_events WHERE Query = 'savepoint';
INSERT INTO dd_pfs.mem_events (Name, N_alloc, N_free, N_curr, Sz_alloc, Sz_free, Sz_curr, Query) SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
SELECT * FROM s.t_innodb_1;
SET @diff = (SELECT COUNT_ALLOC - N_alloc FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT COUNT_FREE - N_free FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT CURRENT_COUNT_USED - N_curr FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
DELETE FROM dd_pfs.mem_events WHERE Query = 'savepoint';
INSERT INTO dd_pfs.mem_events (Name, N_alloc, N_free, N_curr, Sz_alloc, Sz_free, Sz_curr, Query) SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
DROP TABLE s.t_innodb_1;
SET @diff = (SELECT COUNT_ALLOC - N_alloc FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT COUNT_FREE - N_free FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT CURRENT_COUNT_USED - N_curr FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
DELETE FROM dd_pfs.mem_events WHERE Query = 'savepoint';
INSERT INTO dd_pfs.mem_events (Name, N_alloc, N_free, N_curr, Sz_alloc, Sz_free, Sz_curr, Query) SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
DROP TABLE s.t_innodb_2;
SET @diff = (SELECT COUNT_ALLOC - N_alloc FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT COUNT_FREE - N_free FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT CURRENT_COUNT_USED - N_curr FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
DELETE FROM dd_pfs.mem_events WHERE Query = 'savepoint';
INSERT INTO dd_pfs.mem_events (Name, N_alloc, N_free, N_curr, Sz_alloc, Sz_free, Sz_curr, Query) SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
DROP SCHEMA s;
SET @diff = (SELECT COUNT_ALLOC - N_alloc FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT COUNT_FREE - N_free FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT CURRENT_COUNT_USED - N_curr FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
DELETE FROM dd_pfs.mem_events WHERE Query = 'savepoint';
INSERT INTO dd_pfs.mem_events (Name, N_alloc, N_free, N_curr, Sz_alloc, Sz_free, Sz_curr, Query) SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
SET foreign_key_checks= 0;
SET foreign_key_checks= DEFAULT;
DELETE FROM dd_pfs.mem_events WHERE Query = 'savepoint';
INSERT INTO dd_pfs.mem_events (Name, N_alloc, N_free, N_curr, Sz_alloc, Sz_free, Sz_curr, Query) SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
SELECT * FROM test.tables;
SET @diff = (SELECT COUNT_ALLOC - N_alloc FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT COUNT_FREE - N_free FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
SET @diff = (SELECT CURRENT_COUNT_USED - N_curr FROM performance_schema.memory_summary_global_by_event_name, dd_pfs.mem_events WHERE EVENT_NAME = 'memory/sql/dd::objects' AND EVENT_NAME = Name AND Query = 'savepoint');
DELETE FROM dd_pfs.mem_events WHERE Query = 'savepoint';
INSERT INTO dd_pfs.mem_events (Name, N_alloc, N_free, N_curr, Sz_alloc, Sz_free, Sz_curr, Query) SELECT EVENT_NAME AS Name, COUNT_ALLOC AS N_alloc, COUNT_FREE AS N_free, CURRENT_COUNT_USED AS N_curr, SUM_NUMBER_OF_BYTES_ALLOC AS Sz_alloc, SUM_NUMBER_OF_BYTES_FREE AS Sz_free, CURRENT_NUMBER_OF_BYTES_USED AS Sz_curr, 'savepoint' AS Query FROM performance_schema.memory_summary_global_by_event_name WHERE EVENT_NAME = 'memory/sql/dd::infrastructure' OR EVENT_NAME = 'memory/sql/dd::objects' OR EVENT_NAME = 'memory/sql/dd::String_type';
DROP TABLE test.tables;
CREATE TABLE test.t_150 (i int) TABLESPACE innodb_system;
SELECT * FROM  test.t_150;
FLUSH TABLES test.t_150;
CREATE TABLE test.t_149 (i int) TABLESPACE innodb_system;
SELECT * FROM  test.t_149;
FLUSH TABLES test.t_149;
CREATE TABLE test.t_148 (i int) TABLESPACE innodb_system;
SELECT * FROM  test.t_148;
FLUSH TABLES test.t_148;
CREATE TABLE test.t_147 (i int) TABLESPACE innodb_system;
SELECT * FROM  test.t_147;
FLUSH TABLES test.t_147;
CREATE TABLE test.t_146 (i int) TABLESPACE innodb_system;
SELECT * FROM  test.t_146;
FLUSH TABLES test.t_146;
CREATE TABLE test.t_145 (i int) TABLESPACE innodb_system;
SELECT * FROM  test.t_145;
FLUSH TABLES test.t_145;
CREATE TABLE test.t_144 (i int) TABLESPACE innodb_system;
SELECT * FROM  test.t_144;
FLUSH TABLES test.t_144;
CREATE TABLE test.t_143 (i int) TABLESPACE innodb_system;
SELECT * FROM  test.t_143;
FLUSH TABLES test.t_143;
CREATE TABLE test.t_142 (i int) TABLESPACE innodb_system;
SELECT * FROM  test.t_142;
FLUSH TABLES test.t_142;
CREATE TABLE test.t_141 (i int) TABLESPACE innodb_system;
SELECT * FROM  test.t_141;
FLUSH TABLES test.t_141;
CREATE TABLE test.t_140 (i int) TABLESPACE innodb_system;
SELECT * FROM  test.t_140;
FLUSH TABLES test.t_140;
CREATE TABLE test.t_139 (i int) TABLESPACE innodb_system;
