CREATE FUNCTION sf1() RETURNS INT return 0;
CREATE TABLE t1 (f1 INT);
CREATE TABLE t2 (f2 INT);
CREATE TABLE t3 (f3 INT);
PREPARE check_view_columns FROM 'SELECT table_name, column_name, column_type FROM information_schema.columns    WHERE table_name= ? ORDER BY table_name, column_name';
PREPARE check_view_status FROM 'SELECT table_name, table_comment FROM information_schema.tables WHERE    table_name= ?';
CREATE VIEW v1 AS SELECT * FROM t1;
EXECUTE check_view_columns USING @view;
CREATE VIEW v2 AS SELECT * FROM t2;
SET @view='v2';
EXECUTE check_view_columns USING @view;
CREATE VIEW v3 AS SELECT * FROM v2, t3;
SET @view='v3';
EXECUTE check_view_columns USING @view;
CREATE VIEW v4 AS SELECT sf1() AS sf;
SET @view='v4';
EXECUTE check_view_columns USING @view;
create view v5 as select * from v4;
SET @view='v5';
EXECUTE check_view_columns USING @view;
ALTER TABLE t1 ADD f2 INT;
SET @view='v1';
EXECUTE check_view_columns USING @view;
ALTER TABLE t1 CHANGE f1 f1 CHAR(100);
SET @view='v1';
EXECUTE check_view_columns USING @view;
ALTER TABLE t2 CHANGE f2 f2 CHAR(100);
SET @view='v2';
EXECUTE check_view_columns USING @view;
SET @view='v3';
EXECUTE check_view_columns USING @view;
SET @view='v1';
EXECUTE check_view_status USING @view;
ALTER TABLE t1 DROP f1;
EXECUTE check_view_status USING @view;
SET @view='v1';
ALTER TABLE t2 ADD f1 DATETIME;
EXECUTE check_view_status USING @view;
ALTER TABLE t2 DROP f1;
SET @view='v1';
EXECUTE check_view_status USING @view;
ALTER TABLE t1 ADD f1 int;
EXECUTE check_view_status USING @view;
EXECUTE check_view_columns USING @view;
ALTER TABLE t2 CHANGE f2 f5 int;
SET @view='v2';
EXECUTE check_view_status USING @view;
SET @view='v3';
EXECUTE check_view_status USING @view;
EXECUTE check_view_columns USING @view;
ALTER TABLE t2 CHANGE f5 f2 int;
SET @view='v2';
EXECUTE check_view_status USING @view;
EXECUTE check_view_columns USING @view;
SET @view='v3';
EXECUTE check_view_status USING @view;
EXECUTE check_view_columns USING @view;
DROP TABLE t2;
SET @view='v2';
EXECUTE check_view_status USING @view;
SET @view='v3';
EXECUTE check_view_status USING @view;
CREATE TABLE t2(f4 int);
SET @view='v2';
EXECUTE check_view_status USING @view;
SET @view='v3';
EXECUTE check_view_status USING @view;
DROP TABLE t2;
CREATE TABLE t2(f2 int);
SET @view='v2';
EXECUTE check_view_status USING @view;
SET @view='v3';
EXECUTE check_view_status USING @view;
RENAME TABLE t2 TO t5;
SET @view='v2';
EXECUTE check_view_status USING @view;
SET @view='v3';
EXECUTE check_view_status USING @view;
CREATE VIEW vw AS SELECT * FROM t5;
SET @view='vw';
EXECUTE check_view_status USING @view;
RENAME TABLE t5 to t2;
SET @view='v2';
EXECUTE check_view_status USING @view;
SET @view='v3';
EXECUTE check_view_status USING @view;
SET @view='vw';
EXECUTE check_view_status USING @view;
DROP VIEW vw;
ALTER TABLE t2 RENAME t5;
SET @view='v2';
EXECUTE check_view_status USING @view;
SET @view='v3';
EXECUTE check_view_status USING @view;
CREATE VIEW vw AS SELECT * FROM t5;
SET @view='vw';
EXECUTE check_view_status USING @view;
ALTER TABLE t5 RENAME t2;
SET @view='v2';
EXECUTE check_view_status USING @view;
SET @view='v3';
EXECUTE check_view_status USING @view;
SET @view='vw';
EXECUTE check_view_status USING @view;
DROP VIEW vw;
DROP FUNCTION sf1;
SET @view='v4';
EXECUTE check_view_status USING @view;
SET @view='v5';
EXECUTE check_view_status USING @view;
CREATE FUNCTION sf1() RETURNS INT return 0;
SET @view='v4';
EXECUTE check_view_status USING @view;
SET @view='v5';
EXECUTE check_view_status USING @view;
SET @view='v3';
EXECUTE check_view_status USING @view;
DROP VIEW v2;
EXECUTE check_view_status USING @view;
CREATE VIEW v2 AS SELECT * FROM t2;
SET @view='v3';
EXECUTE check_view_status USING @view;
