set names utf8;
DROP DATABASE IF EXISTS mysqltest1;
CREATE DATABASE mysqltest1 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_unicode_ci;
use mysqltest1;
CREATE TABLE t1(кол INT);
INSERT INTO t1 VALUES(1);
CREATE VIEW v1 AS SELECT 'тест' AS c1, кол AS c2 FROM t1;
CREATE VIEW v2 AS SELECT _koi8r'����' as c1;
CREATE VIEW v3 AS SELECT _koi8r'����';
SHOW CREATE VIEW v1;
SHOW CREATE VIEW v2;
SHOW CREATE VIEW v3;
SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE table_name = 'v1';
SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE table_name = 'v2';
SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE table_name = 'v3';
SELECT COLLATION(c1), COLLATION(c2) FROM v1;
SELECT COLLATION(c1) FROM v2;
SELECT * FROM v3;
ALTER DATABASE mysqltest1 COLLATE cp866_general_ci;
SET @@character_set_client= cp1251;
SET @@character_set_results= cp1251;
SET @@collation_connection= cp1251_general_ci;
SELECT * FROM mysqltest1.v1;
SELECT * FROM mysqltest1.v2;
SELECT * FROM mysqltest1.v3;
use mysqltest1;
set names utf8;
SHOW CREATE VIEW v1;
SHOW CREATE VIEW v2;
SHOW CREATE VIEW v3;
SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE table_name = 'v1';
SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE table_name = 'v2';
SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE table_name = 'v3';
SELECT COLLATION(c1), COLLATION(c2) FROM v1;
SELECT COLLATION(c1) FROM v2;
SELECT * FROM v3;
DROP DATABASE mysqltest1;
SET @@character_set_client= cp1251;
SET @@character_set_results= cp1251;
SET @@collation_connection= cp1251_general_ci;
SELECT * FROM mysqltest1.v1;
SELECT * FROM mysqltest1.v2;
SELECT * FROM mysqltest1.v3;
use mysqltest1;
set names utf8;
SHOW CREATE VIEW v1;
SHOW CREATE VIEW v2;
SHOW CREATE VIEW v3;
SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE table_name = 'v1';
SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE table_name = 'v2';
SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE table_name = 'v3';
SELECT COLLATION(c1), COLLATION(c2) FROM v1;
SELECT COLLATION(c1) FROM v2;
SELECT * FROM v3;
use test;
DROP DATABASE mysqltest1;
DROP DATABASE IF EXISTS mysqltest1;
DROP DATABASE IF EXISTS mysqltest2;
CREATE DATABASE mysqltest1 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_unicode_ci;
CREATE DATABASE mysqltest2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_unicode_ci;
use mysqltest1;
CREATE PROCEDURE p1( INOUT парам1 CHAR(10), OUT парам2 CHAR(10)) BEGIN DECLARE перем1 CHAR(10); SELECT COLLATION(перем1) AS c1, COLLATION(парам1) AS c2, COLLATION(парам2) AS c3; SELECT COLLATION('текст') AS c4, COLLATION(_utf8 'текст') AS c5, COLLATION(_koi8r    '�����') AS c6, @@collation_connection AS c7, @@character_set_client AS c8; SET парам1 = 'a'; SET парам2 = 'b'; END;
CREATE PROCEDURE p2( INOUT парам1 CHAR(10) CHARACTER SET utf8, OUT парам2 CHAR(10) CHARACTER SET utf8) BEGIN DECLARE перем1 CHAR(10) CHARACTER SET utf8; SELECT COLLATION(перем1) AS c1, COLLATION(парам1) AS c2, COLLATION(парам2) AS c3; SELECT COLLATION('текст') AS c4, COLLATION(_utf8 'текст') AS c5, COLLATION(_koi8r    '�����') AS c6, @@collation_connection AS c7, @@character_set_client AS c8; SET парам1 = 'a'; SET парам2 = 'b'; END;
CREATE PROCEDURE mysqltest2.p3( INOUT парам1 CHAR(10), OUT парам2 CHAR(10)) BEGIN DECLARE перем1 CHAR(10); SELECT COLLATION(перем1) AS c1, COLLATION(парам1) AS c2, COLLATION(парам2) AS c3; SELECT COLLATION('текст') AS c4, COLLATION(_utf8 'текст') AS c5, COLLATION(_koi8r    '�����') AS c6, @@collation_connection AS c7, @@character_set_client AS c8; SET парам1 = 'a'; SET парам2 = 'b'; END;
CREATE PROCEDURE mysqltest2.p4( INOUT парам1 CHAR(10) CHARACTER SET utf8, OUT парам2 CHAR(10) CHARACTER SET utf8) BEGIN DECLARE перем1 CHAR(10) CHARACTER SET utf8; SELECT COLLATION(перем1) AS c1, COLLATION(парам1) AS c2, COLLATION(парам2) AS c3; SELECT COLLATION('текст') AS c4, COLLATION(_utf8 'текст') AS c5, COLLATION(_koi8r    '�����') AS c6, @@collation_connection AS c7, @@character_set_client AS c8; SET парам1 = 'a'; SET парам2 = 'b'; END;
SHOW CREATE PROCEDURE p1;
SHOW CREATE PROCEDURE p2;
SHOW CREATE PROCEDURE mysqltest2.p3;
SHOW CREATE PROCEDURE mysqltest2.p4;
SHOW PROCEDURE STATUS LIKE 'p1';
SHOW PROCEDURE STATUS LIKE 'p2';
SHOW PROCEDURE STATUS LIKE 'p3';
SHOW PROCEDURE STATUS LIKE 'p4';
SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE routine_name = 'p1';
SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE routine_name = 'p2';
SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE routine_name = 'p3';
SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE routine_name = 'p4';
SET @a = '1';
SET @b = '2';
CALL p1(@a, @b);
SELECT COLLATION(@a) AS ca, COLLATION(@b) cb;
CALL p2(@a, @b);
SELECT COLLATION(@a) AS ca, COLLATION(@b) cb;
CALL mysqltest2.p3(@a, @b);
SELECT COLLATION(@a) AS ca, COLLATION(@b) cb;
CALL mysqltest2.p4(@a, @b);
SELECT COLLATION(@a) AS ca, COLLATION(@b) cb;
ALTER DATABASE mysqltest1 COLLATE cp866_general_ci;
ALTER DATABASE mysqltest2 COLLATE cp866_general_ci;
SET @@character_set_client= cp1251;
SET @@character_set_results= cp1251;
SET @@collation_connection= cp1251_general_ci;
CALL p1(@a, @b);
CALL p2(@a, @b);
CALL mysqltest2.p3(@a, @b);
CALL mysqltest2.p4(@a, @b);
set names utf8;
SHOW CREATE PROCEDURE p1;
SHOW CREATE PROCEDURE p2;
SHOW CREATE PROCEDURE mysqltest2.p3;
SHOW CREATE PROCEDURE mysqltest2.p4;
SHOW PROCEDURE STATUS LIKE 'p1';
SHOW PROCEDURE STATUS LIKE 'p2';
SHOW PROCEDURE STATUS LIKE 'p3';
SHOW PROCEDURE STATUS LIKE 'p4';
SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE routine_name = 'p1';
SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE routine_name = 'p2';
SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE routine_name = 'p3';
SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE routine_name = 'p4';
SET @a = '1';
SET @b = '2';
CALL p1(@a, @b);
SELECT COLLATION(@a) AS ca, COLLATION(@b) cb;
CALL p2(@a, @b);
SELECT COLLATION(@a) AS ca, COLLATION(@b) cb;
CALL mysqltest2.p3(@a, @b);
SELECT COLLATION(@a) AS ca, COLLATION(@b) cb;
CALL mysqltest2.p4(@a, @b);
SELECT COLLATION(@a) AS ca, COLLATION(@b) cb;
DROP DATABASE mysqltest1;
DROP DATABASE mysqltest2;
SET @@character_set_client= cp1251;
