create table t1(f1 int, key f1_idx(f1 desc)) engine=heap;
create table t1(a int, b int, key a_desc_b_asc (a desc, b), key a_asc_b_desc (a, b desc)) engine= innodb;
flush tables;
show create table t1;
insert into t1 values(1,6),(1,5),(2,5),(2,4),(3,4),(3,3), (4,3),(4,2),(5,2),(5,1),(6,1),(NULL,NULL);
analyze table t1;
explain select * from t1 order by a desc;
select * from t1 order by a desc;
explain select * from t1 order by a desc, b asc;
select * from t1 order by a desc, b asc;
explain select * from t1 order by a asc;
select * from t1 order by a asc, b desc;
explain select * from t1 order by a asc, b desc;
select * from t1 order by a asc, b desc;
explain select * from t1 group by a,b order by a, b desc;
select * from t1 group by a,b order by a, b desc;
explain select * from t1 group by a, b;
explain select * from t1 group by a, b order by a;
explain select * from t1 group by a , b order by a desc;
explain select * from t1 group by a, b order by a desc, b;
explain select * from t1 group by a, b order by a asc, b desc;
alter table t1 drop index a_asc_b_desc;
explain select * from t1 group by a, b order by a;
explain select distinct a from t1;
select distinct a from t1;
explain select a from t1 group by a;
select a from t1 group by a;
explain select * from t1 order by a asc;
select * from t1 order by a asc, b desc;
explain select * from t1 order by a asc, b desc;
select * from t1 order by a asc, b desc;
explain select * from t1 order by a desc, b desc;
select * from t1 order by a desc, b desc;
explain select * from t1 order by a asc, b asc;
select * from t1 order by a asc, b asc;
create index i1 on t1 (a desc, a asc);
create index i1 on t1 (a desc, b desc);
show create table t1;
create table t2 (a int auto_increment, primary key (a desc)) engine= innodb;
show create table t2;
insert ignore into t2 select a from t1;
select * from t2;
create table t3 (a varchar(10), key i1(a(5) desc)) engine= innodb;
flush tables;
show create table t3;
create index i2 on t3(a(6));
flush tables;
show create table t3;
alter table t3 add fulltext index fts_idx(a desc);
alter table t3 add fulltext index fts_idx(a asc);
alter table t3 add column b point not null, add spatial index gis_idx(b desc);
alter table t3 add column b point not null, add spatial index gis_idx(b asc);
create table t4 (a text, fulltext key fts(a desc));
create table t4 (a point not null, spatial key gis(a desc));
create table t4 (a text, fulltext key fts(a asc));
create table t4 (a point not null, spatial key gis(a asc));
create table t5 (f1 int, key h(f1 asc) using hash) engine= heap;
create table t5 (f1 int, key h(f1 desc) using hash) engine= heap;
create table t5 (f1 int, key h(f1) using hash) engine= heap;
drop table t1,t2,t3,t5;
CREATE TABLE t0 (i INTEGER);
INSERT INTO t0 VALUES (0),(1),(2),(3),(4),(5),(6),(7),(8),(9);
CREATE TABLE t1 (i1 INTEGER NOT NULL, i2 INTEGER NOT NULL, i3 INTEGER NOT NULL, KEY k1 (i1 desc, i2) ) ENGINE= innodb;
INSERT INTO t1 SELECT a.i*10 + b.i + 1, a.i*100 + b.i*10 + c.i, a.i FROM t0 AS a, t0 AS b, t0 AS c;
ANALYZE TABLE t1;
EXPLAIN SELECT * FROM t1 WHERE i1 BETWEEN 50 AND 52 AND MOD(i2,2)=1 ORDER BY i1 DESC;
SELECT * FROM t1 WHERE i1 BETWEEN 50 AND 52 AND MOD(i2,2)=1 ORDER BY i1 DESC;
EXPLAIN SELECT * FROM t1 WHERE (i1 BETWEEN 50 AND 52 OR i1 BETWEEN 70 AND 72) AND MOD(i2,2)=1 ORDER BY i1 DESC;
SELECT * FROM t1 WHERE (i1 BETWEEN 50 AND 52 OR i1 BETWEEN 70 AND 72) AND MOD(i2,2)=1 ORDER BY i1 DESC;
EXPLAIN SELECT * FROM t1 WHERE ( (i1=50 AND i2=495) OR i1 BETWEEN 70 AND 72) AND MOD(i2,2)=1 ORDER BY i1 DESC;
SELECT * FROM t1 WHERE ( (i1=50 AND i2=495) OR i1 BETWEEN 70 AND 72) AND MOD(i2,2)=1 ORDER BY i1 DESC;
EXPLAIN SELECT * FROM t1 WHERE i1 >= 50 AND i1 < 52 AND MOD(i2,2)=1 ORDER BY i1 DESC;
SELECT * FROM t1 WHERE i1 >= 50 AND i1 < 52 AND MOD(i2,2)=1 ORDER BY i1 DESC;
EXPLAIN SELECT * FROM t1 WHERE i1 > 50 AND i1 <= 52 AND MOD(i2,2)=1 ORDER BY i1 DESC;
SELECT * FROM t1 WHERE i1 > 50 AND i1 <= 52 AND MOD(i2,2)=1 ORDER BY i1 DESC;
ALTER TABLE t1 DROP INDEX k1, ADD INDEX k1(i1, i2);
ANALYZE TABLE t1;
EXPLAIN SELECT * FROM t1 WHERE i1 BETWEEN 50 AND 52 AND MOD(i2,2)=1 ORDER BY i1 DESC;
SELECT * FROM t1 WHERE i1 BETWEEN 50 AND 52 AND MOD(i2,2)=1 ORDER BY i1 DESC;
ALTER TABLE t1 DROP INDEX k1, ADD INDEX k1(i1, i2 DESC);
ANALYZE TABLE t1;
EXPLAIN SELECT * FROM t1 WHERE i1 BETWEEN 50 AND 52 AND i2 BETWEEN 495 AND 515 ORDER BY i1, i2 DESC;
SELECT * FROM t1 WHERE i1 BETWEEN 50 AND 52 AND i2 BETWEEN 495 AND 515 ORDER BY i1, i2 DESC;
ALTER TABLE t1 DROP INDEX k1, ADD INDEX k1(i1, i2 DESC, i3);
ANALYZE TABLE t1;
EXPLAIN SELECT * FROM t1 WHERE i1 BETWEEN 48 AND 62 AND i2 BETWEEN 395 AND 615 AND i3 BETWEEN 4 AND 5 AND MOD(i1,2)=0 AND MOD(i2,2)=1 ORDER BY i1, i2 DESC;
SELECT * FROM t1 WHERE i1 BETWEEN 48 AND 62 AND i2 BETWEEN 395 AND 615 AND i3 BETWEEN 4 AND 5 AND MOD(i1,2)=0 AND MOD(i2,2)=1 ORDER BY i1, i2 DESC;
ALTER TABLE t1 DROP INDEX k1, ADD INDEX k1(i1, i2 DESC, i3 DESC);
ANALYZE TABLE t1;
EXPLAIN SELECT * FROM t1 WHERE i1 BETWEEN 48 AND 62 AND i2 BETWEEN 395 AND 615 AND i3 BETWEEN 4 AND 5 AND MOD(i1,2)=0 AND MOD(i2,2)=1 ORDER BY i1, i2 DESC;
SELECT * FROM t1 WHERE i1 BETWEEN 48 AND 62 AND i2 BETWEEN 395 AND 615 AND i3 BETWEEN 4 AND 5 AND MOD(i1,2)=0 AND MOD(i2,2)=1 ORDER BY i1, i2 DESC;
ALTER TABLE t1 DROP INDEX k1, ADD INDEX k1(i1, i2 DESC, i3);
ANALYZE TABLE t1;
EXPLAIN SELECT * FROM t1   WHERE  ((i1 BETWEEN 48 AND 62 AND i2 BETWEEN 395 AND 615 AND i3 BETWEEN 4 AND 5) or i1 between 70 and 72) AND MOD(i1,2)=0 AND MOD(i2,2)=1 ORDER BY i1 desc, i2 ;
SELECT * FROM t1   WHERE  ((i1 BETWEEN 48 AND 62 AND i2 BETWEEN 395 AND 615 AND i3 BETWEEN 4 AND 5) or i1 between 70 and 72) AND MOD(i1,2)=0 AND MOD(i2,2)=1 ORDER BY i1 desc, i2 ;
ALTER TABLE t1 DROP INDEX k1, ADD INDEX k1(i1 DESC, i2, i3);
ANALYZE TABLE t1;
EXPLAIN SELECT * FROM t1   WHERE  ((i1 BETWEEN 48 AND 62 AND i2 BETWEEN 395 AND 615 AND i3 BETWEEN 4 AND 5) or i1 between 70 and 72) AND MOD(i1,2)=0 AND MOD(i2,2)=1 ORDER BY i1 desc, i2 ;
SELECT * FROM t1   WHERE  ((i1 BETWEEN 48 AND 62 AND i2 BETWEEN 395 AND 615 AND i3 BETWEEN 4 AND 5) or i1 between 70 and 72) AND MOD(i1,2)=0 AND MOD(i2,2)=1 ORDER BY i1 desc, i2 ;
ALTER TABLE t1 DROP INDEX k1, ADD INDEX k1(i1 DESC, i2, i3);
ANALYZE TABLE t1;
EXPLAIN SELECT * FROM t1 WHERE ( (i1=50 AND i2=495 and i3=4) OR i1 BETWEEN 70 AND 72) AND MOD(i2,2)=1 ORDER BY i1 DESC;
SELECT * FROM t1 WHERE ( (i1=50 AND i2=495 and i3=4) OR i1 BETWEEN 70 AND 72) AND MOD(i2,2)=1 ORDER BY i1 DESC;
ALTER TABLE t1 ADD COLUMN (i4 INTEGER NOT NULL);
UPDATE t1 SET i4=i3;
ALTER TABLE t1 DROP INDEX k1, ADD INDEX k1(i1 DESC, i2, i3 DESC, i4);
ANALYZE TABLE t1;
EXPLAIN SELECT * FROM t1   WHERE ((i1 BETWEEN 48 AND 62 AND i2 BETWEEN 395 AND 615 AND i3 BETWEEN 4 AND 5 AND i4 BETWEEN 5 AND 6) OR i1 between 70 and 72) AND MOD(i1,2)=0 AND MOD(i2,2)=1 ORDER BY i1 desc, i2 ;
SELECT * FROM t1   WHERE ((i1 BETWEEN 48 AND 62 AND i2 BETWEEN 395 AND 615 AND i3 BETWEEN 4 AND 5 AND i4 BETWEEN 5 AND 6) OR i1 between 70 and 72) AND MOD(i1,2)=0 AND MOD(i2,2)=1 ORDER BY i1 desc, i2 ;
DROP TABLE t0, t1;
CREATE TABLE t1 (a INT, b INT, KEY i1 (a DESC, b DESC));
INSERT INTO t1 (a, b) VALUES (1,1), (1,2), (1,3);
INSERT INTO t1 SELECT a + 1, b FROM t1;
INSERT INTO t1 SELECT a + 2, b FROM t1;
INSERT INTO t1 SELECT a + 4, b FROM t1;
ANALYZE TABLE t1;
EXPLAIN SELECT a, MIN(b), MAX(b) FROM t1 GROUP BY a ORDER BY a DESC;
SELECT a, MIN(b), MAX(b) FROM t1 GROUP BY a ORDER BY a DESC;
DROP TABLE t1;
create table t1 (a int not null, b int, c varchar(10), key (a desc, b desc, c desc));
insert into t1 values (1, NULL, NULL), (1, NULL, 'b'), (1, 1, NULL), (1, 1, 'b'), (1, 1, 'b'), (2, 1, 'a'), (2, 1, 'b'), (2, 2, 'a'), (2, 2, 'b'), (2, 3, 'c'),(1,3,'b');
insert into t1 values (0, NULL, NULL), (0, NULL, 'b'), (0, 0, NULL), (0, 0, 'b'), (0, 0, 'b'), (0, 0, 'a'), (0, 0, 'b'), (0, 0, 'a'), (0, 0, 'b'), (0, 0, 'c'),(0,0,'b');
