drop table if exists t1;
drop database if exists mysqltest;
drop database if exists client_test_db;
drop table t1;
create table t1(n int);
insert into t1 values(1);
create temporary table t1( n int);
insert into t1 values(2);
create table t1(n int);
drop table t1;
select * from t1;
create database mysqltest;
drop database if exists mysqltest;
create database mysqltest;
create table mysqltest.mysqltest (n int);
insert into mysqltest.mysqltest values (4);
select * from mysqltest.mysqltest;
drop database if exists mysqltest;
create database mysqltest;
use mysqltest;
drop table table1, table2, table3, table4, table5, table6, table7, table8, table9, table10, table11, table12, table13, table14, table15, table16, table17, table18, table19, table20, table21, table22, table23, table24, table25, table26, table27, table28;
drop table table1, table2, table3, table4, table5, table6, table7, table8, table9, table10, table11, table12, table13, table14, table15, table16, table17, table18, table19, table20, table21, table22, table23, table24, table25, table26, table27, table28, table29, table30;
use test;
drop database mysqltest;
flush tables with read lock;
create database mysqltest;
unlock tables;
create database mysqltest;
select schema_name from information_schema.schemata order by schema_name;
flush tables with read lock;
drop database mysqltest;
unlock tables;
drop database mysqltest;
select schema_name from information_schema.schemata order by schema_name;
drop database mysqltest;
drop table t1;
flush tables with read lock;
create table t1(n int);
unlock tables;
create table t1(n int);
show tables;
drop table t1;
drop database if exists mysqltest;
drop table if exists t1;
create table t1 (i int);
create database mysqltest;
lock tables t1 read;
drop table t1;
show open tables;
drop database mysqltest;
select 1;
unlock tables;
drop table if exists t1,t2;
create table t1 (a int);
create table t2 (a int);
lock table t1 read;
drop table t2;
drop table t1;
unlock tables;
drop table t1,t2;
create table t1 (i int);
create table t2 (i int);
lock tables t1 read;
lock tables t2 read;
drop table t1;
drop table t1,t2;
unlock tables;
drop table t1,t2;
create database mysqltestbug26703;
use mysqltestbug26703;
create table `#mysql50#abc``def` ( id int );
create table `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` (a int);
create table `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` (a int);
create table `#mysql50#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` (a int);
create table `#mysql50#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` (a int);
use test;
drop database mysqltestbug26703;
DROP TABLE IF EXISTS t1;
DROP TABLE t1;
SHOW WARNINGS;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (a INT);
LOCK TABLE t1 WRITE;
DROP TABLE t1, t1;
UNLOCK TABLES;
DROP TABLE t1;
DROP TABLE table1;
DROP TABLE table1,table2;
DROP VIEW view1,view2,view3,view4;
DROP TABLE IF EXISTS table1;
DROP TABLE IF EXISTS table1,table2;
DROP VIEW IF EXISTS view1,view2,view3,view4;
CREATE TABLE table1(a int);
CREATE TABLE table2(b int);
CREATE TRIGGER trg1 AFTER INSERT ON table1 FOR EACH ROW INSERT INTO table2 SELECT t.notable.*;
INSERT INTO table1 VALUES (1);
DROP TABLE table1,table2;
CREATE DATABASE bug19573998;
USE bug19573998;
CREATE TABLE t1(i int);
FLUSH TABLES t1 FOR EXPORT;
DROP DATABASE bug19573998;
UNLOCK TABLES;
CREATE DATABASE bug19573998;
DROP DATABASE bug19573998;
USE test;
