CREATE TABLE t1(i INT) ENGINE_ATTRIBUTE;
CREATE TABLE t1(i INT) engine_ATTRIBUTE='{bad:json';
CREATE TABLE t1(i INT) ENGINE_ATTRIBUTE='';
CREATE TABLE t1(i INT) ENGINE_ATTRIBUTE='{"table attr": "for engine"}';
CREATE TABLE t1(i INT) SECONDARY_engine_ATTRIBUTE='{bad:json';
CREATE TABLE t1(i INT) SECONDARY_ENGINE_ATTRIBUTE='';
SHOW CREATE TABLE t1;
DROP TABLE t1;
CREATE TABLE t1(i INT) SECONDARY_ENGINE_ATTRIBUTE='{"table attr": "for secondary engine"}';
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.tables_extensions WHERE table_name = 't1';
DROP TABLE t1;
CREATE TABLE t1(i INT ENGINE_ATTRIBUTE='');
CREATE TABLE t1(i INT ENGINE_ATTRIBUTE='{"column attr": "for engine"}' SECONDARY_ENGINE_ATTRIBUTE='{"column attr": "for secondary engine"}');
CREATE TABLE t1(i INT, j INT, INDEX(j) ENGINE_ATTRIBUTE='{"index attr": }');
CREATE TABLE t1(i INT, j INT, INDEX(j) ENGINE_ATTRIBUTE='{"index attr": "for engine"}' SECONDARY_ENGINE_ATTRIBUTE='{"index attr": "for secondary engine"}');
CREATE TABLE t1(i INT, j INT);
CREATE INDEX ix ON t1(i) ENGINE_ATTRIBUTE;
CREATE INDEX ix ON t1(i) ENGINE_ATTRIBUTE='{attr';
CREATE INDEX ix ON t1(i) ENGINE_ATTRIBUTE='{"index attr": "for engine"}' SECONDARY_ENGINE_ATTRIBUTE='{"index attr":"for secondary engine"}';
SHOW CREATE TABLE t1;
SHOW INDEX FROM t1;
SELECT * FROM information_schema.table_constraints_extensions WHERE table_name = 't1';
DROP TABLE t1;
CREATE TABLE t1(i INT ENGINE_ATTRIBUTE = '{"column attr": "i"}'        SECONDARY_ENGINE_ATTRIBUTE='{"secondary column attr": "i"}',  j INT ENGINE_ATTRIBUTE = '{"column attr": "j"}'        SECONDARY_ENGINE_ATTRIBUTE='{"secondary column attr": "j"}',  INDEX(j) ENGINE_ATTRIBUTE='{"index attr": "index on j"}'  SECONDARY_ENGINE_ATTRIBUTE='{"secondary index attr": "index on j"}') ENGINE_ATTRIBUTE = '{"table attr":"t1"}' SECONDARY_ENGINE_ATTRIBUTE = '{"secondary table attr": "t1"}';
CREATE TABLE t1(i INT ENGINE_ATTRIBUTE = '{"column attr": "i"}'        SECONDARY_ENGINE_ATTRIBUTE='{"secondary column attr": "i"}'        COMMENT 'Column comment',  j INT ENGINE_ATTRIBUTE = '{"column attr": "j"}'        SECONDARY_ENGINE_ATTRIBUTE='{"secondary column attr": "j"}',  INDEX(j) ENGINE_ATTRIBUTE='{"index attr": "index on j"}'  SECONDARY_ENGINE_ATTRIBUTE='{"secondary index attr": "index on j"}' COMMENT 'index comment') ENGINE_ATTRIBUTE = '{"table attr":"t1"}' SECONDARY_ENGINE_ATTRIBUTE = '{"secondary table attr": "t1"}' COMMENT='Table comment';
CREATE TABLE t1(i INT, j INT, k INT);
ALTER TABLE t1 ENGINE_ATTRIBUTE='{"table algo": "none"}';
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.tables_extensions WHERE table_name = 't1';
ALTER TABLE t1 ENGINE_ATTRIBUTE='{"table algo": "inplace"}', ALGORITHM=INPLACE;
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.tables_extensions WHERE table_name = 't1';
ALTER TABLE t1 ENGINE_ATTRIBUTE='{"table algo": "instant"}',  ALGORITHM=INSTANT;
ALTER TABLE t1 ADD COLUMN l VARCHAR(64) ENGINE_ATTRIBUTE='{"add column algo":"none"}';
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.columns_extensions WHERE table_name = 't1';
ALTER TABLE t1 ADD COLUMN m VARCHAR(64) ENGINE_ATTRIBUTE='{"add column algo":"inplace"}', ALGORITHM=INPLACE;
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.columns_extensions WHERE table_name = 't1';
ALTER TABLE t1 ADD COLUMN n VARCHAR(64) ENGINE_ATTRIBUTE='{"add column algo":"instant"}', ALGORITHM=INSTANT;
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.columns_extensions WHERE table_name = 't1';
ALTER TABLE t1 MODIFY COLUMN l INT ENGINE_ATTRIBUTE='{"modify column algo": "none"}';
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.columns_extensions WHERE table_name = 't1';
ALTER TABLE t1 MODIFY COLUMN m INT ENGINE_ATTRIBUTE='{"modify column algo": "inplace"}', ALGORITHM=INPLACE;
ALTER TABLE t1 MODIFY COLUMN n INT ENGINE_ATTRIBUTE='{"modify column algo": "instant"}', ALGORITHM=INSTANT;
ALTER TABLE t1 CHANGE COLUMN l ll CHAR(8) ENGINE_ATTRIBUTE='{"change column algo": "none"}';
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.columns_extensions WHERE table_name = 't1';
ALTER TABLE t1 CHANGE COLUMN m mm CHAR(8) ENGINE_ATTRIBUTE='{"change column algo": "inplace" }', ALGORITHM=INPLACE;
ALTER TABLE t1 CHANGE COLUMN n nn CHAR(8) ENGINE_ATTRIBUTE='{"change column algo": "instant" }', ALGORITHM=INSTANT;
ALTER TABLE t1 ADD INDEX (i) ENGINE_ATTRIBUTE='{"index algo":"none"}';
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.table_constraints_extensions WHERE table_name = 't1';
ALTER TABLE t1 ADD INDEX (m) ENGINE_ATTRIBUTE='{"index algo":"inplace"}', ALGORITHM=INPLACE;
ALTER TABLE t1 ADD INDEX (n) ENGINE_ATTRIBUTE='{"index algo":"instant"}', ALGORITHM=INSTANT;
DROP TABLE t1;
CREATE TABLE t1(i INT, j INT, k INT);
ALTER TABLE t1 SECONDARY_ENGINE_ATTRIBUTE='{"table algo": "none"}';
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.tables_extensions WHERE table_name = 't1';
ALTER TABLE t1 SECONDARY_ENGINE_ATTRIBUTE='{"table algo": "inplace"}', ALGORITHM=INPLACE;
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.tables_extensions WHERE table_name = 't1';
ALTER TABLE t1 SECONDARY_ENGINE_ATTRIBUTE='{"table algo": "instant"}',  ALGORITHM=INSTANT;
ALTER TABLE t1 ADD COLUMN l VARCHAR(64) SECONDARY_ENGINE_ATTRIBUTE='{"add column algo":"none"}';
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.columns_extensions WHERE table_name = 't1';
ALTER TABLE t1 ADD COLUMN m VARCHAR(64) SECONDARY_ENGINE_ATTRIBUTE='{"add column algo":"inplace"}', ALGORITHM=INPLACE;
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.columns_extensions WHERE table_name = 't1';
ALTER TABLE t1 ADD COLUMN n VARCHAR(64) SECONDARY_ENGINE_ATTRIBUTE='{"add column algo":"instant"}', ALGORITHM=INSTANT;
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.columns_extensions WHERE table_name = 't1';
ALTER TABLE t1 MODIFY COLUMN l INT SECONDARY_ENGINE_ATTRIBUTE='{"modify column algo": "none"}';
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.columns_extensions WHERE table_name = 't1';
ALTER TABLE t1 MODIFY COLUMN m INT SECONDARY_ENGINE_ATTRIBUTE='{"modify column algo": "inplace"}', ALGORITHM=INPLACE;
ALTER TABLE t1 MODIFY COLUMN m INT SECONDARY_ENGINE_ATTRIBUTE='{"modify column algo": "inplace"}', ALGORITHM=INPLACE;
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.columns_extensions WHERE table_name = 't1';
ALTER TABLE t1 MODIFY COLUMN n INT SECONDARY_ENGINE_ATTRIBUTE='{"modify column algo": "instant"}', ALGORITHM=INSTANT;
ALTER TABLE t1 MODIFY COLUMN n INT SECONDARY_ENGINE_ATTRIBUTE='{"modify column algo": "instant"}', ALGORITHM=INSTANT;
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.columns_extensions WHERE table_name = 't1';
ALTER TABLE t1 CHANGE COLUMN l ll CHAR(8) SECONDARY_ENGINE_ATTRIBUTE='{"change column algo": "none"}';
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.columns_extensions WHERE table_name = 't1';
ALTER TABLE t1 CHANGE COLUMN m mm CHAR(8) SECONDARY_ENGINE_ATTRIBUTE='{"change column algo": "inplace" }', ALGORITHM=INPLACE;
ALTER TABLE t1 CHANGE COLUMN m mm CHAR(8) SECONDARY_ENGINE_ATTRIBUTE='{"change column algo": "inplace" }', ALGORITHM=INPLACE;
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.columns_extensions WHERE table_name = 't1';
ALTER TABLE t1 CHANGE COLUMN n nn CHAR(8) SECONDARY_ENGINE_ATTRIBUTE='{"change column algo": "instant" }', ALGORITHM=INSTANT;
ALTER TABLE t1 CHANGE COLUMN n nn CHAR(8) SECONDARY_ENGINE_ATTRIBUTE='{"change column algo": "instant" }', ALGORITHM=INSTANT;
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.columns_extensions WHERE table_name = 't1';
ALTER TABLE t1 ADD INDEX (i) SECONDARY_ENGINE_ATTRIBUTE='{"index algo":"none"}';
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.table_constraints_extensions WHERE table_name = 't1';
ALTER TABLE t1 ADD INDEX (m) SECONDARY_ENGINE_ATTRIBUTE='{"index algo":"inplace"}', ALGORITHM=INPLACE;
SHOW CREATE TABLE t1;
SELECT * FROM information_schema.table_constraints_extensions WHERE table_name = 't1';
ALTER TABLE t1 ADD INDEX (n) SECONDARY_ENGINE_ATTRIBUTE='{"index algo":"instant"}', ALGORITHM=INSTANT;
DROP TABLE t1;
CREATE TABLE t1(i INT, j INT, INDEX jix (j));
ALTER TABLE t1 MODIFY COLUMN i INT ENGINE_ATTRIBUTE = '{"column attr": "i"}'        SECONDARY_ENGINE_ATTRIBUTE='{"secondary column attr": "i"}', MODIFY COLUMN j INT ENGINE_ATTRIBUTE = '{"column attr": "j"}'        SECONDARY_ENGINE_ATTRIBUTE='{"secondary column attr": "j"}', DROP INDEX jix, ADD INDEX jix (i) ENGINE_ATTRIBUTE='{"index attr": "index on j"}'        SECONDARY_ENGINE_ATTRIBUTE='{"secondary index attr": "index on j"}', ENGINE_ATTRIBUTE = '{"table attr":"t1"}'        SECONDARY_ENGINE_ATTRIBUTE = '{"secondary table attr": "t1"}';
DROP TABLE t1;
CREATE TABLE t1(i INT, j INT, INDEX jix (j)) ENGINE=MYISAM;
ALTER TABLE t1 COMMENT 'A comment', ALGORITHM=INPLACE;
ALTER TABLE t1 SECONDARY_ENGINE_ATTRIBUTE='{"secondary column attr": "i"}', MODIFY COLUMN j INT ENGINE_ATTRIBUTE = '{"column attr": "j"}'        SECONDARY_ENGINE_ATTRIBUTE='{"secondary column attr": "j"}', DROP INDEX jix, ADD INDEX jix (i) ENGINE_ATTRIBUTE='{"index attr": "index on j"}'        SECONDARY_ENGINE_ATTRIBUTE='{"secondary index attr": "index on j"}', ENGINE_ATTRIBUTE = '{"table attr":"t1"}'        SECONDARY_ENGINE_ATTRIBUTE = '{"secondary table attr": "t1"}';
DROP TABLE t1;
CREATE TABLE t1(i INT, j INT) ENGINE=MYISAM;
ALTER TABLE t1 COMMENT 'A comment', ALGORITHM=INSTANT;
ALTER TABLE t1 ENGINE_ATTRIBUTE='{"table algo": "inplace"}', ALGORITHM=INSTANT;
ALTER TABLE t1 MODIFY COLUMN i INT COMMENT 'Modified column with comment', ALGORITHM=INSTANT;
ALTER TABLE t1 MODIFY COLUMN i INT ENGINE_ATTRIBUTE='{"modify column algo": "inplace"}', ALGORITHM=INSTANT;
ALTER TABLE t1 CHANGE COLUMN i mm INT COMMENT 'Changed column with comment', ALGORITHM=INSTANT;
