SET @old_log_bin_trust_function_creators= @@global.log_bin_trust_function_creators;
SET GLOBAL log_bin_trust_function_creators = 1;
set @orig_sql_mode_session= @@SESSION.sql_mode;
set @orig_sql_mode_global= @@GLOBAL.sql_mode;
SET NAMES binary;
flush privileges;
flush privileges;
flush privileges;
flush privileges;
create table t1 (a int);
flush privileges;
drop table t1;
create table t1 (abcdefghijklmnopqrstuvwxyz int);
drop table t1;
select 1;
flush privileges;
flush privileges;
create user test6123 identified by 'magic123';
create database mysqltest1;
grant usage on mysqltest1.* to test6123;
drop database mysqltest1;
flush privileges;
create table t1 (a int);
set sql_mode=ansi_quotes;
set sql_mode=default;
set sql_quote_show_create=0;
set sql_mode="ansi_quotes";
set sql_quote_show_create=1;
set sql_mode="";
drop table t1;
SET NAMES koi8r;
