drop view if exists v1;
drop table if exists t1,t4;
create table t4 ( pk_col int auto_increment primary key, a1 char(64), a2 char(64), b char(16), c char(16) not null, d char(16), dummy char(64) default ' ' ) engine=innodb;
create index idx12672_0 on t4 (a1);
create index idx12672_1 on t4 (a1,a2,b,c);
create index idx12672_2 on t4 (a1,a2,b);
analyze table t4;
select distinct a1 from t4 where pk_col not in (1,2,3,4);
drop table t4;
create table t1 ( a varchar(30), b varchar(30), primary key(a), key(b) ) engine=innodb;
select distinct a from t1;
drop table t1;
create table t1(a int, key(a)) engine=innodb;
insert into t1 values(1);
select a, count(a) from t1 group by a with rollup;
drop table t1;
create table t1 (f1 int, f2 char(1), primary key(f1,f2)) charset utf8mb4 engine=innodb stats_persistent=0;
insert into t1 values ( 1,"e"),(2,"a"),( 3,"c"),(4,"d");
alter table t1 drop primary key, add primary key (f2, f1);
explain select distinct f1 a, f1 b from t1;
explain select distinct f1, f2 from t1;
drop table t1;
create table t1(pk int primary key) engine=innodb;
create view v1 as select pk from t1 where pk < 20;
insert into t1 values (1), (2), (3), (4);
select distinct pk from v1;
insert into t1 values (5), (6), (7);
select distinct pk from v1;
drop view v1;
drop table t1;
CREATE TABLE t1 (a CHAR(1), b CHAR(1), PRIMARY KEY (a,b)) charset utf8mb4 ENGINE=InnoDB;
INSERT INTO t1 VALUES ('a', 'b'), ('c', 'd');
EXPLAIN SELECT COUNT(DISTINCT a) FROM t1 WHERE b = 'b';
SELECT COUNT(DISTINCT a) FROM t1 WHERE b = 'b';
DROP TABLE t1;
CREATE TABLE t1 (a CHAR(1) NOT NULL, b CHAR(1) NOT NULL, UNIQUE KEY (a,b)) charset utf8mb4 ENGINE=InnoDB;
INSERT INTO t1 VALUES ('a', 'b'), ('c', 'd');
EXPLAIN SELECT COUNT(DISTINCT a) FROM t1 WHERE b = 'b';
SELECT COUNT(DISTINCT a) FROM t1 WHERE b = 'b';
DROP TABLE t1;
CREATE TABLE t0 ( i1 INTEGER NOT NULL );
INSERT INTO t0 VALUES (1),(2),(3),(4),(5),(6),(7),(8),(9),(10), (11),(12),(13),(14),(15),(16),(17),(18),(19),(20), (21),(22),(23),(24),(25),(26),(27),(28),(29),(30);
CREATE TABLE t1 ( c1 CHAR(1) NOT NULL, i1 INTEGER NOT NULL, i2 INTEGER NOT NULL, UNIQUE KEY k1 (c1,i2) ) charset utf8mb4 ENGINE=InnoDB;
INSERT INTO t1 SELECT 'A',i1,i1 FROM t0;
INSERT INTO t1 SELECT 'B',i1,i1 FROM t0;
INSERT INTO t1 SELECT 'C',i1,i1 FROM t0;
INSERT INTO t1 SELECT 'D',i1,i1 FROM t0;
INSERT INTO t1 SELECT 'E',i1,i1 FROM t0;
INSERT INTO t1 SELECT 'F',i1,i1 FROM t0;
CREATE TABLE t2 ( c1 CHAR(1) NOT NULL, i1 INTEGER NOT NULL, i2 INTEGER NOT NULL, UNIQUE KEY k2 (c1,i1,i2) ) charset utf8mb4 ENGINE=InnoDB;
INSERT INTO t2 SELECT 'A',i1,i1 FROM t0;
INSERT INTO t2 SELECT 'B',i1,i1 FROM t0;
INSERT INTO t2 SELECT 'C',i1,i1 FROM t0;
INSERT INTO t2 SELECT 'D',i1,i1 FROM t0;
INSERT INTO t2 SELECT 'E',i1,i1 FROM t0;
INSERT INTO t2 SELECT 'F',i1,i1 FROM t0;
ANALYZE TABLE t1;
ANALYZE TABLE t2;
set optimizer_trace_max_mem_size=1048576;
set @@session.optimizer_trace='enabled=on';
set end_markers_in_json=on;
EXPLAIN SELECT c1, max(i2) FROM t1 WHERE (c1 = 'C' AND i2 = 17) OR ( c1 = 'F') GROUP BY c1;
SELECT c1, max(i2) FROM t1 WHERE (c1 = 'C' AND i2 = 17) OR ( c1 = 'F') GROUP BY c1;
SELECT TRACE RLIKE 'minmax_keypart_in_disjunctive_query' AS OK FROM INFORMATION_SCHEMA.OPTIMIZER_TRACE;
EXPLAIN SELECT c1, max(i2) FROM t1 WHERE (c1 = 'C' OR ( c1 = 'F' AND i2 = 17)) GROUP BY c1;
SELECT c1, max(i2) FROM t1 WHERE (c1 = 'C' OR ( c1 = 'F' AND i2 = 17)) GROUP BY c1;
SELECT TRACE RLIKE 'minmax_keypart_in_disjunctive_query' AS OK FROM INFORMATION_SCHEMA.OPTIMIZER_TRACE;
EXPLAIN SELECT c1, max(i2) FROM t1 WHERE (c1 = 'C' OR c1 = 'F' ) AND ( i2 = 17 ) GROUP BY c1;
SELECT c1, max(i2) FROM t1 WHERE (c1 = 'C' OR c1 = 'F' ) AND ( i2 = 17 ) GROUP BY c1;
SELECT TRACE RLIKE 'minmax_keypart_in_disjunctive_query' AS OK FROM INFORMATION_SCHEMA.OPTIMIZER_TRACE;
EXPLAIN SELECT c1, max(i2) FROM t1  WHERE ((c1 = 'C' AND (i2 = 40 OR i2 = 30)) OR ( c1 = 'F' AND (i2 = 40 ))) GROUP BY c1;
SELECT c1, max(i2) FROM t1  WHERE ((c1 = 'C' AND (i2 = 40 OR i2 = 30)) OR ( c1 = 'F' AND (i2 = 40 ))) GROUP BY c1;
SELECT TRACE RLIKE 'minmax_keypart_in_disjunctive_query' AS OK FROM INFORMATION_SCHEMA.OPTIMIZER_TRACE;
EXPLAIN SELECT c1, i1, max(i2) FROM t2 WHERE (c1 = 'C' OR ( c1 = 'F' AND i1 < 35)) AND ( i2 = 17 ) GROUP BY c1,i1;
SELECT c1, i1, max(i2) FROM t2 WHERE (c1 = 'C' OR ( c1 = 'F' AND i1 < 35)) AND ( i2 = 17 ) GROUP BY c1,i1;
SELECT TRACE RLIKE 'minmax_keypart_in_disjunctive_query' AS OK FROM INFORMATION_SCHEMA.OPTIMIZER_TRACE;
EXPLAIN SELECT c1, i1, max(i2) FROM t2  WHERE (((c1 = 'C' AND i1 < 40) OR ( c1 = 'F' AND i1 < 35)) AND ( i2 = 17 )) GROUP BY c1,i1;
SELECT c1, i1, max(i2) FROM t2  WHERE (((c1 = 'C' AND i1 < 40) OR ( c1 = 'F' AND i1 < 35)) AND ( i2 = 17 )) GROUP BY c1,i1;
SELECT TRACE RLIKE 'minmax_keypart_in_disjunctive_query' AS OK FROM INFORMATION_SCHEMA.OPTIMIZER_TRACE;
EXPLAIN SELECT c1, i1, max(i2) FROM t2  WHERE ((c1 = 'C' AND i1 < 40) OR ( c1 = 'F' AND i1 < 35) OR ( i2 = 17 )) GROUP BY c1,i1;
SELECT c1, i1, max(i2) FROM t2  WHERE ((c1 = 'C' AND i1 < 40) OR ( c1 = 'F' AND i1 < 35) OR ( i2 = 17 )) GROUP BY c1,i1;
SELECT TRACE RLIKE 'minmax_keypart_in_disjunctive_query' AS OK FROM INFORMATION_SCHEMA.OPTIMIZER_TRACE;
SET optimizer_trace_max_mem_size=DEFAULT;
SET optimizer_trace=DEFAULT;
SET end_markers_in_json=DEFAULT;
DROP TABLE t0,t1,t2;
CREATE TABLE t1 ( pk_col INT AUTO_INCREMENT PRIMARY KEY, a1 CHAR(64), KEY a1_idx (a1) ) charset utf8mb4 ENGINE=INNODB;
INSERT INTO t1 (a1) VALUES ('a'),('a'),('a'),('a'), ('a');
CREATE TABLE t2 ( pk_col1 INT NOT NULL, pk_col2 INT NOT NULL, a1 CHAR(64), a2 CHAR(64), PRIMARY KEY(pk_col1, pk_col2), KEY a1_idx (a1), KEY a1_a2_idx (a1, a2) ) charset utf8mb4 ENGINE=INNODB;
INSERT INTO t2 (pk_col1, pk_col2, a1, a2) VALUES (1,1,'a','b'),(1,2,'a','b'), (1,3,'a','c'),(1,4,'a','c'), (2,1,'a','d');
ANALYZE TABLE t1;
ANALYZE TABLE t2;
EXPLAIN SELECT DISTINCT a1 FROM t1 WHERE (pk_col = 2 OR pk_col = 22) AND a1 = 'a';
SELECT DISTINCT a1 FROM t1 WHERE (pk_col = 2 OR pk_col = 22) AND a1 = 'a';
EXPLAIN SELECT COUNT(DISTINCT a1) FROM t1 GROUP BY a1,pk_col;
SELECT COUNT(DISTINCT a1) FROM t1 GROUP BY a1,pk_col;
EXPLAIN SELECT COUNT(DISTINCT a1) FROM t2 GROUP BY a1,pk_col1;
SELECT COUNT(DISTINCT a1) FROM t2 GROUP BY a1,pk_col1;
EXPLAIN SELECT COUNT(DISTINCT a1) FROM t2 GROUP BY a1,a2;
SELECT COUNT(DISTINCT a1) FROM t2 GROUP BY a1,a2;
SET @optimizer_switch_save=@@optimizer_switch;
SET @@optimizer_switch= "use_index_extensions=off";
EXPLAIN SELECT DISTINCT a1 FROM t1 WHERE (pk_col = 2 OR pk_col = 22) AND a1 = 'a';
SELECT DISTINCT a1 FROM t1 WHERE (pk_col = 2 OR pk_col = 22) AND a1 = 'a';
EXPLAIN SELECT COUNT(DISTINCT a1) FROM t1 GROUP BY a1,pk_col;
SELECT COUNT(DISTINCT a1) FROM t1 GROUP BY a1,pk_col;
EXPLAIN SELECT COUNT(DISTINCT a1) FROM t2 GROUP BY a1,pk_col1;
SELECT COUNT(DISTINCT a1) FROM t2 GROUP BY a1,pk_col1;
EXPLAIN SELECT COUNT(DISTINCT a1) FROM t2 GROUP BY a1,a2;
SELECT COUNT(DISTINCT a1) FROM t2 GROUP BY a1,a2;
SET @@optimizer_switch= @optimizer_switch_save;
DROP TABLE t1, t2;
CREATE TABLE t1 ( id int NOT NULL, c1 int NOT NULL, c2 int, PRIMARY KEY(id), INDEX c1_c2_idx(c1, c2));
INSERT INTO t1 (id, c1, c2) VALUES (1,1,1), (2,2,2), (10,10,1), (11,10,8), (12,10,1), (13,10,2);
ANALYZE TABLE t1;
EXPLAIN SELECT DISTINCT c1 FROM t1 WHERE EXISTS (SELECT * FROM DUAL WHERE (c2 = 2));
EXPLAIN SELECT DISTINCT c1 FROM t1 WHERE 1 IN (2, (SELECT 1 FROM DUAL WHERE (c2 = 2)), 3);
EXPLAIN SELECT DISTINCT c1 FROM t1 WHERE c2 = 2;
EXPLAIN SELECT DISTINCT c1 FROM t1 IGNORE INDEX (c1_c2_idx) WHERE EXISTS (SELECT * FROM DUAL WHERE (c2 = 2));
EXPLAIN SELECT DISTINCT c1 FROM t1 IGNORE INDEX (c1_c2_idx) WHERE 1 IN (2, (SELECT 1 FROM DUAL WHERE (c2 = 2)), 3);
SET optimizer_trace="enabled=on";
SELECT DISTINCT c1 FROM t1 WHERE EXISTS (SELECT * FROM DUAL WHERE (c2 = 2));
