DROP TABLE IF EXISTS t1;
CREATE TABLE t1 ( key1 INT NOT NULL, key2 INT NOT NULL, key3 INT NOT NULL, key4 INT NOT NULL, key5 INT, key6 INT, key7 INT NOT NULL, key8 INT NOT NULL, INDEX i1(key1), INDEX i2(key2), INDEX i3(key3), INDEX i4(key4), INDEX i5(key5), INDEX i6(key6) );
INSERT INTO t1 VALUES ( 1,1,1,1,1,1,1,1),(2,2,2,2,2,2,2,2);
set @d=2;
INSERT INTO t1 SELECT key1+@d, key2+@d, key3+@d, key4+@d, key5+@d, key6+@d, key7+@d, key8+@d FROM t1;
set @d=@d*2;
INSERT INTO t1 SELECT key1+@d, key2+@d, key3+@d, key4+@d, key5+@d, key6+@d, key7+@d, key8+@d FROM t1;
set @d=@d*2;
INSERT INTO t1 SELECT key1+@d, key2+@d, key3+@d, key4+@d, key5+@d, key6+@d, key7+@d, key8+@d FROM t1;
set @d=@d*2;
INSERT INTO t1 SELECT key1+@d, key2+@d, key3+@d, key4+@d, key5+@d, key6+@d, key7+@d, key8+@d FROM t1;
set @d=@d*2;
INSERT INTO t1 SELECT key1+@d, key2+@d, key3+@d, key4+@d, key5+@d, key6+@d, key7+@d, key8+@d FROM t1;
set @d=@d*2;
INSERT INTO t1 SELECT key1+@d, key2+@d, key3+@d, key4+@d, key5+@d, key6+@d, key7+@d, key8+@d FROM t1;
set @d=@d*2;
INSERT INTO t1 SELECT key1+@d, key2+@d, key3+@d, key4+@d, key5+@d, key6+@d, key7+@d, key8+@d FROM t1;
set @d=@d*2;
INSERT INTO t1 SELECT key1+@d, key2+@d, key3+@d, key4+@d, key5+@d, key6+@d, key7+@d, key8+@d FROM t1;
set @d=@d*2;
INSERT INTO t1 SELECT key1+@d, key2+@d, key3+@d, key4+@d, key5+@d, key6+@d, key7+@d, key8+@d FROM t1;
set @d=@d*2;
INSERT INTO t1 SELECT key1+@d, key2+@d, key3+@d, key4+@d, key5+@d, key6+@d, key7+@d, key8+@d FROM t1;
set @d=@d*2;
set @d=5;
INSERT INTO t1 VALUES (key1+@d, key2+@d, key3+@d, key4+@d, key5+@d, NULL, key7+@d, key8+@d);
set @d=@d*2;
INSERT INTO t1 VALUES (key1+@d, key2+@d, key3+@d, key4+@d, key5+@d, NULL, key7+@d, key8+@d);
set @d=@d*2;
INSERT INTO t1 VALUES (key1+@d, key2+@d, key3+@d, key4+@d, key5+@d, NULL, key7+@d, key8+@d);
set @d=@d*2;
INSERT INTO t1 VALUES (key1+@d, key2+@d, key3+@d, key4+@d, key5+@d, NULL, key7+@d, key8+@d);
set @d=@d*2;
INSERT INTO t1 VALUES (key1+@d, key2+@d, key3+@d, key4+@d, key5+@d, NULL, key7+@d, key8+@d);
set @d=@d*2;
set @d=6;
INSERT INTO t1 VALUES (key1+@d, key2+@d, key3+@d, key4+@d, NULL, key6+@d, key7+@d, key8+@d);
set @d=@d*2;
INSERT INTO t1 VALUES (key1+@d, key2+@d, key3+@d, key4+@d, NULL, key6+@d, key7+@d, key8+@d);
set @d=@d*2;
INSERT INTO t1 VALUES (key1+@d, key2+@d, key3+@d, key4+@d, NULL, key6+@d, key7+@d, key8+@d);
set @d=@d*2;
INSERT INTO t1 VALUES (key1+@d, key2+@d, key3+@d, key4+@d, NULL, key6+@d, key7+@d, key8+@d);
set @d=@d*2;
ANALYZE TABLE t1;
DROP TABLE IF EXISTS t2;
CREATE TABLE t2 LIKE t1;
INSERT INTO t2 VALUES (rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6);
INSERT INTO t2 VALUES (rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6);
INSERT INTO t2 VALUES (rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6);
INSERT INTO t2 VALUES (rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6);
INSERT INTO t2 VALUES (rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6);
INSERT INTO t2 VALUES (rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6);
INSERT INTO t2 VALUES (rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6);
INSERT INTO t2 VALUES (rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6);
INSERT INTO t2 VALUES (rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6);
INSERT INTO t2 VALUES (rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6, rand()*6);
ANALYZE TABLE t2;
EXPLAIN REPLACE INTO t2 SELECT * FROM t1 WHERE key3=1025 OR key5 IS NULL;
SELECT COUNT(*) FROM t2;
REPLACE INTO t2 SELECT * FROM t1 WHERE key3=1025 OR key5 IS NULL;
ANALYZE TABLE t2;;
SELECT COUNT(*) FROM t2;
EXPLAIN REPLACE INTO t2 SELECT * FROM t1 WHERE key1=48 OR key4=2 OR key6=3;
SELECT COUNT(*) FROM t2;
REPLACE INTO t2 SELECT * FROM t1 WHERE key1=48 OR key4=2 OR key6=3;
ANALYZE TABLE t2;;
SELECT COUNT(*) FROM t2;
EXPLAIN REPLACE INTO t2 SELECT * FROM t1 WHERE key1<2 OR key2<3;
SELECT COUNT(*) FROM t2;
REPLACE INTO t2 SELECT * FROM t1 WHERE key1<2 OR key2<3;
ANALYZE TABLE t2;;
SELECT COUNT(*) FROM t2;
EXPLAIN REPLACE INTO t2 SELECT * FROM t1 WHERE (key1>30 AND key1<35) OR (key2>32 AND key2<40);
SELECT COUNT(*) FROM t2;
REPLACE INTO t2 SELECT * FROM t1 WHERE (key1>30 AND key1<35) OR (key2>32 AND key2<40);
ANALYZE TABLE t2;;
SELECT COUNT(*) FROM t2;
EXPLAIN REPLACE INTO t2 SELECT * FROM t1 IGNORE INDEX(i2) WHERE key1<2 OR key2<3;
SELECT COUNT(*) FROM t2;
REPLACE INTO t2 SELECT * FROM t1 IGNORE INDEX(i2) WHERE key1<2 OR key2<3;
ANALYZE TABLE t2;;
SELECT COUNT(*) FROM t2;
INSERT INTO t1 VALUES (42,42,42,42,3,3,3,3),(4,4,6,6,6,6,4,4);
ANALYZE TABLE t1;
EXPLAIN  REPLACE INTO t2 SELECT * FROM t1 USE INDEX(i6,i3) WHERE (key4=42 AND key6=3) OR (key1=4 AND key3=6);
SELECT COUNT(*) FROM t2;
REPLACE INTO t2 SELECT * FROM t1 USE INDEX(i6,i3) WHERE (key4=42 AND key6=3) OR (key1=4 AND key3=6);
ANALYZE TABLE t2;;
SELECT COUNT(*) FROM t2;
EXPLAIN REPLACE INTO t2 SELECT * FROM t1 FORCE INDEX(i1,i2) WHERE (key1>1 OR key2>2);
SELECT COUNT(*) FROM t2;
REPLACE INTO t2 SELECT * FROM t1 FORCE INDEX(i1,i2) WHERE (key1>1 OR key2>2);
ANALYZE TABLE t2;;
SELECT COUNT(*) FROM t2;
INSERT INTO t1 VALUES (42,42,42,42,3,3,3,3),(4,4,6,6,6,6,4,4);
ANALYZE TABLE t1;
EXPLAIN INSERT INTO t2 SELECT * FROM t1 WHERE (key4=42 AND key6=3) OR (key1=4 AND key3=6) AND key5<>50;
SELECT COUNT(*) FROM t2;
INSERT INTO t2 SELECT * FROM t1 WHERE (key4=42 AND key6=3) OR (key1=4 AND key3=6) AND key5<>50;
ANALYZE TABLE t2;;
SELECT COUNT(*) FROM t2;
EXPLAIN INSERT INTO t2 SELECT * FROM t1 WHERE key2=10 OR key3=3 OR key4 <=> null;
SELECT COUNT(*) FROM t2;
INSERT INTO t2 SELECT * FROM t1 WHERE key2=10 OR key3=3 OR key4 <=> null                   ;
ANALYZE TABLE t2;;
SELECT COUNT(*) FROM t2;
EXPLAIN INSERT INTO t2 SELECT * FROM t1 IGNORE INDEX(i1) WHERE key1<2 OR key2<3;
SELECT COUNT(*) FROM t2;
INSERT INTO t2 SELECT * FROM t1 IGNORE INDEX(i1) WHERE key1<2 OR key2<3;
ANALYZE TABLE t2;;
SELECT COUNT(*) FROM t2;
EXPLAIN INSERT INTO t2 SELECT * FROM t1 USE INDEX(i5,i6) WHERE (key1<2 OR key2<2) AND (key3<3 OR key4<3) AND (key5<5 OR key6<5);;
SELECT COUNT(*) FROM t2;
INSERT INTO t2 SELECT * FROM t1 USE INDEX(i5,i6) WHERE (key1<2 OR key2<2) AND (key3<3 OR key4<3) AND (key5<5 OR key6<5);;
ANALYZE TABLE t2;;
SELECT COUNT(*) FROM t2;
EXPLAIN INSERT INTO t2 SELECT * FROM t1 FORCE INDEX(i4,i5) WHERE (key4>3 OR key5>5);
SELECT COUNT(*) FROM t2;
INSERT INTO t2 SELECT * FROM t1 FORCE INDEX(i4,i5) WHERE (key4>3 OR key5>5);
SELECT COUNT(*) FROM t2;
DROP TABLE IF EXISTS t1;
