SET lock_wait_timeout= 1;
SET autocommit= 0;
CREATE USER 'user1'@'localhost';
CREATE USER 'user2'@'localhost';
CREATE USER 'user3'@'localhost';
GRANT all ON *.* TO 'user1'@'localhost';
GRANT all ON *.* TO 'user2'@'localhost';
GRANT all ON *.* TO 'user3'@'localhost';
SET lock_wait_timeout= 1;
SET autocommit= 0;
LOCK INSTANCE FOR BACKUP;
CREATE TABLE testtable_11 (c1 int, c2 varchar(10));
CREATE TEMPORARY TABLE temptable_11 (tt1 int);
SET lock_wait_timeout= 1;
SET autocommit= 0;
CREATE TABLE testtable_21 (c1 int, c2 varchar(10));
CREATE TEMPORARY TABLE temptable_21 (tt1 int);
SET lock_wait_timeout= 1;
SET autocommit= 0;
CREATE TABLE testtable_31 (c1 int, c2 varchar(10));
CREATE TEMPORARY TABLE temptable_31 (tt1 int);
UNLOCK INSTANCE;
CREATE TABLE testtable_12 (c1 int, c2 varchar(10));
CREATE TABLE testtable_21 (c1 int, c2 varchar(10));
CREATE TABLE testtable_31 (c1 int, c2 varchar(10));
LOCK INSTANCE FOR BACKUP;
CREATE TABLE testtable_12 (c1 int, c2 varchar(10));
CREATE TABLE testtable_31 (c1 int, c2 varchar(10));
LOCK INSTANCE FOR BACKUP;
CREATE TABLE testtable_1 (c1 int, c2 varchar(10));
DROP TABLE IF EXISTS testtable_11;
DROP TABLE IF EXISTS testtable_12;
DROP TABLE IF EXISTS testtable_21;
DROP TABLE IF EXISTS testtable_31;
UNLOCK INSTANCE;
DROP TABLE IF EXISTS testtable_11;
DROP TABLE IF EXISTS testtable_12;
UNLOCK INSTANCE;
DROP TABLE IF EXISTS testtable_11;
DROP TABLE IF EXISTS testtable_12;
DROP TABLE IF EXISTS testtable_21;
DROP TABLE IF EXISTS testtable_31;
DROP USER 'user1'@'localhost';
DROP USER 'user2'@'localhost';
DROP USER 'user3'@'localhost';
