set @orig_sql_mode_session= @@SESSION.sql_mode;
set @orig_sql_mode_global= @@GLOBAL.sql_mode;
create database d1;
create user 'sample'@'localhost' identified by 'password';
grant all on d1.* to 'sample'@'localhost';
flush privileges;
select database();
create database d2;
create database D1;
drop user 'sample'@'localhost';
drop database if exists d1;
CREATE DATABASE d1;
USE d1;
CREATE TABLE T1(f1 INT);
CREATE TABLE t1(f1 INT);
select * from t1;
select * from T1;
select * from information_schema.table_privileges;
DROP DATABASE d1;
USE test;
CREATE DATABASE db1;
USE db1;
CREATE PROCEDURE p1() BEGIN END;
CREATE FUNCTION f1(i INT) RETURNS INT RETURN i+1;
call p1();
call P1();
select f1(1);
call p1();
call P1();
select f1(1);
DROP FUNCTION f1;
DROP PROCEDURE p1;
DROP DATABASE db1;
use test;
set GLOBAL sql_mode= @orig_sql_mode_global;
set SESSION sql_mode= @orig_sql_mode_session;
CREATE TABLE t1(a INT);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1 FOR EACH ROW SET new.a= 1;
RENAME TABLE t1 TO T1;
ALTER TABLE T1 RENAME t1;
DROP TABLE t1;
