DROP TABLE IF EXISTS t1, `t``1`, `t 1`;
drop view if exists v1;
drop database if exists client_test_db;
SET @have_ndb= (select count(engine) from information_schema.engines where engine='ndbcluster');
SET @create_cmd="CREATE TABLE mysql.ndb_binlog_index (i INTEGER PRIMARY KEY)   ENGINE=INNODB STATS_PERSISTENT=0";
SET @drop_cmd="DROP TABLE mysql.ndb_binlog_index";
SET @create = IF(@have_ndb = 0, @create_cmd, 'SET @dummy = 0');
SET @drop = IF(@have_ndb = 0, @drop_cmd, 'SET @dummy = 0');
PREPARE create_stmt FROM @create;
PREPARE drop_stmt FROM @drop;
EXECUTE create_stmt;
DROP PREPARE create_stmt;
EXECUTE drop_stmt;
DROP PREPARE drop_stmt;
create view v1 as select * from information_schema.routines;
check table v1, information_schema.routines;
drop view v1;
DROP DATABASE IF EXISTS b12688860_db;
CREATE DATABASE b12688860_db;
DROP DATABASE b12688860_db;
CREATE USER 'user_with_length_32_abcdefghijkl'@'localhost';
GRANT ALL ON *.* TO 'user_with_length_32_abcdefghijkl'@'localhost';
DROP USER 'user_with_length_32_abcdefghijkl'@'localhost';
