SET @old_concurrent_insert = @@global.concurrent_insert;
SET @@global.concurrent_insert = 0;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (a DECIMAL(64, 20));
INSERT INTO t1 VALUES ("1234567890123456789012345678901234567890"), ("0987654321098765432109876543210987654321");
SET @orig_table_name = CONCAT('test.t1', '_orig');
ALTER TABLE test.t1 RENAME to test.t1_orig;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.t1 ORDER BY `a` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-t1';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.t1_orig ORDER BY `a` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-t1_orig';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE test.t1, test.t1_orig;
CREATE TABLE t1 (a DECIMAL(10,5), b FLOAT);
INSERT INTO t1 VALUES (1.2345, 2.3456);
INSERT INTO t1 VALUES ('1.2345', 2.3456);
INSERT INTO t1 VALUES ("1.2345", 2.3456);
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ANSI_QUOTES';
INSERT INTO t1 VALUES (1.2345, 2.3456);
INSERT INTO t1 VALUES ('1.2345', 2.3456);
INSERT INTO t1 VALUES ("1.2345", 2.3456);
SET SQL_MODE=@OLD_SQL_MODE;
SET @orig_table_name = CONCAT('test.t1', '_orig');
ALTER TABLE test.t1 RENAME to test.t1_orig;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.t1 ORDER BY `a`,`b` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-t1';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.t1_orig ORDER BY `a`,`b` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-t1_orig';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE test.t1, test.t1_orig;
CREATE TABLE t1 (a  VARCHAR(255)) DEFAULT CHARSET koi8r;
INSERT INTO t1  VALUES (_koi8r x'C1C2C3C4C5'), (NULL);
SET @orig_table_name = CONCAT('test.t1', '_orig');
ALTER TABLE test.t1 RENAME to test.t1_orig;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.t1 ORDER BY `a` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-t1';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.t1_orig ORDER BY `a` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-t1_orig';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE test.t1, test.t1_orig;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT);
INSERT INTO t1 VALUES (1),(2),(3);
INSERT INTO t2 VALUES (4),(5),(6);
SET @orig_table_name = CONCAT('test.t2', '_orig');
ALTER TABLE test.t2 RENAME to test.t2_orig;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.t2 ORDER BY `a` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-t2';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.t2_orig ORDER BY `a` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-t2_orig';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE test.t2, test.t2_orig;
DROP TABLE t1;
CREATE TABLE t1 (`b` blob);
INSERT INTO `t1` VALUES (0x602010000280100005E71A);
SET @orig_table_name = CONCAT('test.t1', '_orig');
ALTER TABLE test.t1 RENAME to test.t1_orig;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.t1 ORDER BY `b` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-t1';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.t1_orig ORDER BY `b` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-t1_orig';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE test.t1, test.t1_orig;
SET @@global.concurrent_insert = @old_concurrent_insert;
