SET @old_log_output=          @@global.log_output;
SET @old_slow_query_log=      @@global.slow_query_log;
SET @old_slow_query_log_file= @@global.slow_query_log_file;
SET GLOBAL slow_query_log_file= '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/log/slow_query_temp.log';
SET GLOBAL log_output=       'FILE';
SET GLOBAL slow_query_log=   'ON';
SET SESSION long_query_time=  0;
SHOW VARIABLES LIKE "%long_query_time%";
SHOW VARIABLES LIKE "%long_query_time%";
SHOW VARIABLES LIKE "%long_query_time%";
SHOW VARIABLES LIKE "%long_query_time%";
SHOW VARIABLES LIKE "%long_query_time%";
SELECT 1;
SELECT 1;
SELECT 1;
SELECT 1;
SET GLOBAL  log_output=         @old_log_output;
SET GLOBAL  slow_query_log=     @old_slow_query_log;
SET GLOBAL  slow_query_log_file=@old_slow_query_log_file;
