SET sql_mode='NO_ENGINE_SUBSTITUTION';
CREATE DATABASE db1_std_csets;
USE db1_std_csets;
SET NAMES cp1251;
CREATE TABLE t_cp1251 (a VARCHAR(30) CHARACTER SET cp1251 COLLATE cp1251_bin) CHARACTER SET cp1251 COLLATE cp1251_bin;
INSERT INTO t_cp1251 VALUES (_cp1251'MYSQLPUMP'), (_cp1251'cāt?기?會意');
SELECT HEX(a) , CHAR_LENGTH(a) FROM db1_std_csets.t_cp1251 ORDER BY 1;
DROP DATABASE db1_std_csets;
CREATE DATABASE db1_std_csets;
SET NAMES cp1251;
SELECT HEX(a) , CHAR_LENGTH(a) FROM db1_std_csets.t_cp1251 ORDER BY 1;
DROP DATABASE db1_std_csets;
SET sql_mode='NO_ENGINE_SUBSTITUTION';
CREATE DATABASE db1_std_csets;
USE db1_std_csets;
SET NAMES euckr;
CREATE TABLE t_euckr (a VARCHAR(30) CHARACTER SET euckr COLLATE euckr_bin) CHARACTER SET euckr COLLATE euckr_bin;
INSERT INTO t_euckr VALUES (_euckr'MYSQLPUMP'), (_euckr'cāt?기?會意');
SELECT HEX(a) , CHAR_LENGTH(a) FROM db1_std_csets.t_euckr ORDER BY 1;
DROP DATABASE db1_std_csets;
CREATE DATABASE db1_std_csets;
SET NAMES euckr;
SELECT HEX(a) , CHAR_LENGTH(a) FROM db1_std_csets.t_euckr ORDER BY 1;
DROP DATABASE db1_std_csets;
SET sql_mode='NO_ENGINE_SUBSTITUTION';
CREATE DATABASE db1_std_csets;
USE db1_std_csets;
SET NAMES eucjpms;
CREATE TABLE t_eucjpms (a VARCHAR(30) CHARACTER SET eucjpms COLLATE eucjpms_bin) CHARACTER SET eucjpms COLLATE eucjpms_bin;
INSERT INTO t_eucjpms VALUES (_eucjpms'MYSQLPUMP'), (_eucjpms'cāt?기?會意');
SELECT HEX(a) , CHAR_LENGTH(a) FROM db1_std_csets.t_eucjpms ORDER BY 1;
DROP DATABASE db1_std_csets;
CREATE DATABASE db1_std_csets;
SET NAMES eucjpms;
SELECT HEX(a) , CHAR_LENGTH(a) FROM db1_std_csets.t_eucjpms ORDER BY 1;
DROP DATABASE db1_std_csets;
SET sql_mode='NO_ENGINE_SUBSTITUTION';
CREATE DATABASE db1_std_csets;
USE db1_std_csets;
SET NAMES gb18030;
CREATE TABLE t_gb18030 (a VARCHAR(30) CHARACTER SET gb18030 COLLATE gb18030_bin) CHARACTER SET gb18030 COLLATE gb18030_bin;
INSERT INTO t_gb18030 VALUES (_gb18030'MYSQLPUMP'), (_gb18030'cāt?기?會意');
SELECT HEX(a) , CHAR_LENGTH(a) FROM db1_std_csets.t_gb18030 ORDER BY 1;
DROP DATABASE db1_std_csets;
CREATE DATABASE db1_std_csets;
SET NAMES gb18030;
SELECT HEX(a) , CHAR_LENGTH(a) FROM db1_std_csets.t_gb18030 ORDER BY 1;
DROP DATABASE db1_std_csets;
SET sql_mode='NO_ENGINE_SUBSTITUTION';
CREATE DATABASE db1_std_csets;
USE db1_std_csets;
SET NAMES cp932;
CREATE TABLE t_cp932 (a VARCHAR(30) CHARACTER SET cp932 COLLATE cp932_bin) CHARACTER SET cp932 COLLATE cp932_bin;
INSERT INTO t_cp932 VALUES (_cp932'MYSQLPUMP'), (_cp932'cāt?기?會意');
SELECT HEX(a) , CHAR_LENGTH(a) FROM db1_std_csets.t_cp932 ORDER BY 1;
DROP DATABASE db1_std_csets;
CREATE DATABASE db1_std_csets;
SET NAMES cp932;
SELECT HEX(a) , CHAR_LENGTH(a) FROM db1_std_csets.t_cp932 ORDER BY 1;
DROP DATABASE db1_std_csets;
SET sql_mode='NO_ENGINE_SUBSTITUTION';
CREATE DATABASE db1_ucs2_csets CHARACTER SET utf8;
USE db1_ucs2_csets;
SET NAMES utf8;
CREATE TABLE t_ucs2 (a CHAR(4) CHARACTER SET utf8) CHARACTER SET utf8;
LOAD DATA INFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/std_data/charset_utf8.txt' INTO TABLE t_ucs2;
ALTER TABLE t_ucs2 CHANGE a a CHAR(4) CHARACTER SET ucs2 COLLATE ucs2_bin;
SELECT COUNT(*) FROM t_ucs2;
RENAME TABLE t_ucs2 TO old_t_ucs2;
SELECT COUNT(*) FROM t_ucs2;
DROP DATABASE db1_ucs2_csets;
SET sql_mode='NO_ENGINE_SUBSTITUTION';
CREATE DATABASE db1_ucs2_csets CHARACTER SET utf8;
USE db1_ucs2_csets;
SET NAMES utf8;
CREATE TABLE t_ucs2 (a CHAR(4) CHARACTER SET utf8) CHARACTER SET utf8;
LOAD DATA INFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/std_data/charset_utf8.txt' INTO TABLE t_ucs2;
ALTER TABLE t_ucs2 CHANGE a a CHAR(4) CHARACTER SET ucs2 COLLATE ucs2_unicode_ci;
SELECT COUNT(*) FROM t_ucs2;
RENAME TABLE t_ucs2 TO old_t_ucs2;
SELECT COUNT(*) FROM t_ucs2;
DROP DATABASE db1_ucs2_csets;
SET sql_mode='NO_ENGINE_SUBSTITUTION';
CREATE DATABASE db1_utf8_csets CHARACTER SET utf8;
USE db1_utf8_csets;
CREATE TABLE t_utf8 (a CHAR(4) CHARACTER SET utf8 COLLATE utf8_bin) CHARACTER SET utf8 COLLATE utf8_bin;
LOAD DATA INFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/std_data/charset_utf8.txt' INTO TABLE t_utf8;
SELECT COUNT(*) FROM t_utf8;
RENAME TABLE t_utf8 TO old_t_utf8;
SELECT COUNT(*) FROM t_utf8;
DROP DATABASE db1_utf8_csets;
SET sql_mode='NO_ENGINE_SUBSTITUTION';
CREATE DATABASE db1_utf8_csets CHARACTER SET utf8;
USE db1_utf8_csets;
CREATE TABLE t_utf8 (a CHAR(4) CHARACTER SET utf8 COLLATE utf8_unicode_ci) CHARACTER SET utf8 COLLATE utf8_unicode_ci;
LOAD DATA INFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/std_data/charset_utf8.txt' INTO TABLE t_utf8;
SELECT COUNT(*) FROM t_utf8;
RENAME TABLE t_utf8 TO old_t_utf8;
SELECT COUNT(*) FROM t_utf8;
DROP DATABASE db1_utf8_csets;
SET sql_mode='NO_ENGINE_SUBSTITUTION';
SET NAMES utf8;
CREATE DATABASE `Êý¾Ý¿â`;
USE `Êý¾Ý¿â`;
CREATE TABLE ÔÁÂÌÉÃÁ (ÐÏÌÑ VARCHAR(30) CHARACTER SET cp1251 COLLATE cp1251_bulgarian_ci) CHARACTER SET cp1251 COLLATE cp1251_bulgarian_ci;
CREATE VIEW `±í¸ñ` AS SELECT _cp1251'×Ö¶ÎÒ»';
INSERT INTO ÔÁÂÌÉÃÁ VALUES (_cp1251'MYSQLPUMP'), (_cp1251'한글입력기');
SELECT HEX(ÐÏÌÑ) , CHAR_LENGTH(ÐÏÌÑ) FROM ÔÁÂÌÉÃÁ ORDER BY 1;
CREATE FUNCTION `straÃe` ( `饽紴缽菠` CHAR(20) CHARACTER SET cp1251 COLLATE cp1251_bulgarian_ci) RETURNS CHAR(50)  CHARACTER SET cp1251 DETERMINISTIC RETURN `饽紴缽菠`;
SELECT * FROM `±í¸ñ`;
SELECT `straÃe`(_cp1251'한글');
DROP DATABASE `Êý¾Ý¿â`;
SET NAMES utf8;
USE `Êý¾Ý¿â`;
SELECT HEX(ÐÏÌÑ) , CHAR_LENGTH(ÐÏÌÑ) FROM ÔÁÂÌÉÃÁ ORDER BY 1;
SELECT `straÃe`(_cp1251'한글');
SELECT * FROM `±í¸ñ`;
DROP DATABASE `Êý¾Ý¿â`;
SET sql_mode='NO_ENGINE_SUBSTITUTION';
SET NAMES utf8;
CREATE DATABASE `Êý¾Ý¿â`;
USE `Êý¾Ý¿â`;
