DROP TABLE IF EXISTS t1,t2,test1,test2;
CREATE TABLE t1 (a int);
INSERT INTO t1 VALUES (1),(2),(3);
CREATE TABLE t2 (a int, b int);
show tables;
select "--------------------" as "";
select "---- -v ------------" as "";
select "---- -v -v ---------" as "";
select "----- -t -----------" as "";
select "---- -v -t ---------" as "";
select "---- -v -v -t ------" as "";
DROP TABLE t1, t2;
DROP DATABASE IF EXISTS b12688860_db;
CREATE DATABASE b12688860_db;
CREATE TABLE b12688860_db.b12688860_tab (c1 INT);
DROP TABLE b12688860_db.b12688860_tab;
DROP DATABASE b12688860_db;
SET @OLD_SQL_MODE = @@SQL_MODE;
SET GLOBAL sql_mode = 'NO_BACKSLASH_ESCAPES';
SHOW GLOBAL VARIABLES LIKE 'sql_mode';
DROP TABLE IF EXISTS ```t1`,```t2`;
CREATE TABLE ```t1` (a int);
INSERT INTO ```t1` VALUES (1),(2),(3);
CREATE TABLE ```t2` (a int, b int);
show tables;
DROP TABLE ```t1`, ```t2`;
SET GLOBAL sql_mode = '';
SHOW GLOBAL VARIABLES LIKE 'sql_mode';
DROP TABLE IF EXISTS ```t1`,```t2`;
CREATE TABLE ```t1` (a int);
INSERT INTO ```t1` VALUES (1),(2),(3);
CREATE TABLE ```t2` (a int, b int);
show tables;
DROP TABLE ```t1`, ```t2`;
SET GLOBAL sql_mode = @OLD_SQL_MODE;
CREATE USER 'user_with_length_32_abcdefghijkl'@'localhost';
GRANT ALL ON *.* TO 'user_with_length_32_abcdefghijkl'@'localhost';
DROP USER 'user_with_length_32_abcdefghijkl'@'localhost';
