select otto from (select 1 as otto) as t1;
select otto from (select 1 as otto) as t1;
select friedrich from (select 1 as otto) as t1;
select otto from (select 1 as otto) as t1;
select friedrich from (select 1 as otto) as t1;
select otto from (select 1 as otto) as t1;
select 0 as "after_successful_stmt_errno" ;
select 1064 as "after_wrong_syntax_errno" ;
select 1064 as "after_let_var_equal_value" ;
set @my_var= 'abc' ;
select 0 as "after_set_var_equal_value" ;
select 1064 as "after_disable_warnings_command" ;
drop table if exists t1 ;
drop table if exists t1 ;
select 0 as "after_disable_warnings" ;
select 3 from t1 ;
select 1146 as "after_minus_masked" ;
select 3 from t1 ;
select 1146 as "after_!_masked" ;
select -1 as "after_let_errno_equal_value" ;
prepare stmt from "select 3 from t1" ;
select 1146 as "after_failing_prepare" ;
create table t1 ( f1 char(10));
prepare stmt from "select 3 from t1" ;
select 0 as "after_successful_prepare" ;
execute stmt;
select 0 as "after_successful_execute" ;
drop table t1;
execute stmt;
select 1146 as "after_failing_execute" ;
execute __stmt_;
select 1243 as "after_failing_execute" ;
deallocate prepare stmt;
select 0 as "after_successful_deallocate" ;
deallocate prepare __stmt_;
select 1243 as "after_failing_deallocate" ;
select 1064 as "after_--disable_abort_on_error" ;
select 3 from t1 ;
select 3 from t1 ;
select 3 from t1 ;
select 1146 as "after_!errno_masked_error" ;
select 1064 as "after_--enable_abort_on_error" ;
select 3 from t1 ;
garbage;
select 2;
select 3;
select 5;
select 3 from t1;
select 7;
select 5 from t1;
select "CASE" as "LOWER";
select "xyz" as name union select "abc" as name order by name desc;
DROP TABLE table_does_not_exist;
DROP TABLE table_does_not_exist;
DROP TABLE table_does_not_exist;
DROP TABLE table_does_not_exist;
CREATE TABLE t1 (a INT);
CREATE TABLE t1 (a INT);
CREATE TABLE t1 (a INT);
DROP TABLE t1;
create table t1 (a varchar(100)) charset utf8mb4;
insert into t1 values ('`select 42`');
insert into t1 values ('$dollar');
drop table t1;
SELECT '2 = outer loop variable after while' AS "";
SELECT '2 = outer loop variable before dec' AS "";
SELECT '1 = outer loop variable after dec' AS "";
SELECT '1 = outer loop variable after while' AS "";
SELECT '1 = outer loop variable before dec' AS "";
SELECT '0 = outer loop variable after dec' AS "";
SELECT * from nowhere;
SELECT * FROM nowhere else;
SELECT 'In loop' AS "";
SELECT 'In loop' AS "";
SELECT 'In loop' AS "";
SELECT 'In loop' AS "";
SELECT 'In loop' AS "";
SELECT 'In loop' AS "";
SELECT 'In loop' AS "";
SELECT 'In loop' AS "";
SELECT 'In loop' AS "";
select "a" as col1, "c" as col2;
select "a" as col1, "c" as col2;
select "a" as col1, "c" as col2;
select "a" as col1, "c" as col2;
show tables;
failing_statement;
failing_statement;
SELECT 1 as a;
select 1 as `a'b`, 2 as `a"b`;
select 'aaa\\','aa''a',"aa""a";
SET @utf8_message = CONVERT('Here comes a message' using utf8);
select @utf8_message as "" union select repeat(CONVERT('-' using utf8),char_length(@utf8_message));
select @utf8_message as "" union select repeat(CONVERT('-' using utf8),char_length(@utf8_message));
SET @utf8_message = CONVERT('"Here comes a very very long message that     - is longer then 80 characters    and     - consists of several lines"' using utf8);
select @utf8_message as "" union select repeat(CONVERT('-' using utf8),80);
SET @utf8_message = CONVERT('. Here comes a very very long message that .      - is longer then 80 characters    and .      - consists of several lines' using utf8);
select @utf8_message as "" union select repeat(CONVERT('-' using utf8),80);
drop table t1;
drop table t1;
drop table t1;
drop table t1;
