CREATE FUNCTION service_get_read_locks  RETURNS INT SONAME "locking_service.so";
CREATE FUNCTION service_get_write_locks RETURNS INT SONAME "locking_service.so";
CREATE FUNCTION service_release_locks   RETURNS INT SONAME "locking_service.so";
SELECT service_get_read_locks();
SELECT service_get_read_locks('negative');
SELECT service_get_read_locks('negative', 'lock1');
SELECT service_get_read_locks(         1, 'lock1', 'lock2', 0);
SELECT service_get_read_locks(        '', 'lock1', 'lock2', 0);
SELECT service_get_read_locks('negative',       1, 'lock2', 0);
SELECT service_get_write_locks();
SELECT service_get_write_locks('negative');
SELECT service_get_write_locks('negative', 'lock1');
SELECT service_get_write_locks(         1, 'lock1', 'lock2', 0);
SELECT service_get_write_locks(        '', 'lock1', 'lock2', 0);
SELECT service_get_write_locks('negative',       1, 'lock2', 0);
SELECT service_get_write_locks('negative',      '', 'lock2', 0);
SELECT service_get_write_locks('negative', 'lock1',       1, 0);
SELECT service_get_write_locks('negative', 'lock1',      '', 0);
SELECT service_get_write_locks('negative', 'lock1', 'lock2', 'hello');
SELECT service_release_locks();
SELECT service_release_locks('negative', 'hello');
SELECT service_release_locks(         1);
SELECT service_release_locks(        '');
UPDATE performance_schema.setup_instruments SET enabled = 'NO', timed = 'YES';
TRUNCATE TABLE performance_schema.events_waits_current;
TRUNCATE TABLE performance_schema.events_waits_history_long;
UPDATE performance_schema.setup_instruments SET enabled = 'YES' WHERE name = 'wait/lock/metadata/sql/mdl';
SELECT COUNT(*) = 0 AS expect_1 FROM performance_schema.metadata_locks WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT service_get_read_locks('pfs_check', 'lock1', 'lock2', 0);
SELECT service_get_write_locks('pfs_check', 'lock3', 'lock4', 0);
SELECT OBJECT_TYPE, OBJECT_SCHEMA, OBJECT_NAME, LOCK_TYPE, LOCK_DURATION, LOCK_STATUS FROM performance_schema.metadata_locks WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT service_release_locks('pfs_check');
SELECT COUNT(*) = 0 AS expect_1 FROM performance_schema.metadata_locks WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT service_get_write_locks("namespace1", "lock1", 60);
SELECT service_get_write_locks("namespace2", "lock1", "lock2", 60);
SELECT service_release_locks("namespace1");
SELECT service_release_locks("namespace2");
SELECT COUNT(*) = 0 AS expect_1 FROM performance_schema.metadata_locks WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT COUNT(*) = 0 AS expect_1 FROM performance_schema.events_waits_current WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT service_get_write_locks("namespace1", "lock1", "lock2", 60);
SELECT service_get_write_locks("namespace1", "lock1", 1);
SELECT service_get_write_locks("namespace1", "lock2", 1);
SELECT service_get_read_locks("namespace1", "lock1", 1);
SELECT service_get_write_locks("namespace1", "lock1", 0);
SELECT service_get_write_locks("namespace1", "lock2", 0);
SELECT service_get_read_locks("namespace1", "lock1", 0);
SELECT OBJECT_SCHEMA, OBJECT_NAME, OBJECT_TYPE, OPERATION FROM performance_schema.events_waits_history_long WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT COUNT(*) = 1 AS expect_1 FROM performance_schema.events_waits_current WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT service_get_write_locks("namespace1", "lock1", 60);
SELECT COUNT(*) = 1 AS expect_1 FROM information_schema.processlist WHERE state = 'Waiting for locking service lock';
SELECT OBJECT_SCHEMA, OBJECT_NAME, OBJECT_TYPE, OPERATION FROM performance_schema.events_waits_current WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT service_release_locks("namespace1");
SELECT COUNT(*) = 0 AS expect_1 FROM information_schema.processlist WHERE state = 'Waiting for locking service lock';
SELECT COUNT(*) = 1 AS expect_1 FROM performance_schema.events_waits_current WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT service_release_locks("namespace1");
SELECT service_get_write_locks('holder_name_space', 'first', 'middle', 'last', 1);
SELECT service_get_write_locks('holder_name_space', 'first', 'l2_1', 'l3_1', 0);
SELECT service_get_write_locks('holder_name_space', 'l1_2', 'middle', 'l3_2', 0);
SELECT service_get_write_locks('holder_name_space', 'l1_3', 'l2_3', 'last', 0);
SELECT object_schema, object_name, lock_type, lock_status FROM performance_schema.metadata_locks WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT service_release_locks("holder_name_space");
SELECT service_get_write_locks(RPAD('holder_name_space_', 64, 'a'), 'l1', 'l2', 'l3', 0) AS col1;
SELECT service_release_locks(RPAD('holder_name_space_', 64, 'a')) AS col1;
SELECT service_get_write_locks(RPAD('holder_name_space_', 65, 'a'), 'l1', 'l2', 'l3', 0) AS col1;
SELECT service_get_write_locks('holder_name_space', RPAD('l1_', 64, 'a'), RPAD('l2_', 64, 'a'), RPAD('l3_', 64, 'a'), 0) AS col1;
SELECT service_release_locks('holder_name_space') AS col1;
SELECT service_get_write_locks('holder_name_space', RPAD('l1_', 65, 'a'), 'l2_1', 'l3_1', 0) AS col1;
SELECT service_get_write_locks('holder_name_space', 'l1_2', RPAD('l2_', 65, 'a'), 'l3_2', 0) AS col1;
SELECT service_get_write_locks('holder_name_space', 'l1_3', 'l2_3', RPAD('l3_', 65, 'a'), 0) AS col1;
SELECT service_get_write_locks('holder_name_space', 'l1_1', 'l2_1', 'l3_1', 'l1_2', 'l2_2', 'l3_2', 'l1_3', 'l2_3', 'l3_3', 1) AS col1;
SELECT service_release_locks('holder_name_space') AS col1;
SELECT COUNT(*) = 0 AS expect_1 FROM performance_schema.metadata_locks WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT service_get_write_locks('holder_name_space', 'lock', 0) AS col1;
SELECT service_get_write_locks('holder_name_space', 'lock', 0) AS col1;
SELECT service_get_write_locks('holder_name_space ', 'lock', 0) AS col1;
SELECT service_release_locks('holder_name_space ') AS col1;
SELECT service_get_write_locks(' holder_name_space', 'lock', 0) AS col1;
SELECT service_release_locks(' holder_name_space') AS col1;
SELECT service_get_write_locks('holder_name_spac', 'lock', 0) AS col1;
SELECT service_release_locks('holder_name_spac') AS col1;
SELECT service_get_write_locks('older_name_space', 'lock', 0) AS col1;
SELECT service_release_locks('older_name_space') AS col1;
SELECT service_get_write_locks('holder_name_space', 'lock ', 0) AS col1;
SELECT service_release_locks('holder_name_space') AS col1;
SELECT service_get_write_locks('holder_name_space', ' lock', 0) AS col1;
SELECT service_release_locks('holder_name_space') AS col1;
SELECT service_get_write_locks('holder_name_space', 'loc', 0) AS col1;
SELECT service_release_locks('holder_name_space') AS col1;
SELECT service_get_write_locks('holder_name_space', 'ock', 0) AS col1;
SELECT service_release_locks('holder_name_space') AS col1;
SELECT service_release_locks('holder_name_space ') AS col1;
SELECT service_get_write_locks('holder_name_space', 'lock', 0) AS col1;
SELECT service_release_locks(' holder_name_space') AS col1;
SELECT service_get_write_locks('holder_name_space', 'lock', 0) AS col1;
SELECT service_release_locks('holder_name_spac') AS col1;
SELECT service_get_write_locks('holder_name_space', 'lock', 0) AS col1;
SELECT service_release_locks('older_name_spac') AS col1;
SELECT service_get_write_locks('holder_name_space', 'lock', 0) AS col1;
SELECT service_release_locks('holder_name_space') AS col1;
SELECT COUNT(*) = 0 AS expect_1 FROM performance_schema.metadata_locks WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT service_get_write_locks('holder_name_space', 'lock', 0) AS col1;
SELECT service_get_write_locks('holder_name_space', 'lock', 0) AS col1;
SELECT service_get_write_locks('holder_name_space', 'lock', -1) AS col1;
SELECT service_release_locks('holder_name_space') AS col1;
SELECT service_release_locks('holder_name_space') AS col1;
SELECT service_get_write_locks('holder_name_space', 'lock', 0) AS col1;
SELECT service_get_write_locks('holder_name_space', 'lock', 1.0E-5) AS col1;
SELECT service_release_locks('holder_name_space') AS col1;
SELECT COUNT(*) = 0 AS expect_1 FROM performance_schema.metadata_locks WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT service_get_write_locks('holder_name_space', 'l1', 'l1', 0) AS col1;
SELECT COUNT(*) = 2 AS expect_1 FROM performance_schema.metadata_locks WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT service_get_write_locks('holder_name_space', 'l2', 0) AS col1, service_get_write_locks('holder_name_space', 'l2', 0);
SELECT service_get_write_locks('holder_name_space', 'l3', 0) AS col1;
SELECT service_get_write_locks('holder_name_space', 'l3', 0) AS col1;
SELECT COUNT(*) = 6 AS expect_1 FROM performance_schema.metadata_locks WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT service_release_locks('holder_name_space') AS col1;
SELECT COUNT(*) = 0 AS expect_1 FROM performance_schema.metadata_locks WHERE OBJECT_TYPE = 'LOCKING SERVICE';
SELECT service_get_write_locks('holder_name_space', 'first', 'middle', 'last', 0) AS col1;
SELECT service_get_write_locks('holder_name_space', 'first', 'l2_1', 'l3_1', 0) AS col1;
