SELECT * FROM mysql.server_cost;
SHOW INDEX FROM mysql.server_cost;
SELECT * FROM mysql.engine_cost;
SHOW INDEX FROM mysql.engine_cost;
UPDATE mysql.server_cost SET cost_value=0.1 WHERE cost_name="row_evaluate_cost";
SELECT * FROM mysql.server_cost WHERE cost_name="row_evaluate_cost";
UPDATE mysql.server_cost SET cost_value=DEFAULT WHERE cost_name="row_evaluate_cost";
SELECT * FROM mysql.server_cost WHERE cost_name="row_evaluate_cost";
INSERT INTO mysql.server_cost VALUES ("lunch_cost", DEFAULT, CURRENT_TIMESTAMP, "Lunch is important", DEFAULT);
SELECT * FROM mysql.server_cost;
DELETE FROM mysql.server_cost WHERE cost_name="lunch_cost";
INSERT INTO mysql.server_cost VALUES ("row_evaluate_cost", DEFAULT, CURRENT_TIMESTAMP, "Faster CPU", DEFAULT);
INSERT INTO mysql.server_cost VALUES ("ROW_EVALUATE_COST", DEFAULT, CURRENT_TIMESTAMP, "Faster CPU", DEFAULT);
SELECT * FROM mysql.server_cost;
UPDATE mysql.engine_cost SET cost_value=0.1 WHERE cost_name="io_block_read_cost";
SELECT * FROM mysql.engine_cost WHERE cost_name="io_block_read_cost";
UPDATE mysql.engine_cost SET cost_value=DEFAULT WHERE cost_name="io_block_read_cost";
SELECT * FROM mysql.engine_cost WHERE cost_name="io_block_read_cost";
INSERT INTO mysql.engine_cost VALUES ("InnoDB", 2, "lunch_cost1", DEFAULT, CURRENT_TIMESTAMP, "Lunch 1", DEFAULT), ("InnoDB", 2, "lunch_cost2", DEFAULT, CURRENT_TIMESTAMP, "Lunch 2", DEFAULT);
SELECT * FROM mysql.engine_cost;
DELETE FROM mysql.engine_cost WHERE cost_name LIKE "lunch_cost%";
INSERT INTO mysql.engine_cost VALUES ("default", 0, "lunch_cost", DEFAULT, CURRENT_TIMESTAMP, "Lunch", DEFAULT);
INSERT INTO mysql.engine_cost VALUES ("default", 0, "lunch_cost", DEFAULT, CURRENT_TIMESTAMP, "Lunch", DEFAULT);
SELECT * FROM mysql.engine_cost;
DELETE FROM mysql.engine_cost WHERE cost_name="lunch_cost";
INSERT INTO mysql.engine_cost VALUES ("default", 0, "IO_BLOCK_READ_COST", DEFAULT, CURRENT_TIMESTAMP, "Lunch", DEFAULT);
SELECT * FROM mysql.engine_cost;
CREATE TABLE server_cost_tmp ( cost_name VARCHAR(64) NOT NULL, last_update TIMESTAMP );
CREATE TABLE engine_cost_tmp ( cost_name VARCHAR(64) NOT NULL, last_update TIMESTAMP );
INSERT INTO server_cost_tmp SELECT cost_name, last_update FROM mysql.server_cost;
INSERT INTO engine_cost_tmp SELECT cost_name, last_update FROM mysql.engine_cost;
UPDATE mysql.server_cost  SET cost_value=0.1 WHERE cost_name="row_evaluate_cost";
SELECT mysql.server_cost.cost_name FROM mysql.server_cost JOIN server_cost_tmp  ON mysql.server_cost.cost_name = server_cost_tmp.cost_name WHERE mysql.server_cost.last_update > server_cost_tmp.last_update;
UPDATE mysql.server_cost  SET cost_value=DEFAULT WHERE cost_name="row_evaluate_cost";
UPDATE mysql.engine_cost  SET cost_value=2.0 WHERE cost_name="io_block_read_cost";
SELECT mysql.engine_cost.cost_name FROM mysql.engine_cost JOIN engine_cost_tmp  ON mysql.engine_cost.cost_name = engine_cost_tmp.cost_name WHERE mysql.engine_cost.last_update > engine_cost_tmp.last_update;
UPDATE mysql.engine_cost  SET cost_value=DEFAULT WHERE cost_name="io_block_read_cost";
DROP TABLE server_cost_tmp, engine_cost_tmp;
SELECT COUNT(*) FROM mysql.server_cost WHERE default_value IS NULL;
SELECT COUNT(*) FROM mysql.engine_cost WHERE default_value IS NULL;
UPDATE mysql.server_cost SET default_value = 1.0;
UPDATE mysql.engine_cost SET default_value = 1.0;
