SELECT "Outfile OK" INTO OUTFILE "/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/outfile.test";
set @tmpdir="../../tmp";
drop table if exists t1;
create table t1 (`a` blob);
insert into t1 values("hello world"),("Hello mars"),(NULL);
select * into outfile "../../tmp/outfile-test.1" from t1;
select load_file(concat(@tmpdir,"/outfile-test.1"));
select * into dumpfile "../../tmp/outfile-test.2" from t1 limit 1;
select load_file(concat(@tmpdir,"/outfile-test.2"));
select * into dumpfile "../../tmp/outfile-test.3" from t1 where a is null;
select load_file(concat(@tmpdir,"/outfile-test.3"));
select * into outfile "../../tmp/outfile-test.1" from t1;
select * into dumpfile "../../tmp/outfile-test.2" from t1;
select * into dumpfile "../../tmp/outfile-test.3" from t1;
select load_file(concat(@tmpdir,"/outfile-test.not-exist"));
drop table t1;
select 1 into outfile "../../tmp/outfile-test.4";
select load_file(concat(@tmpdir,"/outfile-test.4"));
CREATE TABLE t1 (a INT);
EXPLAIN SELECT /*+ SET_VAR(optimizer_switch='hypergraph_optimizer=off') */ * INTO OUTFILE '/tmp/t1.txt'   FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n'   FROM t1;
DROP TABLE t1;
SELECT * INTO OUTFILE "../../tmp/outfile-test.4" FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' FROM information_schema.schemata LIMIT 0, 5;
use information_schema;
SELECT * INTO OUTFILE "../../tmp/outfile-test.4" FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' FROM schemata LIMIT 0, 5;
use test;
create table t1(a int);
select * into outfile "/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/mysql-test/outfile-test1" from t1;
drop table t1;
create database mysqltest;
select schema_name into outfile "../../tmp/outfile-test.4" fields terminated by ',' optionally enclosed by '"'  lines terminated by '\n' from information_schema.schemata where schema_name like 'mysqltest';
select schema_name into outfile "../../tmp/outfile-test.4" fields terminated by ',' optionally enclosed by '"'  lines terminated by '\n' from information_schema.schemata where schema_name like 'mysqltest';
use test;
drop database mysqltest;
