drop table if exists abs;
drop table if exists bug21114_child;
CREATE TABLE abs( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES abs(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES abs (col1, col2) ) ENGINE InnoDb;
SHOW CREATE TABLE abs;
SHOW CREATE TABLE bug21114_child;
DROP TABLE bug21114_child;
DROP TABLE abs;
drop table if exists field;
drop table if exists bug21114_child;
CREATE TABLE field( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES field(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES field (col1, col2) ) ENGINE InnoDb;
SHOW CREATE TABLE field;
SHOW CREATE TABLE bug21114_child;
DROP TABLE bug21114_child;
DROP TABLE field;
drop table if exists format;
drop table if exists bug21114_child;
CREATE TABLE format( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES format(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES format (col1, col2) ) ENGINE InnoDb;
SHOW CREATE TABLE format;
SHOW CREATE TABLE bug21114_child;
DROP TABLE bug21114_child;
DROP TABLE format;
drop table if exists acos;
drop table if exists bug21114_child;
CREATE TABLE acos( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES acos(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES acos (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE acos;
drop table if exists adddate;
drop table if exists bug21114_child;
CREATE TABLE adddate( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES adddate(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES adddate (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE adddate;
drop table if exists addtime;
drop table if exists bug21114_child;
CREATE TABLE addtime( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES addtime(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES addtime (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE addtime;
drop table if exists aes_decrypt;
drop table if exists bug21114_child;
CREATE TABLE aes_decrypt( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES aes_decrypt(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES aes_decrypt (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE aes_decrypt;
drop table if exists aes_encrypt;
drop table if exists bug21114_child;
CREATE TABLE aes_encrypt( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES aes_encrypt(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES aes_encrypt (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE aes_encrypt;
drop table if exists area;
drop table if exists bug21114_child;
CREATE TABLE area( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES area(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES area (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE area;
drop table if exists asbinary;
drop table if exists bug21114_child;
CREATE TABLE asbinary( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES asbinary(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES asbinary (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE asbinary;
drop table if exists asin;
drop table if exists bug21114_child;
CREATE TABLE asin( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES asin(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES asin (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE asin;
drop table if exists astext;
drop table if exists bug21114_child;
CREATE TABLE astext( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES astext(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES astext (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE astext;
drop table if exists aswkb;
drop table if exists bug21114_child;
CREATE TABLE aswkb( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES aswkb(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES aswkb (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE aswkb;
drop table if exists aswkt;
drop table if exists bug21114_child;
CREATE TABLE aswkt( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES aswkt(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES aswkt (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE aswkt;
drop table if exists atan;
drop table if exists bug21114_child;
CREATE TABLE atan( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES atan(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES atan (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE atan;
drop table if exists atan2;
drop table if exists bug21114_child;
CREATE TABLE atan2( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES atan2(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES atan2 (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE atan2;
drop table if exists benchmark;
drop table if exists bug21114_child;
CREATE TABLE benchmark( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES benchmark(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES benchmark (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE benchmark;
drop table if exists bin;
drop table if exists bug21114_child;
CREATE TABLE bin( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES bin(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES bin (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE bin;
drop table if exists bit_count;
drop table if exists bug21114_child;
CREATE TABLE bit_count( col1 int not null, col2 int not null, col3 varchar(10), CONSTRAINT pk PRIMARY KEY (col1, col2) ) ENGINE InnoDb;
CREATE TABLE bug21114_child( pk int not null, fk_col1 int not null, fk_col2 int not null, fk_col3 int not null, fk_col4 int not null, CONSTRAINT fk_fct FOREIGN KEY (fk_col1, fk_col2) REFERENCES bit_count(col1, col2), CONSTRAINT fk_fct_space FOREIGN KEY (fk_col3, fk_col4) REFERENCES bit_count (col1, col2) ) ENGINE InnoDb;
DROP TABLE bug21114_child;
DROP TABLE bit_count;
drop table if exists bit_length;
drop table if exists bug21114_child;
