SET NAMES utf8;
CREATE RESOURCE GROUP café TYPE=USER VCPU=1-3 THREAD_PRIORITY=5;
CREATE RESOURCE GROUP cafe TYPE=USER VCPU=1-3 THREAD_PRIORITY=5;
CREATE RESOURCE GROUP CAFE TYPE=USER VCPU=1-3 THREAD_PRIORITY=5;
DROP RESOURCE GROUP CaFé;
SET NAMES default;
