SELECT @@global.log_error_services;
SELECT "*** SWITCHING ERROR LOG TO SYSLOG/EVENTLOG ***";
INSTALL COMPONENT "file://component_log_sink_syseventlog";
SELECT "logging to syseventlog";
SET @start_value= @@global.syseventlog.facility;
SET @@global.syseventlog.facility= DEFAULT;
SELECT @@global.syseventlog.facility, @start_value;
SET @@global.syseventlog.facility="user";
SELECT @@global.syseventlog.facility;
SET @@global.syseventlog.facility= "daemon";
SELECT @@global.syseventlog.facility;
SET @@global.syseventlog.facility= "local0";
SELECT @@global.syseventlog.facility;
SET @@global.syseventlog.facility= 9;
SET GLOBAL syseventlog.facility= 0.01;
SET SESSION syseventlog.facility= "local1";
SET LOCAL syseventlog.facility= "local1";
SET @@global.syseventlog.facility= "log_local5";
SELECT @@global.syseventlog.facility;
SET @@global.syseventlog.facility= "LOG_LOCAL7";
SELECT @@global.syseventlog.facility;
SET @@global.syseventlog.facility= "9";
SET @@global.syseventlog.facility= "local8";
SET @@global.syseventlog.facility= "";
SET @@global.syseventlog.facility= @start_value;
SET @start_value= @@global.syseventlog.include_pid;
SET @@global.syseventlog.include_pid= DEFAULT;
SELECT @@global.syseventlog.include_pid;
SET @@global.syseventlog.include_pid= 0;
SELECT @@global.syseventlog.include_pid;
SET @@global.syseventlog.include_pid= 1;
SELECT @@global.syseventlog.include_pid;
SET @@global.syseventlog.include_pid= ON;
SELECT @@global.syseventlog.include_pid;
SET @@global.syseventlog.include_pid= OFF;
SELECT @@global.syseventlog.include_pid;
SET @@global.syseventlog.include_pid= 9;
SELECT @@global.syseventlog.include_pid;
SET GLOBAL syseventlog.include_pid= 0.01;
SET SESSION syseventlog.include_pid= 0;
SET LOCAL syseventlog.include_pid= 0;
SET @@global.syseventlog.include_pid= @start_value;
SET @start_value= @@global.syseventlog.tag;
SET @@global.syseventlog.tag= DEFAULT;
SELECT @@global.syseventlog.tag;
SET @@global.syseventlog.tag="production";
SELECT @@global.syseventlog.tag;
SET @@global.syseventlog.tag= "";
SELECT @@global.syseventlog.tag;
SET @@global.syseventlog.tag= 9;
SET @@global.syseventlog.tag= "path/like";
SET GLOBAL syseventlog.tag= 0.01;
SET SESSION syseventlog.tag= "staging";
SET LOCAL syseventlog.tag= "staging";
SET @@global.syseventlog.tag= @start_value;
FLUSH ERROR LOGS;
SET @@global.log_error_services=DEFAULT;
UNINSTALL COMPONENT "file://component_log_sink_syseventlog";
