DROP TABLE if exists t1;
SET sql_mode = 'NO_ENGINE_SUBSTITUTION';
select field from t1 group by field;
drop table t1;
create table t1 (a enum (' ','a','b') not null);
show create table t1;
drop table t1;
create table t1 (a enum (' ','a','b ') not null default 'b ');
show create table t1;
drop table t1;
create table t1 (a enum ('0','1'));
insert into t1 set a='foobar';
select * from t1;
update t1 set a = replace(a,'x','y');
select * from t1;
drop table t1;
set names latin1;
create table t1 (a enum(0xE4, '1', '2') not null default 0xE4) character set latin1;
show columns from t1;
show create table t1;
drop table t1;
set names latin1;
CREATE TABLE t1 ( a INT  default 1, b ENUM('value','���_value','���') character set latin1 NOT NULL );
show create table t1;
show columns from t1;
drop table t1;
CREATE TABLE t1 (c enum('a', 'A') BINARY);
INSERT INTO t1 VALUES ('a'),('A');
SELECT * FROM t1;
DROP TABLE t1;
CREATE TABLE t1 (c enum('ae','oe','ue','ss') collate latin1_german2_ci);
INSERT INTO t1 VALUES ('�'),('�'),('�'),('�');
SELECT * FROM t1;
DROP TABLE t1;
CREATE TABLE t1 ( a ENUM('�','�','�') character set utf8 default '�' );
show create table t1;
insert into t1 values ('�'), ('�'), ('�');
select a from t1 order by a;
drop table t1;
set names utf8;
CREATE TABLE t1 ( a ENUM('ä','ö','ü') character set latin1 default 'ü' );
insert into t1 values ('ä'),('ö'),('ü');
set names latin1;
show create table t1;
select a from t1 order by a;
drop table t1;
create table t1 (a enum ('Y','N') CHARACTER SET utf8 COLLATE utf8_bin);
insert into t1 values ('Y');
alter table t1 add b set ('Y','N') CHARACTER SET utf8 COLLATE utf8_bin;
alter table t1 add c enum ('Y','N') CHARACTER SET utf8 COLLATE utf8_bin;
select * from t1;
drop table t1;
create table t1 (a enum('x','y') default 'x');
alter table t1 alter a set default 'z';
drop table t1;
create table t1 (a set('x','y') default 'x');
alter table t1 alter a set default 'z';
drop table t1;
create table t1 (f1 int);
alter table t1 add f2 enum(0xFFFF);
show create table t1;
drop table t1;
create table t1(russian enum('E','F','E�F','F�E') NOT NULL DEFAULT'E');
show create table t1;
drop table t1;
create table t1(denormal enum('E','F','E,F','F,E') NOT NULL DEFAULT'E');
show create table t1;
drop table t1;
create table t1(russian_deviant enum('E','F','E�F','F,E') NOT NULL DEFAULT'E');
show create table t1;
drop table t1;
create table t1(exhausting_charset enum('ABCDEFGHIJKLMNOPQRSTUVWXYZ','	 
 !"','#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~','xx\','yy\�','zz�������������������������������������������������������������������������������������������������������������������������������'));
drop table t1;
CREATE TABLE t1 ( id INT AUTO_INCREMENT PRIMARY KEY, c1 ENUM('a', '', 'b') );
INSERT INTO t1 (c1) VALUES (0), ('a'), (''), ('b');
SELECT id, c1 + 0, c1 FROM t1;
ALTER TABLE t1 CHANGE c1 c1 ENUM('a', '') NOT NULL;
SELECT id, c1 + 0, c1 FROM t1;
DROP TABLE t1;
create table t1(f1 set('a','b'), index(f1));
insert into t1 values(''),(''),('a'),('b');
select * from t1 where f1='';
drop table t1;
CREATE TABLE t1 (c1 ENUM('a', '', 'b'));
INSERT INTO t1 (c1) VALUES ('b');
INSERT INTO t1 (c1) VALUES ('');
INSERT INTO t1 (c1) VALUES (0);
INSERT INTO t1 (c1) VALUES ('');
SELECT c1 + 0, COUNT(c1) FROM t1 GROUP BY c1;
CREATE TABLE t2 SELECT * FROM t1;
SELECT c1 + 0 FROM t2;
DROP TABLE t1,t2;
CREATE TABLE t1(a enum('a','b','c','d'));
INSERT INTO t1 VALUES (4),(1),(0),(3);
ANALYZE TABLE t1;
SELECT a FROM t1;
EXPLAIN SELECT a FROM t1 WHERE a=0;
SELECT a FROM t1 WHERE a=0;
ALTER TABLE t1 ADD PRIMARY KEY (a);
EXPLAIN SELECT a FROM t1 WHERE a=0;
SELECT a FROM t1 WHERE a=0;
DROP TABLE t1;
SET sql_mode = default;
CREATE TABLE t1(exhausting_charset enum( 'zz�������������������������������������������������������������������������������������������������������������������������������')) CHARSET=utf8mb4;
DROP TABLE t1;
CREATE TABLE t1(exhausting_charset enum( 'zz�������������������������������������������������������������������������������������������������������������������������������  zz�������������������������������������������������������������������������������������������������������������������������������')) CHARSET=utf8mb4;
CREATE PROCEDURE p1(exhausting_charset enum( 'zz�������������������������������������������������������������������������������������������������������������������������������') CHARACTER SET utf8mb4) BEGIN END;
DROP PROCEDURE p1;
CREATE PROCEDURE p1(exhausting_charset enum( 'zz�������������������������������������������������������������������������������������������������������������������������������  zz�������������������������������������������������������������������������������������������������������������������������������') CHARACTER SET utf8mb4) BEGIN END;
set session optimizer_switch="derived_merge=off";
set session internal_tmp_mem_storage_engine=temptable;
show function status;
select ROUTINE_SCHEMA, ROUTINE_NAME, ROUTINE_TYPE from INFORMATION_SCHEMA.ROUTINES where ROUTINE_TYPE = 'FUNCTION'   order by  ROUTINE_SCHEMA, ROUTINE_NAME;
set session internal_tmp_mem_storage_engine=default;
set session optimizer_switch="derived_merge=default";
CREATE TABLE grants ( USER char(32), HOST char(60), PRIV char(32), WITH_GRANT_OPTION enum('N','Y'), PRIMARY KEY (WITH_GRANT_OPTION,`USER`,`HOST`, `PRIV`) ) engine innodb;
insert into grants values ('mysql.session','localhost','PERSIST_RO_VARIABLES_ADMIN','N');
insert into grants values ('mysql.session','localhost','SESSION_VARIABLES_ADMIN','N');
insert into grants values ('mysql.session','localhost','SYSTEM_VARIABLES_ADMIN','N');
