SET @org_partial_revokes= @@partial_revokes;
SET @org_sql_mode= @@sql_mode;
CREATE USER u1;
SHOW CREATE USER u1;
ALTER USER u1 COMMENT 'free form text';
ALTER USER u1 COMMENT 'changed the free form text';
ALTER USER u1 ATTRIBUTE '{"uid" : "34234"}';
ALTER USER u1 ATTRIBUTE '{"speed" : "9000"}';
ALTER USER u1 ATTRIBUTE '{"speed" : null }';
ALTER USER u4@sdasd ATTRIBUTE '{}';
ALTER USER fff@asdasd COMMENT '';
ALTER USER USER() COMMENT 'test';
CREATE USER foo3 PASSWORD EXPIRE DEFAULT COMMENT 'abc';
SHOW CREATE USER foo4;
SELECT * FROM INFORMATION_SCHEMA.USER_ATTRIBUTES WHERE USER like 'foo%';
SELECT `attribute`->>"$.comment" FROM INFORMATION_SCHEMA.USER_ATTRIBUTES WHERE USER like 'foo%';
SET GLOBAL partial_revokes=ON;
SET GLOBAL partial_revokes=OFF;
CREATE USER u1 COMMENT 'Hello "Smith"';
DROP USER u1;
DROP USER u1;
CREATE USER u1 COMMENT 'Hello "Smith"';
SET @@sql_mode='NO_BACKSLASH_ESCAPES';
DROP USER u1;
DROP USER u1;
SET @@sql_mode = @org_sql_mode;
SET GLOBAL partial_revokes=ON;
ALTER USER CURRENT_USER() COMMENT 'test';
ALTER USER CURRENT_USER() ATTRIBUTE '{ "comment" : null }';
SET GLOBAL partial_revokes=@org_partial_revokes;
