set @orig_sql_mode= @@sql_mode;
drop table if exists t1;
create table t1 (i int);
flush privileges;
flush user_resources;
select * from t1;
select * from t1;
select * from t1;
select * from t1;
flush user_resources;
select * from t1;
select * from t1;
select * from t1;
delete from t1;
delete from t1;
delete from t1;
select * from t1;
delete from t1;
select * from t1;
flush user_resources;
select * from t1;
select * from t1;
select * from t1;
flush privileges;
flush user_resources;
select * from t1;
select * from t1;
select * from t1;
flush user_resources;
select * from t1;
select @@session.max_user_connections, @@global.max_user_connections;
set session max_user_connections= 2;
set global max_user_connections= 2;
select @@session.max_user_connections, @@global.max_user_connections;
flush user_resources;
select @@session.max_user_connections, @@global.max_user_connections;
select * from t1;
flush user_resources;
select @@session.max_user_connections, @@global.max_user_connections;
set global max_user_connections= 0;
drop table t1;
set sql_mode= @orig_sql_mode;
