CREATE VIEW v1 AS SELECT '<--- 65 char including the arrows                            --->';
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'test' AND TABLE_NAME = 'v1' ORDER BY COLUMN_NAME;
DROP VIEW v1;
CREATE VIEW v1 AS select '<--- 65 char including the arrows                            --->' AS `Name_exp_1`;
DROP VIEW v1;
CREATE VIEW v1 AS select '<--- 65 char including the arrows                            --->' AS `Name_exp_1`;
DROP VIEW v1;
CREATE VIEW v1 AS SELECT (SELECT '<--- 54 char including the arrows (+ 11 outside)   -->');
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'test' AND TABLE_NAME = 'v1' ORDER BY COLUMN_NAME;
DROP VIEW v1;
CREATE VIEW v1 AS select (select '<--- 54 char including the arrows (+ 11 outside)   -->') AS `Name_exp_1`;
DROP VIEW v1;
CREATE VIEW v1 AS select (select '<--- 54 char including the arrows (+ 11 outside)   -->') AS `Name_exp_1`;
DROP VIEW v1;
CREATE VIEW v1 AS SELECT '<--- 64 char including the arrows                           --->';
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'test' AND TABLE_NAME = 'v1' ORDER BY COLUMN_NAME;
DROP VIEW v1;
CREATE VIEW v1 AS select '<--- 64 char including the arrows                           --->' AS `<--- 64 char including the arrows                           --->`;
DROP VIEW v1;
CREATE VIEW v1 AS select '<--- 64 char including the arrows                           --->' AS `<--- 64 char including the arrows                           --->`;
DROP VIEW v1;
CREATE VIEW v1 AS SELECT (SELECT '<--- 53 char including the arrows (+ 11 outside) --->');
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'test' AND TABLE_NAME = 'v1' ORDER BY COLUMN_NAME;
DROP VIEW v1;
CREATE VIEW v1 AS select (select '<--- 53 char including the arrows (+ 11 outside) --->') AS `(SELECT '<--- 53 char including the arrows (+ 11 outside) --->')`;
DROP VIEW v1;
CREATE VIEW v1 AS select (select '<--- 53 char including the arrows (+ 11 outside) --->') AS `(SELECT '<--- 53 char including the arrows (+ 11 outside) --->')`;
DROP VIEW v1;
CREATE VIEW v1 AS SELECT 'c1', 'c2 ', ' c3', ' c4 ';
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'test' AND TABLE_NAME = 'v1' ORDER BY COLUMN_NAME;
DROP VIEW v1;
CREATE VIEW v1 AS select 'c1' AS `c1`,'c2 ' AS `Name_exp_2`,' c3' AS `c3`,' c4 ' AS `Name_exp_4`;
DROP VIEW v1;
CREATE VIEW v1 AS select 'c1' AS `c1`,'c2 ' AS `Name_exp_2`,' c3' AS `c3`,' c4 ' AS `Name_exp_4`;
DROP VIEW v1;
DROP VIEW IF EXISTS v1;
DROP TABLE IF EXISTS t1,t2;
CREATE VIEW v1 AS SELECT '0000000000 1111111111 2222222222 3333333333 4444444444 5555555555';
DROP VIEW v1;
CREATE VIEW v1 AS select '0000000000 1111111111 2222222222 3333333333 4444444444 5555555555' AS `Name_exp_1`;
DROP VIEW v1;
CREATE VIEW v1 AS SELECT 'c1', 'c2 ', ' c3', ' c4 ';
DROP VIEW v1;
CREATE VIEW v1 AS select 'c1' AS `c1`,'c2 ' AS `Name_exp_2`,' c3' AS `c3`,' c4 ' AS `Name_exp_4`;
DROP VIEW v1;
CREATE VIEW v1 AS SELECT 'c1', 'c2 ', ' c3', ' c4 ', 'Name_exp_2';
DROP VIEW v1;
CREATE VIEW v1 AS select 'c1' AS `c1`,'c2 ' AS `Name_exp_2`,' c3' AS `c3`,' c4 ' AS `Name_exp_4`,'Name_exp_2' AS `Name_exp_Name_exp_2`;
DROP VIEW v1;
CREATE VIEW v1 AS SELECT (SELECT ' c1 ');
DROP VIEW v1;
CREATE VIEW v1 AS select (select ' c1 ') AS `(SELECT ' c1 ')`;
DROP VIEW v1;
CREATE TABLE t1(a INT);
CREATE TABLE t2 LIKE t1;
CREATE VIEW v1 AS SELECT a FROM t1 WHERE EXISTS (SELECT 1 FROM t2 AS b WHERE b.a = 0);
DROP VIEW v1;
CREATE VIEW v1 AS select `test`.`t1`.`a` AS `a` from `test`.`t1` where exists(select 1 from `test`.`t2` `b` where (`b`.`a` = 0));
DROP VIEW v1;
CREATE VIEW v1 AS SELECT a FROM t1 WHERE EXISTS (SELECT a AS alias FROM t1 GROUP BY alias);
SHOW CREATE VIEW v1;
DROP VIEW v1;
CREATE VIEW v1 AS select `test`.`t1`.`a` AS `a` from `test`.`t1` where exists(select `test`.`t1`.`a` AS `alias` from `test`.`t1` group by `alias`);
DROP VIEW v1;
CREATE VIEW v1 AS SELECT a FROM t1 WHERE EXISTS (SELECT '  a   ' AS alias FROM t1 GROUP BY alias);
SHOW CREATE VIEW v1;
DROP VIEW v1;
CREATE VIEW v1 AS select `test`.`t1`.`a` AS `a` from `test`.`t1` where exists(select '  a   ' AS `alias` from `test`.`t1` group by `alias`);
DROP VIEW v1;
DROP TABLE t1, t2;
