SET @@global.log_error_verbosity= 3;
SET @@global.wait_timeout= 2;
SET SESSION wait_timeout=100;
SET @aborted_clients= 0;
SELECT 1;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	1', 16)+0;
SELECT 2;
SELECT 3;
FLUSH STATUS;
SET @aborted_clients= 0;
SELECT 1;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	0', 16)+0;
SET @aborted_clients= SUBSTRING('Aborted_clients	1', 16)+0;
SELECT 2;
SELECT 3;
SET @@global.wait_timeout= 28800;
SET @@SESSION.wait_timeout = 2;
SELECT 1;
SET @@SESSION.wait_timeout = 2;
SELECT 1;
SELECT "Check that we don't reconnect with reconnection disabled.";
SET @is_old_connection = 1;
SELECT @is_old_connection;
SET @@SESSION.wait_timeout = 2;
SELECT "Unix domain socket will hit wait_timeout with reconnect";
SELECT @is_old_connection;
