CREATE TABLE t(a INT);
INSERT INTO t VALUES (1),(2),(3);
ANALYZE TABLE t;
SELECT * FROM t WHERE a = ALL(SELECT ROW_NUMBER() OVER () + 1 FROM t);
SELECT * FROM t WHERE a <> SOME(SELECT ROW_NUMBER() OVER () + 1 FROM t);
SELECT * FROM t WHERE a <> ANY(SELECT ROW_NUMBER() OVER () + 1 FROM t);
SELECT * FROM t upper WHERE upper.a IN (SELECT ROW_NUMBER() OVER () FROM t WHERE t.a > upper.a);
SELECT * FROM t upper WHERE upper.a > ANY (SELECT ROW_NUMBER() OVER () FROM t WHERE t.a > upper.a);
SELECT * FROM t upper WHERE upper.a > ALL (SELECT ROW_NUMBER() OVER () FROM t WHERE t.a > upper.a);
DROP TABLE t;
CREATE TABLE t1(i INT, j INT, k INT);
INSERT INTO t1 VALUES (1,1,1),(2,2,2);
select * from t1 AS upper where i+1 IN (select row_number() over () + upper.i from t1 );
DROP TABLE t1;
