create database mysqltest1;
use mysqltest1;
create table t1(pub int, priv int);
insert into t1 values(1,2);
analyze table t1;
use mysqltest1;
select pub from t1;
select priv from t1;
select * from (select pub from t1) as dt;
explain select * from (select pub from t1) as dt;
select /*+ merge(dt) */ * from (select priv from t1) as dt;
select /*+ no_merge(dt) */ * from (select priv from t1) as dt;
explain select * from (select priv from t1) as dt;
with qn as (select pub from t1) select * from qn;
explain with qn as (select pub from t1) select * from qn;
with qn as (select priv from t1) select /*+ merge(qn) */ * from qn;
with qn as (select priv from t1) select /*+ no_merge(qn) */ * from qn;
explain with qn as (select priv from t1) select * from qn;
with qn2 as (with qn as (select pub from t1) select * from qn) select * from qn2;
with qn2 as (with qn as (select priv from t1) select * from qn) select * from qn2;
drop database mysqltest1;
