USE test;
RESET MASTER;
RESET REPLICA ALL FOR CHANNEL '';
USE test;
RESET MASTER;
RESET REPLICA ALL FOR CHANNEL '';
START REPLICA ;
CREATE TABLE tmp (a VARCHAR(10), b INT) ENGINE=Memory;
INSERT INTO tmp VALUES ('aZa', 1), ('zAz', 2), ('M', 3);
INSERT INTO tmp SELECT * FROM tmp;
INSERT INTO tmp SELECT * FROM tmp;
INSERT INTO tmp SELECT * FROM tmp;
INSERT INTO tmp SELECT * FROM tmp;
INSERT INTO tmp SELECT * FROM tmp;
INSERT INTO tmp SELECT * FROM tmp;
CREATE TABLE t (a VARCHAR(10), b INT, KEY a (a)) ENGINE = MyISAM;
INSERT INTO t SELECT * FROM tmp;
SELECT COUNT(*) FROM t WHERE b > -1;
RENAME TABLE t to t_2;
RENAME TABLE t_2 to t;
SELECT COUNT(*) FROM t WHERE b > -1;
CHECK TABLE t;
REPAIR TABLE t;
SELECT COUNT(*) FROM t WHERE b > -1;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.t ORDER BY `a`,`b` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table-master-test-t';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.t ORDER BY `a`,`b` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.2/data//diff_table-slave-test-t';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE t, tmp;
STOP REPLICA ;
SELECT asynchronous_connection_failover_reset();
SELECT asynchronous_connection_failover_reset();
KILL 12;
