SET SQL_LOG_BIN = 0;
SET DEBUG = "";
USE mtr;
SET SESSION TRANSACTION READ WRITE;
SET SESSION AUTOCOMMIT = 1;
COMMIT;
SET @@session.sql_mode = '';
SET @@session.sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
