SET @global_saved_tmp =  @@global.offline_mode;
CREATE DATABASE wl3836;
USE wl3836;
SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST WHERE DB LIKE 'wl3836';
CREATE USER 'user1'@'localhost';
CREATE USER 'user2'@'localhost';
GRANT ALL ON wl3836.* TO 'user1'@'localhost', 'user2'@'localhost';
SET GLOBAL offline_mode=ON;
CREATE TABLE t1 (id INT PRIMARY KEY AUTO_INCREMENT) ENGINE=MYISAM;
CREATE TABLE t2 (id INT UNSIGNED NOT NULL);
INSERT INTO t1 VALUES (0),(0),(0),(0),(0),(0),(0),(0), (0),(0),(0),(0),(0),(0),(0),(0), (0),(0),(0),(0),(0),(0),(0),(0), (0),(0),(0),(0),(0),(0),(0),(0), (0),(0),(0),(0),(0),(0),(0),(0), (0),(0),(0),(0),(0),(0),(0),(0), (0),(0),(0),(0),(0),(0),(0),(0), (0),(0),(0),(0),(0),(0),(0),(0);
INSERT t1 SELECT 0 FROM t1 AS a1, t1 AS a2 LIMIT 4032;
INSERT INTO t2 SELECT id FROM t1;
set @previous_sql_mode_htnt542nh=@@sql_mode;
set sql_mode=(select replace(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
SELECT id FROM t1 WHERE id IN (SELECT DISTINCT a.id FROM t2 a, t2 b, t2 c, t2 d GROUP BY ACOS(1/a.id), b.id, c.id, d.id HAVING a.id BETWEEN 10 AND 20);
SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST WHERE DB LIKE 'wl3836';
SET GLOBAL offline_mode = ON;
SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST WHERE DB LIKE 'wl3836';
SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST WHERE DB LIKE 'wl3836';
SET GLOBAL offline_mode=OFF;
DROP DATABASE wl3836;
DROP USER 'user1'@'localhost';
DROP USER 'user2'@'localhost';
USE test;
RESET MASTER;
RESET REPLICA ALL FOR CHANNEL '';
USE test;
RESET MASTER;
RESET REPLICA ALL FOR CHANNEL '';
START REPLICA ;
SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST;
SET GLOBAL offline_mode=ON;
SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST;
SET @slave_saved_tmp = @@global.offline_mode;
SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST;
SET GLOBAL offline_mode=ON;
SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST;
SET GLOBAL offline_mode = @slave_saved_tmp;
STOP REPLICA ;
SELECT asynchronous_connection_failover_reset();
SELECT asynchronous_connection_failover_reset();
KILL 15;
SET @@global.offline_mode = @global_saved_tmp;
