USE test;
RESET MASTER;
RESET REPLICA ALL FOR CHANNEL '';
USE test;
RESET MASTER;
RESET REPLICA ALL FOR CHANNEL '';
START REPLICA ;
use test;
STOP REPLICA ;
SELECT asynchronous_connection_failover_reset();
SELECT asynchronous_connection_failover_reset();
KILL 36;
