SET @save_sqlf=@@global.slow_query_log_file;
SET GLOBAL slow_query_log_file= '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/my_slow.log';
SET timestamp=10;
SET @@global.slow_query_log_file=@save_sqlf;
SET @old_slow_query_log_file= @@global.slow_query_log_file;
SET @old_log_output         = @@global.log_output;
SET GLOBAL slow_query_log_file= '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/my_slow.log';
SET @main_thd_id=CONNECTION_ID();
SET GLOBAL log_output=        'TABLE,FILE';
SET GLOBAL slow_query_log=    1;
SET SESSION long_query_time=  0;
TRUNCATE mysql.slow_log;
SET SESSION long_query_time= 0;
SELECT @@log_output,@@slow_query_log,@@long_query_time;
/* KILL CONNECTION: should not be logged */ SELECT SLEEP(1001);
KILL CONNECTION 10;
SELECT "1>",IF(thread_id=@main_thd_id,"KILLER","killee"),sql_text FROM mysql.slow_log WHERE INSTR(sql_text,"SLEEP(10")>0 ORDER BY start_time;
TRUNCATE mysql.slow_log;
SET SESSION long_query_time= 0;
SELECT @@log_output,@@slow_query_log,@@long_query_time;
/* KILL QUERY: should be logged */ SELECT SLEEP(1002);
KILL QUERY 11;
SELECT "2>",IF(thread_id=@main_thd_id,"KILLER","killee"),sql_text FROM mysql.slow_log WHERE INSTR(sql_text,"SLEEP(10")>0 ORDER BY start_time;
SELECT "con1 is still here.";
SET @@global.slow_query_log_file= @old_slow_query_log_file;
SET @@global.log_output         = @old_log_output;
TRUNCATE TABLE mysql.general_log;
TRUNCATE TABLE mysql.slow_log;
