SET @@session.time_zone=@@global.log_timestamps;
SELECT FROM_UNIXTIME(VARIABLE_VALUE/1000000) INTO @pfs_errlog_latest FROM performance_schema.global_status WHERE VARIABLE_NAME LIKE "Error_log_latest_write";
CREATE USER 'user31633859'@'127.0.0.1';
GRANT SELECT, EVENT, RELOAD ON *.* TO 'user31633859'@'127.0.0.1';
SELECT COUNT(thread_id) FROM performance_schema.threads WHERE name='thread/sql/event_scheduler';
CREATE DEFINER='user31633859'@'127.0.0.1' EVENT IF NOT EXISTS mysql.event31633859 ON SCHEDULE EVERY 1 SECOND DO SET @dummy=1;
SET @@global.offline_mode=ON;
SET @@global.super_read_only=ON;
SELECT definer,event_name FROM information_schema.events WHERE event_schema='mysql'    AND event_name='event31633859';
SELECT @@global.offline_mode;
SELECT @@global.super_read_only;
SELECT error_code,data FROM performance_schema.error_log WHERE error_code='MY-010045' AND logged>=@pfs_errlog_latest;
SELECT COUNT(thread_id) FROM performance_schema.threads WHERE name='thread/sql/event_scheduler';
SELECT @@global.event_scheduler;
SET @@global.super_read_only=OFF;
SELECT COUNT(thread_id)>0 FROM performance_schema.threads WHERE name='thread/sql/event_scheduler';
SET @@global.read_only=OFF;
SET @@global.offline_mode=OFF;
DROP EVENT mysql.event31633859;
DROP USER 'user31633859'@'127.0.0.1';
