SET @old_general_log= @@global.general_log;
SET @old_slow_query_log= @@global.slow_query_log;
SET @old_log_output = @@global.log_output;
SET @old_general_log_file = @@global.general_log_file;
SET GLOBAL log_output="FILE,TABLE";
SET GLOBAL general_log_file = '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/log/master.log';
SET GLOBAL general_log= 'ON';
SET @@global.general_log= @old_general_log;
SET @@global.slow_query_log= @old_slow_query_log;
SET @@global.log_output= @old_log_output;
SET @@global.general_log_file = @old_general_log_file;
TRUNCATE TABLE mysql.general_log;
TRUNCATE TABLE mysql.slow_log;
