drop table if exists t1,t2;
create table t1 (a int) engine=myisam;
drop table t1;
select * from t1;
drop table if exists t1;
create table t1 (a int) engine=myisam;
drop table t1;
select * from t1;
drop table if exists t1;
drop table t1;
