drop table ׻Ѹ;
create table ׻Ѹ (Ѹ text, ʬॳ varchar, 1A char(16));
create index ׻Ѹindex1 on ׻Ѹ using btree (Ѹ);
create index ׻Ѹindex2 on ׻Ѹ using hash (ʬॳ);
insert into ׻Ѹ values('ԥ塼ǥץ쥤','A01');
insert into ׻Ѹ values('ԥ塼եå','ʬB10');
insert into ׻Ѹ values('ԥ塼ץޡ','Z01');
vacuum ׻Ѹ;
select * from ׻Ѹ;
select * from ׻Ѹ where ʬॳ = 'Z01';
select * from ׻Ѹ where ʬॳ ~* 'z01';
select * from ׻Ѹ where ʬॳ like '_Z01_';
select * from ׻Ѹ where ʬॳ like '_Z%';
select * from ׻Ѹ where Ѹ ~ 'ԥ塼[ǥ]';
select * from ׻Ѹ where Ѹ ~* 'ԥ塼[ǥ]';
select *,character_length(Ѹ) from ׻Ѹ;
select *,octet_length(Ѹ) from ׻Ѹ;
select *,position('' in Ѹ) from ׻Ѹ;
select *,substring(Ѹ from 10 for 4) from ׻Ѹ;
