CREATE TABLE INT2_TBL(f1 int2);
INSERT INTO INT2_TBL(f1) VALUES (1);
INSERT INTO INT2_TBL(f1) VALUES (1);
INSERT INTO INT2_TBL(f1) VALUES (1);
INSERT INTO INT2_TBL(f1) VALUES (1);
INSERT INTO INT2_TBL(f1) VALUES (1);
INSERT INTO INT2_TBL(f1) VALUES (1);
INSERT INTO INT2_TBL(f1) VALUES (1);
INSERT INTO INT2_TBL(f1) VALUES (1);
