CREATE TABLE test_extdep_commands (command text);
COPY test_extdep_commands FROM stdin;
ALTER FUNCTION b() DEPENDS ON EXTENSION test_ext5 CREATE TRIGGER c BEFORE INSERT ON a FOR EACH ROW EXECUTE PROCEDURE b() ALTER TRIGGER c ON a DEPENDS ON EXTENSION test_ext5;
CREATE MATERIALIZED VIEW d AS SELECT * FROM a ALTER MATERIALIZED VIEW d DEPENDS ON EXTENSION test_ext5 CREATE INDEX e ON a (a1) ALTER INDEX e DEPENDS ON EXTENSION test_ext5;
RESET search_path;
SELECT * FROM test_extdep_commands;
ALTER FUNCTION test_ext.b() DEPENDS ON EXTENSION test_ext5;
SELECT deptype, p.*  FROM pg_depend, pg_identify_object(classid, objid, objsubid) AS p WHERE refclassid = 'pg_extension'::regclass AND       refobjid = (SELECT oid FROM pg_extension WHERE extname = 'test_ext5')ORDER BY type;
DROP EXTENSION test_ext5;
SELECT deptype, i.*  FROM pg_catalog.pg_depend, pg_identify_object(classid, objid, objsubid) iWHERE refclassid='pg_class'::regclass AND refobjid='test_ext.a'::regclass AND NOT deptype IN ('i', 'a');
DROP SCHEMA test_ext CASCADE;
DROP TABLE test_ext.a;		DROP TABLE test_ext.a CASCADE;
SELECT deptype, i.*  FROM pg_catalog.pg_depend, pg_identify_object(classid, objid, objsubid) i WHERE refclassid='pg_extension'::regclass AND refobjid=(SELECT oid FROM pg_extension WHERE extname='test_ext5');
DROP EXTENSION test_ext5;
DROP SCHEMA test_ext CASCADE;
SET search_path TO test_ext;
DROP TRIGGER c ON a;
DROP FUNCTION b();
DROP MATERIALIZED VIEW d;
DROP INDEX e;
SELECT deptype, i.*  FROM pg_catalog.pg_depend, pg_identify_object(classid, objid, objsubid) i WHERE (refclassid='pg_extension'::regclass AND        refobjid=(SELECT oid FROM pg_extension WHERE extname='test_ext5'))	OR (refclassid='pg_class'::regclass AND refobjid='test_ext.a'::regclass)   AND NOT deptype IN ('i', 'a');
DROP TABLE a;
RESET search_path;
DROP SCHEMA test_ext CASCADE;
SET search_path TO test_ext;
ALTER FUNCTION b() NO DEPENDS ON EXTENSION test_ext5;
ALTER TRIGGER c ON a NO DEPENDS ON EXTENSION test_ext5;
ALTER MATERIALIZED VIEW d NO DEPENDS ON EXTENSION test_ext5;
ALTER INDEX e NO DEPENDS ON EXTENSION test_ext5;
DROP EXTENSION test_ext5;
DROP TRIGGER c ON a;
DROP FUNCTION b();
DROP MATERIALIZED VIEW d;
DROP INDEX e;
DROP SCHEMA test_ext CASCADE;
