CREATE TABLE tid_tab (a int);
INSERT INTO tid_tab VALUES (1), (2);
SELECT min(ctid) FROM tid_tab;
SELECT max(ctid) FROM tid_tab;
TRUNCATE tid_tab;
CREATE MATERIALIZED VIEW tid_matview AS SELECT a FROM tid_tab;
SELECT currtid('tid_matview'::regclass::oid, '(0,1)'::tid);
 SELECT currtid2('tid_matview'::text, '(0,1)'::tid);
 INSERT INTO tid_tab VALUES (1);
 INSERT INTO tid_tab VALUES (1);
REFRESH MATERIALIZED VIEW tid_matview;
SELECT currtid('tid_matview'::regclass::oid, '(0,1)'::tid);
 SELECT currtid2('tid_matview'::text, '(0,1)'::tid);
 DROP MATERIALIZED VIEW tid_matview;
 DROP MATERIALIZED VIEW tid_matview;
TRUNCATE tid_tab;
CREATE SEQUENCE tid_seq;
SELECT currtid('tid_seq'::regclass::oid, '(0,1)'::tid);
 SELECT currtid2('tid_seq'::text, '(0,1)'::tid);
 DROP SEQUENCE tid_seq;
 DROP SEQUENCE tid_seq;
CREATE INDEX tid_ind ON tid_tab(a);
SELECT currtid('tid_ind'::regclass::oid, '(0,1)'::tid);
 SELECT currtid2('tid_ind'::text, '(0,1)'::tid);
 DROP INDEX tid_ind;
 DROP INDEX tid_ind;
CREATE TABLE tid_part (a int) PARTITION BY RANGE (a);
SELECT currtid('tid_part'::regclass::oid, '(0,1)'::tid);
 SELECT currtid2('tid_part'::text, '(0,1)'::tid);
 DROP TABLE tid_part;
 DROP TABLE tid_part;
CREATE VIEW tid_view_no_ctid AS SELECT a FROM tid_tab;
SELECT currtid('tid_view_no_ctid'::regclass::oid, '(0,1)'::tid);
 SELECT currtid2('tid_view_no_ctid'::text, '(0,1)'::tid);
 DROP VIEW tid_view_no_ctid;
 DROP VIEW tid_view_no_ctid;
CREATE VIEW tid_view_with_ctid AS SELECT ctid, a FROM tid_tab;
SELECT currtid('tid_view_with_ctid'::regclass::oid, '(0,1)'::tid);
 SELECT currtid2('tid_view_with_ctid'::text, '(0,1)'::tid);
 INSERT INTO tid_tab VALUES (1);
 INSERT INTO tid_tab VALUES (1);
SELECT currtid('tid_view_with_ctid'::regclass::oid, '(0,1)'::tid);
 SELECT currtid2('tid_view_with_ctid'::text, '(0,1)'::tid);
 DROP VIEW tid_view_with_ctid;
 DROP VIEW tid_view_with_ctid;
TRUNCATE tid_tab;
CREATE VIEW tid_view_fake_ctid AS SELECT 1 AS ctid, 2 AS a;
SELECT currtid('tid_view_fake_ctid'::regclass::oid, '(0,1)'::tid);
 SELECT currtid2('tid_view_fake_ctid'::text, '(0,1)'::tid);
 DROP VIEW tid_view_fake_ctid;
 DROP VIEW tid_view_fake_ctid;
DROP TABLE tid_tab CASCADE;
