CREATE TABLE t1(x, y INTEGER PRIMARY KEY, z) WITHOUT ROWID ;
CREATE TABLE t12(a, b, c, CHECK(c>10));
CREATE TABLE t13(a, b, c CHECK(c>10));
INSERT INTO t1 VALUES(1, 2, 3);
INSERT INTO t1 VALUES(4, 5, 6);
INSERT INTO t1 VALUES(7, 8, 9);
ALTER TABLE t1 DROP COLUMN x;
SELECT * FROM t1;
