CREATE TABLE t1(a COLLATE caseless); 
INSERT INTO t1 VALUES('Abc2');
INSERT INTO t1 VALUES('abc1');
INSERT INTO t1 VALUES('aBc3');
SELECT * FROM t1 ORDER BY a;
SELECT a FROM t1 ORDER BY a COLLATE NOCASE;
SELECT a FROM t1 ORDER BY a COLLATE NOCASE, rowid;
