DROP TABLE t1;
DROP TABLE t2;
CREATE TABLE t1(a);
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(2);
CREATE TABLE t2(b);
INSERT INTO t2 VALUES(3);
SELECT * FROM (SELECT * FROM (SELECT * FROM t1 LIMIT 1) UNION ALL SELECT * from t2);
