CREATE TABLE t0(t TEXT, u TEXT);
INSERT INTO t0 VALUES('t', 'u');
CREATE TABLE t1(v TEXT, w TEXT);
INSERT INTO t1 VALUES('v', 'w');
CREATE TABLE t2(x TEXT, y TEXT);
INSERT INTO t2 VALUES('x', 'y');
SELECT * FROM t0 JOIN t1 ON (t2.x NOT NULL) LEFT JOIN t2 ON false;
SELECT * FROM t0 JOIN t1 ON (t2.x NOT NULL) LEFT JOIN t2 ON false WHERE t2.y ISNULL;
