CREATE TABLE t1 (c0 INTEGER UNIQUE);
CREATE TABLE t2 (c0);
CREATE TABLE t3 (c0);
INSERT INTO t1 VALUES (1);
INSERT INTO t2 VALUES (2);
INSERT INTO t3 VALUES (3);

SELECT t1.c0, t3.c0 FROM t2 NATURAL JOIN t1 RIGHT OUTER JOIN t3 ON t1.c0;
SELECT DISTINCT t1.c0, t3.c0 FROM t2 NATURAL JOIN t1 RIGHT OUTER JOIN t3 ON t1.c0;
