CREATE TABLE t0 (c0);
CREATE TABLE t1(c0);
CREATE VIEW v0(c0) AS SELECT 0.4 FROM t0;
INSERT INTO t1(c0) VALUES (1);
INSERT INTO t0 VALUES (NULL);
SELECT v0.c0 FROM t1 INNER JOIN v0 ON ((((((((v0.c0)))))))AND(t0.c0)) COLLATE RTRIM LEFT OUTER JOIN t0 ON (('a') ISNULL) WHERE (((CASE ((t1.c0) BETWEEN (t1.c0) AND (v0.c0))  WHEN t1.c0 THEN (NOT (v0.c0)) END) ISNULL));
SELECT v0.c0 FROM t1 INNER JOIN v0 ON (((((((v0.c0)))))))AND(t0.c0) COLLATE RTRIM LEFT OUTER JOIN t0 ON (('a') ISNULL) WHERE (((CASE ((t1.c0) BETWEEN (t1.c0) AND (v0.c0))  WHEN t1.c0 THEN (NOT (v0.c0)) END) ISNULL));
