CREATE TABLE t1 (c0, c1);
INSERT INTO t1(c0) VALUES (2);
CREATE TABLE t2 (c0);
CREATE INDEX i0 ON t2 (c0) WHERE c0;
CREATE TABLE t3 (c0);
INSERT INTO t3 VALUES (1);
SELECT * FROM t2 RIGHT OUTER JOIN t3 ON t3.c0 LEFT OUTER JOIN t1 ON t2.c0 WHERE t1.c0;
SELECT (t1.c0 IS TRUE) FROM t2 RIGHT OUTER JOIN t3 ON t3.c0 LEFT OUTER JOIN t1 ON t2.c0;
