CREATE TABLE t2(k,v);
CREATE TRIGGER r2 AFTER INSERT ON t2 BEGIN UPDATE t2 SET (k,v)= ( (WITH cte1(a) AS ( SELECT 1 FROM ( SELECT * FROM t2 ) ) SELECT a FROM cte1 ), 1); END;
CREATE TRIGGER r1 AFTER INSERT ON t2 BEGIN UPDATE t2 SET k=1 FROM t2 AS one, t2 AS two NATURAL JOIN t2 AS three WHERE one.k=two.v; END;
ALTER TABLE t2 RENAME TO t2x;
SELECT * FROM t2x;
