CREATE TABLE t3651(a UNIQUE);
INSERT INTO t3651 VALUES(5);
ALTER TABLE t3651 ADD COLUMN b UNIQUE;
ALTER TABLE t3651 ADD COLUMN b PRIMARY KEY;
ALTER TABLE $tbl RENAME TO xyz;
ALTER TABLE $tbl ADD COLUMN xyz;
