CREATE TABLE yyy(q, w, e CHECK (e > 0), r);
INSERT INTO yyy VALUES(1,1,1,1), (2,2,2,2);
CREATE TABLE zzz(q, w, e, r, CHECK (e > 0));
INSERT INTO zzz VALUES(1,1,1,1), (2,2,2,2);
INSERT INTO yyy VALUES(0,0,0,0);
INSERT INTO yyy VALUES(0,0,0,0);
ALTER TABLE yyy DROP e;
