CREATE TABLE t0 (c0, c1 NOT NULL DEFAULT 1, c2, PRIMARY KEY (c0, c1));
INSERT INTO t0(c2) VALUES (NULL), (NULL);
INSERT INTO t0(c2) VALUES('a');
SELECT DISTINCT * FROM t0 WHERE NULL IS t0.c0;
SELECT * FROM t0 WHERE (( (0 IS NOT FALSE) OR NOT (0 IS FALSE OR (t0.c0 = 1)) ) IS 0);
SELECT ((0 IS NOT FALSE) OR NOT (0 IS FALSE OR (t0.c0 = 1)) ) IS 0 FROM t0;
SELECT ( (0 IS NOT FALSE) OR NOT (0 IS 0 OR (t0.c0 = 1)) ) IS 0 FROM t0;
SELECT ((0 IS NOT FALSE) OR NOT (0 IS FALSE OR (t0.c0 = 1)) ) FROM t0;
SELECT NOT (0 IS FALSE OR (t0.c0 = 1)) FROM t0;

