CREATE TABLE t2(a,b);
CREATE TABLE t3(a REAL);
INSERT INTO t3 VALUES(44.0);
INSERT INTO t3 VALUES(56.0);
SELECT 5 IN (SELECT a,b FROM t2);
SELECT 5 IN (SELECT * FROM t2 UNION SELECT * FROM t2);
SELECT 5 IN (SELECT * FROM t2);
SELECT 5 IN (SELECT * FROM t2 UNION SELECT * FROM t2);
SELECT (CASE WHEN a=0 THEN 0 ELSE (a + 25) / 50 END) AS categ, count(*) FROM t3 GROUP BY categ;
