CREATE TYPE casttesttype;
CREATE FUNCTION casttesttype_in(cstring)   RETURNS casttesttype   AS 'textin'   LANGUAGE internal STRICT IMMUTABLE;
CREATE FUNCTION casttesttype_out(casttesttype)   RETURNS cstring   AS 'textout'   LANGUAGE internal STRICT IMMUTABLE;
CREATE TYPE casttesttype (   internallength = variable,   input = casttesttype_in,   output = casttesttype_out,   alignment = int4);
CREATE FUNCTION casttestfunc(casttesttype) RETURNS int4 LANGUAGE SQL AS SELECT 1;
 ;
 ;
SELECT casttestfunc('foo'::text);
 CREATE CAST (text AS casttesttype) WITHOUT FUNCTION;
 CREATE CAST (text AS casttesttype) WITHOUT FUNCTION;
SELECT casttestfunc('foo'::text);
 SELECT casttestfunc('foo'::text::casttesttype);
 DROP CAST (text AS casttesttype);
 CREATE CAST (text AS casttesttype) WITHOUT FUNCTION AS IMPLICIT;
 CREATE CAST (text AS casttesttype) WITHOUT FUNCTION AS IMPLICIT;
SELECT casttestfunc('foo'::text);
 SELECT 1234::int4::casttesttype;
 CREATE CAST (int4 AS casttesttype) WITH INOUT;
 CREATE CAST (int4 AS casttesttype) WITH INOUT;
SELECT 1234::int4::casttesttype;
 DROP CAST (int4 AS casttesttype);
 DROP CAST (int4 AS casttesttype);
CREATE FUNCTION int4_casttesttype(int4) RETURNS casttesttype LANGUAGE SQL AS SELECT ('foo'::text ||  1::text)::casttesttype;
 ;
 ;
CREATE CAST (int4 AS casttesttype) WITH FUNCTION int4_casttesttype(int4) AS IMPLICIT;
