CREATE TABLE t1(id INTEGER PRIMARY KEY, x INT);
CREATE TABLE t2(y INT);
INSERT INTO t1(id,x) VALUES(1, 0);
SELECT * FROM t2 RIGHT JOIN t1 ON true WHERE (+id,x)=(99,0);
SELECT * FROM t2 RIGHT JOIN t1 ON true WHERE (id,x)=(99,0);
