CREATE VIRTUAL TABLE vt0 USING fts4(c0);
CREATE VIRTUAL TABLE vt1 USING fts4(c0);
CREATE VIEW v0(c0) AS SELECT vt0.c0 FROM vt1 CROSS JOIN vt0 ON vt1.c0;
INSERT INTO vt1(c0) VALUES ('x');
INSERT INTO vt0 VALUES (1), (2);

SELECT * FROM vt1 LEFT OUTER JOIN v0 ON vt1.c0 LEFT OUTER JOIN vt0 ON v0.c0;
SELECT * FROM vt1 LEFT OUTER JOIN v0 ON vt1.c0 LEFT OUTER JOIN vt0 ON v0.c0 WHERE vt0.c0;
