CREATE TABLE t0(c0, c1, c2);
CREATE TABLE t1(c0);
INSERT INTO t1 VALUES('1');
CREATE VIEW v0 AS SELECT 0;
SELECT * FROM v0 RIGHT OUTER JOIN t1 ON t1.c0 INNER JOIN t0 ON t0.c2;
SELECT * FROM v0 RIGHT OUTER JOIN t1 ON t1.c0 INNER JOIN t0 ON t0.c2 WHERE c1 ISNULL;
