CREATE TABLE t1 (c0 );
CREATE TABLE t0 (c0);
INSERT INTO t0(c0) VALUES (NULL);

SELECT DISTINCT t1.c0 FROM t1 FULL OUTER JOIN t0;
SELECT DISTINCT t1.c0 FROM t1 FULL OUTER JOIN t0 WHERE (t0.c0 ISNULL);
