CREATE TABLE t0 (c0 INTEGER);
INSERT INTO t0 VALUES ('x');
CREATE TABLE t1(c0 INTEGER);
INSERT INTO t1 VALUES ('y');
CREATE TABLE t2 (c0 INTEGER);
CREATE TABLE t3 (c0 INTEGER);

SELECT * FROM t2 LEFT OUTER JOIN t3 RIGHT OUTER JOIN t1 RIGHT OUTER JOIN t0 WHERE (t3.c0=t2.c0) ;
SELECT (t3.c0=t2.c0) IS TRUE FROM t2 LEFT OUTER JOIN t3 RIGHT OUTER JOIN t1 RIGHT OUTER JOIN t0 ;
