CREATE TABLE t0(c0);
CREATE TABLE t1(c0);
ALTER TABLE t0 ADD c1 c2;
INSERT INTO t1 VALUES(NULL);
CREATE TABLE t2(c0);

SELECT * FROM t0 CROSS JOIN t2 ON t0.c1 IN (1) RIGHT OUTER JOIN t1 WHERE (t0.c1 IS TRUE);
SELECT t0.c1 IS TRUE FROM t0 CROSS JOIN t2 ON t0.c1 IN (1) RIGHT OUTER JOIN t1;
