CREATE TABLE t0(c0);
CREATE VIEW v0(c0) AS SELECT t0.c0 FROM t0;
CREATE TABLE t1 (c0);
INSERT INTO t0 VALUES ('1');
SELECT SUM(count) FROM (SELECT 1 as count FROM t1 INNER JOIN v0 ON t1.c0 RIGHT OUTER JOIN t0 ON t1.c0 ORDER BY t1.c0);
SELECT SUM(count) FROM (SELECT 1 as count FROM t1 INNER JOIN v0 ON t1.c0 RIGHT OUTER JOIN t0 ON t1.c0);
