CREATE TABLE t0 (c0);
CREATE VIEW v0(c0, c1) AS SELECT CUME_DIST() OVER (PARTITION BY t0.c0), TRUE FROM t0;
INSERT INTO t0 VALUES ('x');

SELECT ALL * FROM v0, t0;
SELECT * FROM v0, t0 WHERE ('1')IS(v0.c1) IS FALSE;
SELECT ('1')IS(v0.c1) IS FALSE FROM v0, t0;
